// ignore_for_file: depend_on_referenced_packages

import 'dart:ui' show TextDirection;

import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
  hide EdgeInsets, Colors, PdfDocument;
import 'package:pdf/pdf.dart' as pdf hide PdfFont;
import 'package:pdf/widgets.dart' as pw;
import 'package:syncfusion_flutter_pdf/pdf.dart' as sf
  hide PdfTextStyle, PdfGridStyle, PdfBorderStyle, PdfGridColumn, PdfGridRow;

Future<sf.PdfDocument> buildExportSampleDocument(
  GeniusPdfConfig config,
) async {
  final isRtl = config.textDirection == TextDirection.rtl;

  final builder = GeniusPdfBuilder(id: 'export-demo', config: config)
      .metadata(
        title: 'Export Demo Document',
        author: 'Genius PDF Generator',
        subject: 'Multi-format export sample',
        keywords: 'export, pdf, png, html, text, pdfa',
      )
      .pageFormat(pdf.PdfPageFormat.a4)
      .rtl(isRtl)
      .addPage(
        (page) => page
            .header('Multi-Format Export Demo')
            .spacer(8)
            .paragraph(
              'This document is generated using the v2 Fluent API (GeniusPdfBuilder). '
              'It is used to showcase how the export service converts PDFs into '
              'different output formats while preserving structure and styling.',
            )
            .spacer(10)
            .subheader('Supported Export Formats')
            .bulletList([
              'PNG (high-quality raster image)',
              'JPEG (compressed raster image)',
              'HTML (web-friendly with embedded assets)',
              'Text (plain text extraction)',
              'PDF/A (archival standard)',
            ])
            .spacer(8)
            .subheader('Export Matrix')
            .table(
              [
                ['PNG', 'Images', 'High', 'Per-page export'],
                ['JPEG', 'Images', 'Medium', 'Smaller size'],
                ['HTML', 'Document', 'N/A', 'Embeddable'],
                ['Text', 'Document', 'N/A', 'Extraction only'],
                ['PDF/A', 'Archival', 'N/A', 'Long-term storage'],
              ],
              headers: ['Format', 'Category', 'Quality', 'Notes'],
            )
            .spacer(8)
            .richText([
              pw.TextSpan(
                text: 'Tip: ',
                style: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  color: pdf.PdfColors.blueGrey,
                ),
              ),
              const pw.TextSpan(
                text:
                    'For batch export, select multiple formats to generate outputs '
                    'in parallel and compare size/quality trade-offs.',
              ),
            ])
            .spacer(10)
            .container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                color: pdf.PdfColors.grey200,
                borderRadius: pw.BorderRadius.circular(6),
                border: pw.Border.all(color: pdf.PdfColors.grey400),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Export Checklist',
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                  ),
                  pw.SizedBox(height: 6),
                  pw.Bullet(text: 'Confirm page count'),
                  pw.Bullet(text: 'Choose format & quality'),
                  pw.Bullet(text: 'Validate output paths'),
                ],
              ),
            )
            .spacer(12)
            .footer('Generated by Genius Link PDF Generator')
            .build(),
      )
      .addPage(
        (page) => page
            .header('Page 2 - Multi-Page Export')
            .spacer(8)
            .paragraph(
              'This page demonstrates multi-page export functionality. '
              'Each page can be exported separately or together while '
              'maintaining layout and typography.',
            )
            .spacer(10)
            .subheader('Sample Metrics')
            .table(
              [
                ['Pages', '2'],
                ['Formats', 'PNG, HTML, Text'],
                ['Processing', 'Async + Progress callbacks'],
              ],
              headers: ['Metric', 'Value'],
            )
            .spacer(10)
            .paragraph(
              'Use the export controls in the UI to generate the different '
              'formats and review their output quality and file size.',
            )
            .spacer(12)
            .footer('Export demo - page 2')
            .build(),
      );

  final bytes = await builder.buildBytes();
  return sf.PdfDocument(inputBytes: bytes);
}
