// Generated by create_template_image_export_examples.py.
// Each public export function below is intentionally self-contained so the
// exact function can be shown verbatim in `Dart usage code`.

import 'dart:typed_data';

import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

import 'package:genius_pdf_example/features/business_templates/models/documents/financial_templates.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/hr_templates.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/sales_templates.dart';
import 'package:genius_pdf_example/shared/presentation/controllers/demo_document_controller.dart';

import 'package:genius_pdf_example/features/templates/models/documents/templates_demo_documents.dart';
/// Result of exporting every page of one template to raster images.
final class TemplateImageExportResult {
  const TemplateImageExportResult({
    required this.pages,
    required this.filePaths,
    required this.format,
    required this.quality,
  });

  final List<Uint8List> pages;
  final List<String> filePaths;
  final GeniusExportFormat format;
  final GeniusImageQuality quality;

  int get pageCount => pages.length;
}

/// Builds the Balance Sheet template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportBalanceSheetTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildBalanceSheetDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Income Statement template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportIncomeStatementTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildIncomeStatementDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Cash Flow template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportCashFlowTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildCashFlowDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Budget Report template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportBudgetReportTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildBudgetReportDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Quotation template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportQuotationTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildQuotationDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Purchase Order template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportPurchaseOrderTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildPurchaseOrderDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Delivery Note template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportDeliveryNoteTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildDeliveryNoteDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Credit Note template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportCreditNoteTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildCreditNoteDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Payslip template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportPayslipTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildPayslipDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Employee Report template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportEmployeeReportTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildEmployeeReportDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Attendance Report template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportAttendanceReportTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildAttendanceReportDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Leave Report template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportLeaveReportTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final demo = buildLeaveReportDemo(isRtl: isRtl);
  PdfDocument? document;
  try {
    final pdfBytes = Uint8List.fromList(demo.builder.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                '${demo.fileName}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);
        case GeniusExportFailure(:final message):
          throw StateError(message);
      }
    }

    if (pages.isEmpty) {
      throw StateError('The template did not produce any image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    demo.builder.dispose();
  }
}

/// Builds the Trial Balance template and exports every PDF page as an image.
Future<TemplateImageExportResult> exportTrialBalanceTemplateAsImages({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
}) async {
  if (format != GeniusExportFormat.png &&
      format != GeniusExportFormat.jpeg) {
    throw ArgumentError.value(format, 'format', 'PNG or JPEG is required.');
  }

  final template = buildTrialBalanceTemplate(isRtl: isRtl);
  PdfDocument? document;

  try {
    final pdfBytes = Uint8List.fromList(template.generate());
    document = PdfDocument(inputBytes: pdfBytes);

    final results = await document.exportToImages(
      format: format,
      quality: quality,
    );

    final pages = <Uint8List>[];
    final filePaths = <String>[];
    for (var index = 0; index < results.length; index++) {
      final result = results[index];
      switch (result) {
        case GeniusExportSuccess(:final data):
          pages.add(data);
          final direction = isRtl ? 'rtl' : 'ltr';
          final path = await documents.saveBytes(
            bytes: data,
            fileName:
                'trial_balance_${direction}_page_${index + 1}.${format.extension}',
          );
          filePaths.add(path);

        case GeniusExportFailure(:final message):
          throw StateError('Trial Balance image export failed: $message');
      }
    }

    if (pages.isEmpty) {
      throw StateError('The Trial Balance template did not produce image pages.');
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: filePaths,
      format: format,
      quality: quality,
    );
  } finally {
    document?.dispose();
    template.dispose();
  }
}
