// DART_USAGE_SYNC_V1
// GENERATED by sync_dart_usage_with_generation.py.
// Do not add illustrative/placeholder snippets here. Every entry below is
// derived from the code that exists in this repository.

import 'package:genius_pdf_example/app/navigation/showcase_catalog.dart';

abstract final class ShowcaseUsageSources {
  static const Map<String, String> _workbench = <String, String>{
    'getting-started': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.basic.name,
    config: config,
  ),
  fileName: 'showcase_getting_started',
  runInBackground: false,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.basic.name,
    config: config,
  ),
  fileName: 'showcase_getting_started',
  runInBackground: false,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class _BasicDocument extends GeniusPdfDocumentBuilder {
  _BasicDocument(super.config);
  @override
  void build() {
    addHeader(title: 'Genius PDF developer showcase');
    addLine('A compact working document generated by the example application.');
    addSpace(12);
    addLine('Use the action toolbar to preview, save, open, share, or print it.');
    addFooter(userName: 'Example app', showPageNumber: true);
  }
}''',
    'document-builder': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.basic.name,
    config: config,
  ),
  fileName: 'showcase_document_builder',
  runInBackground: false,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.basic.name,
    config: config,
  ),
  fileName: 'showcase_document_builder',
  runInBackground: false,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class _BasicDocument extends GeniusPdfDocumentBuilder {
  _BasicDocument(super.config);
  @override
  void build() {
    addHeader(title: 'Genius PDF developer showcase');
    addLine('A compact working document generated by the example application.');
    addSpace(12);
    addLine('Use the action toolbar to preview, save, open, share, or print it.');
    addFooter(userName: 'Example app', showPageNumber: true);
  }
}''',
    'typography': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.typography.name,
    config: config,
  ),
  fileName: 'showcase_typography',
  runInBackground: false,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.typography.name,
    config: config,
  ),
  fileName: 'showcase_typography',
  runInBackground: false,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class _TypographyDocument extends GeniusPdfDocumentBuilder {
  _TypographyDocument(super.config);
  @override
  void build() {
    addHeader(title: 'Text and typography');
    addLine('Body copy rendered with the configured primary font.');
    addLine('Bold and heading roles are supplied independently by GeniusPdfConfig.');
    addSpace(12);
    addRichText(
      GeniusPdfRichText(
        config: config,
        spans: const [
          GeniusPdfTextSpan(text: 'Rich text combines '),
          GeniusPdfTextSpan(text: 'emphasis', isBold: true),
          GeniusPdfTextSpan(text: ', color and structured inline content.'),
        ],
      ),
    );
    addFooter(userName: 'Typography demo', showPageNumber: true);
  }
}''',
    'directionality': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.directionality.name,
    config: config,
  ),
  fileName: 'showcase_directionality',
  runInBackground: false,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.directionality.name,
    config: config,
  ),
  fileName: 'showcase_directionality',
  runInBackground: false,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class _DirectionalityDocument extends GeniusPdfDocumentBuilder {
  _DirectionalityDocument(super.config);
  @override
  void build() {
    addHeader(title: 'تقرير ثنائي اللغة');
    addLine('يدعم المستند اتجاه الكتابة من اليمين إلى اليسار.');
    addLine('Genius PDF also supports LTR content in the same application.');
    addSpace(12);
    addLine('Arabic / English • العربية / English');
    addFooter(userName: 'مثال المطورين', showPageNumber: true);
  }
}''',
    'headers-footers': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.headers.name,
    config: config,
  ),
  fileName: 'showcase_headers_footers',
  runInBackground: false,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.headers.name,
    config: config,
  ),
  fileName: 'showcase_headers_footers',
  runInBackground: false,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class HeadersDemoBuilder extends GeniusPdfDocumentBuilder {
  HeadersDemoBuilder(super.config);

  late final _companyInfo = GeniusPdfCompanyInfo(
    name: 'Al-Amal Trading Company',
    nameAr: 'شركة الأمل للتجارة',
    vatNumber: '300123456789003',
    crNumber: '1010123456',
    address: 'King Fahd Road',
    addressAr: 'طريق الملك فهد',
    city: 'Riyadh',
    cityAr: 'الرياض',
    country: 'Saudi Arabia',
    countryAr: 'المملكة العربية السعودية',
    phone: '+966 11 123 4567',
    email: 'info@alamal.com',
  );

  /// Extended company info with more details
  late final _fullCompanyInfo = GeniusPdfCompanyInfo(
    name: 'Al-Amal Trading Company',
    nameAr: 'شركة الأمل للتجارة',
    vatNumber: '300123456789003',
    crNumber: '1010123456',
    licenseNumber: 'LIC-2025-00123',
    address: 'King Fahd Road, Building 45',
    addressAr: 'طريق الملك فهد، مبنى 45',
    addressLine2: 'Floor 3, Office 301',
    addressLine2Ar: 'الطابق 3، مكتب 301',
    city: 'Riyadh',
    cityAr: 'الرياض',
    postalCode: '12345',
    country: 'Saudi Arabia',
    countryAr: 'المملكة العربية السعودية',
    phone: '+966 11 123 4567',
    phone2: '+966 11 765 4321',
    fax: '+966 11 123 4568',
    email: 'info@alamal.com',
    email2: 'support@alamal.com',
    website: 'www.alamal.com',
    slogan: 'Excellence in Trading',
    sloganAr: 'التميز في التجارة',
  );

  /// Info groups for structured header content
  late final _registrationGroup = GeniusPdfHeaderInfoGroup.registration(
    vatNumber: '300123456789003',
    crNumber: '1010123456',
    licenseNumber: 'LIC-2025-00123',
  );

  late final _contactGroup = GeniusPdfHeaderInfoGroup.contact(
    phone: '+966 11 123 4567',
    email: 'info@alamal.com',
    website: 'www.alamal.com',
  );

  @override
  void build() {
    // 1. Invoice Header (Standard Style)
    _buildInvoiceHeader();

    // 2. Bilingual Split Header (Fixed in v2.12.7)
    _buildBilingualSplitHeader();

    // 3. Bilingual Split with RTL Config
    _buildBilingualSplitRTLHeader();

    // 4. Corporate Header with Info Groups
    _buildCorporateWithGroupsHeader();

    // 5. Saudi Style Header
    _buildSaudiStyleHeader();

    // 6. Letterhead Style
    _buildLetterheadHeader();

    // 7. Minimal Header
    _buildMinimalHeader();

    // 8. Full Company Details Header
    _buildFullDetailsHeader();
  }

  void _buildInvoiceHeader() {
    newPage();
    addSectionDivider(
      title: config.isRTL ? 'فاتورة ضريبية - Invoice' : 'Invoice Header',
      spacing: 10,
    );
    addSpace(20);
    addReportHeader(
      GeniusPdfReportHeader(
        config: config,
        title: 'Tax Invoice',
        titleAr: 'فاتورة ضريبية',
        subtitle: 'Invoice #INV-2024-001',
        subtitleAr: 'فاتورة رقم #INV-2024-001',
        company: _companyInfo,
        printDate: DateTime.now(),
        documentNumber: 'INV-2024-001',
        documentNumberLabel: 'Invoice No',
        documentNumberLabelAr: 'رقم الفاتورة',
        style: GeniusPdfReportHeaderStyle.invoice(),
      ),
      spacing: 15,
    );
    addSpace(20);
    _addExplanation(
      'Standard invoice header with logo (if provided), company info on one side, and title/document info on the other.',
      'رأس فاتورة قياسي مع شعار (إذا توفر)، معلومات الشركة في جانب، والعنوان/معلومات المستند في الجانب الآخر.',
    );
  }

  void _buildBilingualSplitHeader() {
    newPage();
    addSectionDivider(
      title: config.isRTL ? 'مزدوج اللغة - Bilingual' : 'Bilingual Header',
      spacing: 10,
    );
    addSpace(20);
    addReportHeader(
      GeniusPdfReportHeader.bilingualSplit(
        config: config,
        title: 'Trial Balance',
        titleAr: 'ميزان المراجعة',
        subtitle: 'As of December 31, 2025',
        subtitleAr: 'كما في 31 ديسمبر 2025',
        company: _companyInfo,
        date: DateTime.now(),
      ),
      spacing: 15,
    );
    addSpace(20);
    _addExplanation(
      'Split layout: English info on left, Arabic info on right, logo centered. '
      'Fixed in v2.12.7 to work correctly with both RTL and LTR configurations.',
      'تخطيط مقسم: المعلومات الإنجليزية يساراً، العربية يميناً، والشعار في المنتصف. '
      'تم إصلاحه في v2.12.7 ليعمل بشكل صحيح مع كل من إعدادات RTL و LTR.',
    );
  }

  void _buildBilingualSplitRTLHeader() {
    newPage();
    addSectionDivider(
      title: config.isRTL
          ? 'ثنائي اللغة (RTL) - Bilingual RTL'
          : 'Bilingual Header (RTL Config)',
      spacing: 10,
    );
    addSpace(20);

    // Create RTL config for this header specifically
    addReportHeader(
      GeniusPdfReportHeader.bilingualSplit(
        config: config,
        title: 'Financial Statement',
        titleAr: 'القوائم المالية',
        subtitle: 'For the Year Ended December 31, 2025',
        subtitleAr: 'للسنة المنتهية في 31 ديسمبر 2025',
        company: _fullCompanyInfo,
        date: DateTime.now(),
        style: GeniusPdfReportHeaderStyle.bilingualSplit(
          primaryColor: const Color(0xFF006C35),
          accentColor: const Color(0xFF004D26),
        ),
      ),
      spacing: 15,
    );
    addSpace(20);
    _addExplanation(
      'Bilingual split header with full company details and Saudi green theme. '
      'The layout maintains correct positioning regardless of global RTL setting.',
      'رأس ثنائي اللغة مع تفاصيل الشركة الكاملة والنمط السعودي الأخضر. '
      'يحافظ التخطيط على الموضع الصحيح بغض النظر عن إعداد RTL العام.',
    );
  }

  void _buildCorporateWithGroupsHeader() {
    newPage();
    addSectionDivider(
      title: config.isRTL
          ? 'رأس مؤسسي مع مجموعات - Corporate with Groups'
          : 'Corporate Header with Info Groups',
      spacing: 10,
    );
    addSpace(20);
    addReportHeader(
      GeniusPdfReportHeader(
        config: config,
        title: 'Annual Report',
        titleAr: 'التقرير السنوي',
        subtitle: 'Fiscal Year 2025',
        subtitleAr: 'السنة المالية 2025',
        company: _companyInfo,
        printDate: DateTime.now(),
        style: GeniusPdfReportHeaderStyle.corporate(
          primaryColor: const Color(0xFF1565C0),
          showAccentLine: true,
        ),
        infoGroups: [_registrationGroup, _contactGroup],
        layout: GeniusPdfReportHeaderLayout.standard,
      ),
      spacing: 15,
    );
    addSpace(20);
    _addExplanation(
      'Corporate header using info groups for structured display of registration '
      'and contact information. Groups can be customized with titles and styling.',
      'رأس مؤسسي يستخدم مجموعات المعلومات للعرض المنظم لمعلومات التسجيل '
      'والتواصل. يمكن تخصيص المجموعات بالعناوين والتنسيق.',
    );
  }

  void _buildSaudiStyleHeader() {
    newPage();
    addSectionDivider(
      title: config.isRTL ? 'النمط السعودي - Saudi Style' : 'Saudi Style Header',
      spacing: 10,
    );
    addSpace(20);
    addReportHeader(
      GeniusPdfReportHeader(
        config: config,
        title: 'Commercial License',
        titleAr: 'الرخصة التجارية',
        subtitle: 'Ministry of Commerce',
        subtitleAr: 'وزارة التجارة',
        company: _fullCompanyInfo,
        printDate: DateTime.now(),
        style: GeniusPdfReportHeaderStyle.saudi(
          primaryColor: const Color(0xFF006C35),
        ),
        layout: GeniusPdfReportHeaderLayout.standard,
        showBilingualTitle: true,
        bilingualTitleOrder: GeniusPdfBilingualOrder.arabicFirst,
      ),
      spacing: 15,
    );
    addSpace(20);
    _addExplanation(
      'Saudi-themed header with green color scheme, top and bottom borders, '
      'and Arabic-first bilingual titles suitable for official Saudi documents.',
      'رأس بالنمط السعودي مع مخطط الألوان الأخضر، حدود علوية وسفلية، '
      'وعناوين ثنائية اللغة بالعربية أولاً مناسبة للمستندات السعودية الرسمية.',
    );
  }

  void _buildLetterheadHeader() {
    newPage();
    addSectionDivider(
      title: config.isRTL ? 'ورق رسمي - Letterhead' : 'Letterhead Header',
      spacing: 10,
    );
    addSpace(20);
    addReportHeader(
      GeniusPdfReportHeader(
        config: config,
        title: 'Official Letter',
        titleAr: 'خطاب رسمي',
        subtitle: 'Reference: REF-2025-001',
        subtitleAr: 'المرجع: REF-2025-001',
        company: _companyInfo,
        printDate: DateTime.now(),
        referenceNumber: 'REF-2025-001',
        referenceLabel: 'Reference',
        referenceLabelAr: 'المرجع',
        layout: GeniusPdfReportHeaderLayout.letterhead,
        style: GeniusPdfReportHeaderStyle.classic(),
      ),
      spacing: 15,
    );
    addSpace(20);
    _addExplanation(
      'Classic letterhead style layout suitable for official correspondence '
      'with reference numbers and formal styling.',
      'نمط الورق الرسمي الكلاسيكي مناسب للمراسلات الرسمية '
      'مع أرقام المراجع والتنسيق الرسمي.',
    );
  }

  void _buildMinimalHeader() {
    newPage();
    addSectionDivider(
      title: config.isRTL ? 'بسيط - Minimal' : 'Minimal Header',
      spacing: 10,
    );
    addSpace(20);
    addReportHeader(
      GeniusPdfReportHeader.simple(
        config: config,
        title: 'Quick Summary',
        titleAr: 'ملخص سريع',
        subtitle: 'Generated Report',
        subtitleAr: 'تقرير مولد',
        date: DateTime.now(),
        style: GeniusPdfReportHeaderStyle.minimal(
          accentColor: const Color(0xFF424242),
        ),
      ),
      spacing: 15,
    );
    addSpace(20);
    _addExplanation(
      'Simple header with just title, subtitle, and date. No company details. '
      'Ideal for internal reports or quick summaries.',
      'رأس بسيط يحتوي فقط على العنوان والعنوان الفرعي والتاريخ. بدون تفاصيل الشركة. '
      'مثالي للتقارير الداخلية أو الملخصات السريعة.',
    );
  }

  void _buildFullDetailsHeader() {
    newPage();
    addSectionDivider(
      title: config.isRTL
          ? 'تفاصيل كاملة - Full Details'
          : 'Full Company Details Header',
      spacing: 10,
    );
    addSpace(20);

    // Custom info groups with titles
    final customGroups = [
      GeniusPdfHeaderInfoGroup.custom(
        title: 'Registration Info',
        titleAr: 'معلومات التسجيل',
        items: [
          GeniusPdfHeaderInfoItem(
            label: 'VAT No',
            labelAr: 'الرقم الضريبي',
            value: '300123456789003',
          ),
          GeniusPdfHeaderInfoItem(
            label: 'CR No',
            labelAr: 'السجل التجاري',
            value: '1010123456',
          ),
          GeniusPdfHeaderInfoItem(
            label: 'License',
            labelAr: 'الترخيص',
            value: 'LIC-2025-00123',
          ),
        ],
        showTitle: true,
      ),
      GeniusPdfHeaderInfoGroup.custom(
        title: 'Contact',
        titleAr: 'التواصل',
        items: [
          GeniusPdfHeaderInfoItem(
            label: 'Phone',
            labelAr: 'الهاتف',
            value: '+966 11 123 4567',
          ),
          GeniusPdfHeaderInfoItem(
            label: 'Email',
            labelAr: 'البريد',
            value: 'info@alamal.com',
          ),
          GeniusPdfHeaderInfoItem(
            label: 'Website',
            labelAr: 'الموقع',
            value: 'www.alamal.com',
          ),
        ],
        showTitle: true,
      ),
    ];

    addReportHeader(
      GeniusPdfReportHeader(
        config: config,
        title: 'Comprehensive Report',
        titleAr: 'تقرير شامل',
        subtitle: 'With All Company Details',
        subtitleAr: 'مع جميع تفاصيل الشركة',
        company: _fullCompanyInfo,
        printDate: DateTime.now(),
        documentNumber: 'DOC-2025-001',
        documentNumberLabel: 'Document No',
        documentNumberLabelAr: 'رقم المستند',
        style: GeniusPdfReportHeaderStyle.modern(),
        infoGroups: customGroups,
        showPageNumber: true,
        pageNumber: 1,
        totalPages: 10,
      ),
      spacing: 15,
    );
    addSpace(20);
    _addExplanation(
      'Header with full company details, custom info groups with section titles, '
      'document number, page numbers, and modern styling. '
      'Demonstrates all available header customization options.',
      'رأس مع تفاصيل الشركة الكاملة، مجموعات معلومات مخصصة مع عناوين الأقسام، '
      'رقم المستند، أرقام الصفحات، والتنسيق الحديث. '
      'يوضح جميع خيارات تخصيص الرأس المتاحة.',
    );
  }

  void _addExplanation(String en, String ar) {
    addLine(
      config.isRTL ? ar : en,
      font: baseFont,
      brush: PdfBrushes.darkGray,
    );
  }
}''',
    'tables-reports': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.grid.name,
    config: config,
  ),
  fileName: 'showcase_tables_reports',
  runInBackground: false,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.grid.name,
    config: config,
  ),
  fileName: 'showcase_tables_reports',
  runInBackground: false,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class DataGridDemoBuilder extends GeniusPdfDocumentBuilder {
  DataGridDemoBuilder(super.config);

  @override
  void build() {
    // ================================================================
    // PAGE 1: Basic Invoice Grid with Multiple Total Rows
    // ================================================================
    newPage();

    addSectionDivider(
      title: config.isRTL
          ? 'جدول البيانات v2.12.0 — GeniusPdfDataGrid'
          : 'Data Grid v2.12.0 — GeniusPdfDataGrid',
      spacing: 10,
    );

    addLine(
      config.isRTL
          ? 'مثال ١: فاتورة مع صفوف إجمالية متعددة (مجموع فرعي، ضريبة، خصم، إجمالي كلي)'
          : 'Example 1: Invoice with multiple total rows (subtotal, tax, discount, grand total)',
      topMargin: 5,
    );

    addSpace(12);

    // Invoice grid with multiple footer rows
    addGrid(
      GeniusPdfDataGrid(
        config: config,
        columns: [
          GeniusPdfGridColumn(
            id: 'code',
            title: 'Code',
            titleAr: 'الكود',
            width: 55,
            alignment: GeniusPdfTextAlign.center,
          ),
          GeniusPdfGridColumn(
            id: 'desc',
            title: 'Description',
            titleAr: 'الوصف',
            flexFactor: 3,
          ),
          GeniusPdfGridColumn.numeric(
            id: 'qty',
            title: 'Qty',
            titleAr: 'الكمية',
            width: 45,
            alignment: GeniusPdfTextAlign.center,
          ),
          GeniusPdfGridColumn.currency(
            id: 'price',
            title: 'Unit Price',
            titleAr: 'سعر الوحدة',
            currencySymbol: config.isRTL ? 'ر.س' : 'SAR',
            widthPercent: 0.18,
          ),
          GeniusPdfGridColumn.currency(
            id: 'total',
            title: 'Total',
            titleAr: 'الإجمالي',
            currencySymbol: config.isRTL ? 'ر.س' : 'SAR',
            widthPercent: 0.20,
          ),
        ],
        rows: [
          GeniusPdfGridRow(cells: {
            'code': 'PRD-001',
            'desc': config.isRTL ? 'حاسوب محمول - Dell Latitude' : 'Laptop - Dell Latitude',
            'qty': 3,
            'price': 4500.00,
            'total': 13500.00,
          }),
          GeniusPdfGridRow(cells: {
            'code': 'PRD-002',
            'desc': config.isRTL ? 'شاشة عرض 27 بوصة' : 'Monitor 27" 4K Display',
            'qty': 5,
            'price': 1200.00,
            'total': 6000.00,
          }),
          GeniusPdfGridRow(cells: {
            'code': 'PRD-003',
            'desc': config.isRTL ? 'طابعة ليزرية' : 'Laser Printer',
            'qty': 2,
            'price': 2800.00,
            'total': 5600.00,
          }),
          GeniusPdfGridRow(cells: {
            'code': 'SRV-001',
            'desc': config.isRTL ? 'خدمة التركيب والتشغيل' : 'Installation & Setup Service',
            'qty': 1,
            'price': 1500.00,
            'total': 1500.00,
          }),
          GeniusPdfGridRow(cells: {
            'code': 'SRV-002',
            'desc': config.isRTL ? 'ضمان ممتد - سنتان' : 'Extended Warranty - 2 Years',
            'qty': 10,
            'price': 350.00,
            'total': 3500.00,
          }),
        ],
        // Multiple explicit footer rows with different styles
        footerRows: [
          GeniusPdfGridRow.subtotal({
            'desc': config.isRTL ? 'المجموع الفرعي' : 'Subtotal',
            'total': 30100.00,
          }),
          GeniusPdfGridRow(
            cells: {
              'desc': config.isRTL ? 'خصم (5%)' : 'Discount (5%)',
              'total': -1505.00,
            },
            isSubtotal: true,
          ),
          GeniusPdfGridRow(
            cells: {
              'desc': config.isRTL ? 'ضريبة القيمة المضافة (15%)' : 'VAT (15%)',
              'total': 4289.25,
            },
            isSubtotal: true,
          ),
          GeniusPdfGridRow.total({
            'desc': config.isRTL ? 'الإجمالي المستحق' : 'Total Due',
            'total': 32884.25,
          }),
        ],
        style: GeniusPdfGridStyle.invoice(),
      ),
      spacing: 12,
    );

    // ================================================================
    // PAGE 1: Auto-Calculated Totals
    // ================================================================
    addSpace(25);

    addSectionDivider(
      title: config.isRTL
          ? 'مثال ٢: إجماليات محسوبة تلقائياً'
          : 'Example 2: Auto-Calculated Totals',
      spacing: 10,
    );

    addLine(
      config.isRTL
          ? 'يقوم الجدول بحساب المجموع والمتوسط والعدد تلقائياً من بيانات الصفوف.'
          : 'The grid automatically calculates sum, average, and count from row data.',
      topMargin: 5,
    );

    addSpace(10);

    addGrid(
      GeniusPdfDataGrid(
        config: config,
        columns: [
          GeniusPdfGridColumn(
            id: 'employee',
            title: 'Employee',
            titleAr: 'الموظف',
            flexFactor: 2,
          ),
          GeniusPdfGridColumn(
            id: 'dept',
            title: 'Department',
            titleAr: 'القسم',
            flexFactor: 1,
          ),
          GeniusPdfGridColumn.currency(
            id: 'salary',
            title: 'Salary',
            titleAr: 'الراتب',
            isNumeric: true,
            width: 90,
          ),
          GeniusPdfGridColumn.currency(
            id: 'bonus',
            title: 'Bonus',
            titleAr: 'المكافأة',
            isNumeric: true,
            width: 80,
          ),
          GeniusPdfGridColumn.currency(
            id: 'net',
            title: 'Net Pay',
            titleAr: 'صافي الدفع',
            isNumeric: true,
            width: 100,
          ),
        ],
        rows: [
          GeniusPdfGridRow(cells: {'employee': config.isRTL ? 'أحمد محمد' : 'Ahmed M.', 'dept': config.isRTL ? 'تقنية' : 'IT', 'salary': 12000, 'bonus': 2000, 'net': 14000}),
          GeniusPdfGridRow(cells: {'employee': config.isRTL ? 'سارة علي' : 'Sara A.', 'dept': config.isRTL ? 'مالية' : 'Finance', 'salary': 10000, 'bonus': 1500, 'net': 11500}),
          GeniusPdfGridRow(cells: {'employee': config.isRTL ? 'خالد يوسف' : 'Khalid Y.', 'dept': config.isRTL ? 'تقنية' : 'IT', 'salary': 15000, 'bonus': 3000, 'net': 18000}),
          GeniusPdfGridRow(cells: {'employee': config.isRTL ? 'فاطمة حسن' : 'Fatima H.', 'dept': config.isRTL ? 'موارد' : 'HR', 'salary': 9000, 'bonus': 1000, 'net': 10000}),
          GeniusPdfGridRow(cells: {'employee': config.isRTL ? 'عمر سالم' : 'Omar S.', 'dept': config.isRTL ? 'مبيعات' : 'Sales', 'salary': 11000, 'bonus': 4000, 'net': 15000}),
        ],
        // Auto-calculated total rows
        autoTotals: [
          GeniusPdfAutoTotal.sum(
            label: 'Total',
            labelAr: 'الإجمالي',
            labelColumnId: 'employee',
            columnIds: ['salary', 'bonus', 'net'],
          ),
          GeniusPdfAutoTotal.average(
            label: 'Average',
            labelAr: 'المتوسط',
            labelColumnId: 'employee',
            columnIds: ['salary', 'bonus', 'net'],
          ),
          GeniusPdfAutoTotal.count(
            label: 'Count',
            labelAr: 'العدد',
            labelColumnId: 'employee',
            columnIds: ['salary'],
          ),
        ],
        style: GeniusPdfGridStyle.corporate(),
      ),
      spacing: 10,
    );

    // ================================================================
    // PAGE 2: Grouped Data with Subgroups
    // ================================================================
    newPage();

    addSectionDivider(
      title: config.isRTL
          ? 'مثال ٣: مجموعات مع مجموعات فرعية'
          : 'Example 3: Groups with Nested Subgroups',
      spacing: 10,
    );

    addLine(
      config.isRTL
          ? 'جدول مُجمَّع حسب الفئة مع مجموعات فرعية وإجماليات لكل مجموعة.'
          : 'Grouped table by category with nested subgroups and per-group totals.',
      topMargin: 5,
    );

    addSpace(10);

    addGrid(
      GeniusPdfDataGrid(
        config: config,
        columns: [
          GeniusPdfGridColumn(
            id: 'item',
            title: 'Item',
            titleAr: 'الصنف',
            flexFactor: 2,
          ),
          GeniusPdfGridColumn.numeric(
            id: 'qty',
            title: 'Qty',
            titleAr: 'الكمية',
            width: 50,
            alignment: GeniusPdfTextAlign.center,
          ),
          GeniusPdfGridColumn.currency(
            id: 'price',
            title: 'Unit Price',
            titleAr: 'سعر الوحدة',
            width: 90,
            isNumeric: true,
          ),
          GeniusPdfGridColumn.currency(
            id: 'total',
            title: 'Total',
            titleAr: 'الإجمالي',
            width: 100,
            isNumeric: true,
          ),
        ],
        rows: [],
        groups: [
          // Group 1: Electronics with subgroups
          GeniusPdfGridGroup(
            title: 'Electronics',
            titleAr: 'إلكترونيات',
            rows: const [],
            subgroups: [
              GeniusPdfGridGroup.withSummary(
                title: 'Computers',
                titleAr: 'حواسيب',
                rows: [
                  GeniusPdfGridRow(cells: {'item': config.isRTL ? 'لابتوب HP' : 'HP Laptop', 'qty': 5, 'price': 3200, 'total': 16000}),
                  GeniusPdfGridRow(cells: {'item': config.isRTL ? 'لابتوب Dell' : 'Dell Laptop', 'qty': 3, 'price': 4500, 'total': 13500}),
                ],
                sumColumns: ['total'],
                labelColumnId: 'item',
                summaryLabel: 'Computers Subtotal',
                summaryLabelAr: 'مجموع الحواسيب',
              ),
              GeniusPdfGridGroup.withSummary(
                title: 'Accessories',
                titleAr: 'ملحقات',
                rows: [
                  GeniusPdfGridRow(cells: {'item': config.isRTL ? 'ماوس لاسلكي' : 'Wireless Mouse', 'qty': 20, 'price': 85, 'total': 1700}),
                  GeniusPdfGridRow(cells: {'item': config.isRTL ? 'لوحة مفاتيح' : 'Keyboard', 'qty': 15, 'price': 120, 'total': 1800}),
                ],
                sumColumns: ['total'],
                labelColumnId: 'item',
                summaryLabel: 'Accessories Subtotal',
                summaryLabelAr: 'مجموع الملحقات',
              ),
            ],
            summary: GeniusPdfGridRow.total({
              'item': config.isRTL ? 'إجمالي الإلكترونيات' : 'Electronics Total',
              'total': 33000,
            }),
          ),

          // Group 2: Furniture
          GeniusPdfGridGroup.withSummary(
            title: 'Office Furniture',
            titleAr: 'أثاث مكتبي',
            rows: [
              GeniusPdfGridRow(cells: {'item': config.isRTL ? 'مكتب خشبي' : 'Wooden Desk', 'qty': 8, 'price': 950, 'total': 7600}),
              GeniusPdfGridRow(cells: {'item': config.isRTL ? 'كرسي مكتبي' : 'Office Chair', 'qty': 12, 'price': 650, 'total': 7800}),
              GeniusPdfGridRow(cells: {'item': config.isRTL ? 'خزانة ملفات' : 'Filing Cabinet', 'qty': 5, 'price': 480, 'total': 2400}),
            ],
            sumColumns: ['total'],
            labelColumnId: 'item',
            summaryLabel: 'Furniture Subtotal',
            summaryLabelAr: 'مجموع الأثاث',
          ),
        ],
        // Grand total after all groups
        footerRows: [
          GeniusPdfGridRow.total({
            'item': config.isRTL ? 'الإجمالي الكلي' : 'Grand Total',
            'total': 50800,
          }),
        ],
        style: GeniusPdfGridStyle.corporate(),
      ),
      spacing: 10,
    );

    // ================================================================
    // PAGE 2: Auto-Grouping Utility
    // ================================================================
    addSpace(20);

    addSectionDivider(
      title: config.isRTL
          ? 'مثال ٤: التجميع التلقائي بالأداة المساعدة'
          : 'Example 4: Auto-Grouping via Utility',
      spacing: 10,
    );

    addLine(
      config.isRTL
          ? 'يقوم GeniusDataGridUtils.autoGroup بتجميع الصفوف تلقائياً حسب عمود محدد.'
          : 'GeniusDataGridUtils.autoGroup groups rows by a specified column automatically.',
      topMargin: 5,
    );

    addSpace(10);

    // Raw data rows (mixed departments)
    final allRows = [
      GeniusPdfGridRow(cells: {'name': config.isRTL ? 'أحمد' : 'Ahmed', 'dept': config.isRTL ? 'تقنية' : 'IT', 'hours': 160, 'rate': 50, 'amount': 8000}),
      GeniusPdfGridRow(cells: {'name': config.isRTL ? 'سارة' : 'Sara', 'dept': config.isRTL ? 'مالية' : 'Finance', 'hours': 170, 'rate': 55, 'amount': 9350}),
      GeniusPdfGridRow(cells: {'name': config.isRTL ? 'خالد' : 'Khalid', 'dept': config.isRTL ? 'تقنية' : 'IT', 'hours': 155, 'rate': 60, 'amount': 9300}),
      GeniusPdfGridRow(cells: {'name': config.isRTL ? 'فاطمة' : 'Fatima', 'dept': config.isRTL ? 'مالية' : 'Finance', 'hours': 165, 'rate': 45, 'amount': 7425}),
      GeniusPdfGridRow(cells: {'name': config.isRTL ? 'عمر' : 'Omar', 'dept': config.isRTL ? 'مبيعات' : 'Sales', 'hours': 180, 'rate': 40, 'amount': 7200}),
    ];

    // Auto-group by department with summaries
    final autoGroups = GeniusDataGridUtils.autoGroup(
      rows: allRows,
      groupByColumn: 'dept',
      sumColumns: ['amount'],
      summaryLabelColumnId: 'name',
      summaryLabel: 'Dept Total',
      summaryLabelAr: 'مجموع القسم',
    );

    addGrid(
      GeniusPdfDataGrid(
        config: config,
        columns: [
          GeniusPdfGridColumn(id: 'name', title: 'Name', titleAr: 'الاسم', flexFactor: 2),
          GeniusPdfGridColumn(id: 'dept', title: 'Department', titleAr: 'القسم', width: 80),
          GeniusPdfGridColumn.numeric(id: 'hours', title: 'Hours', titleAr: 'الساعات', width: 60, alignment: GeniusPdfTextAlign.center),
          GeniusPdfGridColumn.currency(id: 'rate', title: 'Rate', titleAr: 'المعدل', width: 70, isNumeric: true),
          GeniusPdfGridColumn.currency(id: 'amount', title: 'Amount', titleAr: 'المبلغ', width: 90, isNumeric: true),
        ],
        rows: [],
        groups: autoGroups,
        autoTotals: [
          GeniusPdfAutoTotal.sum(
            label: 'Grand Total',
            labelAr: 'الإجمالي الكلي',
            labelColumnId: 'name',
            columnIds: ['amount'],
          ),
        ],
        style: GeniusPdfGridStyle.corporate(),
      ),
      spacing: 10,
    );

    // ================================================================
    // PAGE 3: Percentage Column Widths
    // ================================================================
    newPage();

    addSectionDivider(
      title: config.isRTL
          ? 'مثال ٥: أعمدة بنسب مئوية وقيود عرض'
          : 'Example 5: Percentage Columns & Width Constraints',
      spacing: 10,
    );

    addLine(
      config.isRTL
          ? 'widthPercent يحدد عرض العمود كنسبة مئوية من العرض المتاح مع دعم الحد الأدنى والأقصى.'
          : 'widthPercent defines column width as a percentage of available width with min/max constraints.',
      topMargin: 5,
    );

    addSpace(10);

    addGrid(
      GeniusPdfDataGrid(
        config: config,
        columns: [
          GeniusPdfGridColumn(
            id: 'id',
            title: '#',
            titleAr: '#',
            widthPercent: 0.08,
            alignment: GeniusPdfTextAlign.center,
          ),
          GeniusPdfGridColumn(
            id: 'product',
            title: 'Product Name',
            titleAr: 'اسم المنتج',
            widthPercent: 0.32,
          ),
          GeniusPdfGridColumn(
            id: 'category',
            title: 'Category',
            titleAr: 'الفئة',
            widthPercent: 0.15,
          ),
          GeniusPdfGridColumn.numeric(
            id: 'stock',
            title: 'Stock',
            titleAr: 'المخزون',
            widthPercent: 0.10,
            alignment: GeniusPdfTextAlign.center,
          ),
          GeniusPdfGridColumn.currency(
            id: 'cost',
            title: 'Cost',
            titleAr: 'التكلفة',
            widthPercent: 0.15,
            isNumeric: true,
          ),
          GeniusPdfGridColumn.currency(
            id: 'sell',
            title: 'Sell Price',
            titleAr: 'سعر البيع',
            widthPercent: 0.20,
            isNumeric: true,
          ),
        ],
        rows: [
          GeniusPdfGridRow(cells: {'id': 1, 'product': config.isRTL ? 'هاتف ذكي سامسونج' : 'Samsung Phone', 'category': config.isRTL ? 'هواتف' : 'Phones', 'stock': 45, 'cost': 1800, 'sell': 2500}),
          GeniusPdfGridRow(cells: {'id': 2, 'product': config.isRTL ? 'آيفون ١٥' : 'iPhone 15', 'category': config.isRTL ? 'هواتف' : 'Phones', 'stock': 30, 'cost': 3200, 'sell': 4200}),
          GeniusPdfGridRow(cells: {'id': 3, 'product': config.isRTL ? 'سماعات بلوتوث' : 'Bluetooth Headphones', 'category': config.isRTL ? 'إكسسوارات' : 'Accessories', 'stock': 120, 'cost': 150, 'sell': 250}),
          GeniusPdfGridRow(cells: {'id': 4, 'product': config.isRTL ? 'حقيبة لابتوب' : 'Laptop Bag', 'category': config.isRTL ? 'إكسسوارات' : 'Accessories', 'stock': 80, 'cost': 95, 'sell': 180}),
          GeniusPdfGridRow(cells: {'id': 5, 'product': config.isRTL ? 'شاحن سريع' : 'Fast Charger', 'category': config.isRTL ? 'إكسسوارات' : 'Accessories', 'stock': 200, 'cost': 45, 'sell': 85}),
        ],
        autoTotals: [
          GeniusPdfAutoTotal.sum(
            label: 'Total Stock Value',
            labelAr: 'إجمالي قيمة المخزون',
            labelColumnId: 'product',
            columnIds: ['stock', 'cost', 'sell'],
          ),
          GeniusPdfAutoTotal.min(
            label: 'Min',
            labelAr: 'الأدنى',
            labelColumnId: 'product',
            columnIds: ['cost', 'sell'],
          ),
          GeniusPdfAutoTotal.max(
            label: 'Max',
            labelAr: 'الأقصى',
            labelColumnId: 'product',
            columnIds: ['cost', 'sell'],
          ),
        ],
        style: GeniusPdfGridStyle.corporate(),
      ),
      spacing: 10,
    );

    addSpace(20);

    addInfoBox(
      GeniusPdfInfoBox(
        config: config,
        title: config.isRTL ? 'ملخص التحسينات v2.12.0' : 'v2.12.0 Enhancements Summary',
        titleAr: 'ملخص التحسينات v2.12.0',
        items: [
          GeniusPdfLabeledValue(
            config: config,
            label: config.isRTL ? 'أعمدة نسبية' : 'Percentage Columns',
            labelAr: 'أعمدة نسبية',
            value: config.isRTL
                ? 'widthPercent لتحديد عرض العمود كنسبة من العرض الكلي'
                : 'widthPercent to set column width as a ratio of total width',
          ),
          GeniusPdfLabeledValue(
            config: config,
            label: config.isRTL ? 'إجماليات متعددة' : 'Multi Totals',
            labelAr: 'إجماليات متعددة',
            value: config.isRTL
                ? 'footerRows + autoTotals (مجموع، متوسط، عدد، أدنى، أقصى)'
                : 'footerRows + autoTotals (sum, avg, count, min, max)',
          ),
          GeniusPdfLabeledValue(
            config: config,
            label: config.isRTL ? 'مجموعات فرعية' : 'Nested Groups',
            labelAr: 'مجموعات فرعية',
            value: config.isRTL
                ? 'دعم المجموعات المتداخلة مع إجماليات لكل مستوى'
                : 'Nested subgroups with per-level totals',
          ),
          GeniusPdfLabeledValue(
            config: config,
            label: config.isRTL ? 'حساب دقيق' : 'Accurate Widths',
            labelAr: 'حساب دقيق',
            value: config.isRTL
                ? 'خوارزمية محسّنة متعددة المراحل مع إعادة توزيع القيود'
                : 'Multi-pass algorithm with constraint redistribution',
          ),
        ],
        style: GeniusPdfInfoBoxStyle.info(),
      ),
      spacing: 10,
    );

    // ================================================================
    // PAGE 4: Grid Styles Showcase (v2.12.2)
    // ================================================================
    newPage();

    addSectionDivider(
      title: config.isRTL
          ? 'مثال ٦: عرض أنماط الجدول v2.12.2'
          : 'Example 6: Grid Styles Showcase v2.12.2',
      spacing: 10,
    );

    addLine(
      config.isRTL
          ? 'جميع الأنماط تدعم اللون الرئيسي القابل للتخصيص عبر primaryColor.'
          : 'All styles support customizable primary color via the primaryColor parameter.',
      topMargin: 5,
    );

    // Shared sample data for style demos
    final styleColumns = [
      GeniusPdfGridColumn(
        id: 'name',
        title: 'Product',
        titleAr: 'المنتج',
        flexFactor: 2,
      ),
      GeniusPdfGridColumn.numeric(
        id: 'qty',
        title: 'Qty',
        titleAr: 'الكمية',
        width: 50,
        alignment: GeniusPdfTextAlign.center,
      ),
      GeniusPdfGridColumn.currency(
        id: 'price',
        title: 'Price',
        titleAr: 'السعر',
        width: 80,
        isNumeric: true,
      ),
      GeniusPdfGridColumn.currency(
        id: 'total',
        title: 'Total',
        titleAr: 'الإجمالي',
        width: 90,
        isNumeric: true,
      ),
    ];

    final styleRows = [
      GeniusPdfGridRow(cells: {
        'name': config.isRTL ? 'لابتوب' : 'Laptop',
        'qty': 3,
        'price': 4500,
        'total': 13500,
      }),
      GeniusPdfGridRow(cells: {
        'name': config.isRTL ? 'شاشة' : 'Monitor',
        'qty': 5,
        'price': 1200,
        'total': 6000,
      }),
      GeniusPdfGridRow(cells: {
        'name': config.isRTL ? 'طابعة' : 'Printer',
        'qty': 2,
        'price': 2800,
        'total': 5600,
      }),
    ];

    final styleFooter = [
      GeniusPdfGridRow.total({
        'name': config.isRTL ? 'الإجمالي' : 'Total',
        'total': 25100,
      }),
    ];

    // Helper to build a styled grid
    GeniusPdfDataGrid buildStyleGrid(GeniusPdfGridStyle gridStyle) {
      return GeniusPdfDataGrid(
        config: config,
        columns: styleColumns,
        rows: styleRows,
        footerRows: styleFooter,
        style: gridStyle,
      );
    }

    addSpace(10);

    // --- Style 1: Modern (Teal) ---
    addLine(
      config.isRTL
          ? 'modern — اللون الرئيسي: أزرق مخضر (Teal)'
          : 'modern — primaryColor: Teal',
      topMargin: 6,
    );
    addSpace(4);
    addGrid(
      buildStyleGrid(
        GeniusPdfGridStyle.modern(primaryColor: const Color(0xFF00897B)),
      ),
      spacing: 8,
    );

    // --- Style 2: Classic (Indigo) ---
    addLine(
      config.isRTL
          ? 'classic — اللون الرئيسي: نيلي (Indigo)'
          : 'classic — primaryColor: Indigo',
      topMargin: 6,
    );
    addSpace(4);
    addGrid(
      buildStyleGrid(
        GeniusPdfGridStyle.classic(primaryColor: const Color(0xFF3F51B5)),
      ),
      spacing: 8,
    );

    // --- Style 3: Striped (Blue Grey) ---
    addLine(
      config.isRTL
          ? 'striped — اللون الرئيسي: رمادي مُزرق'
          : 'striped — primaryColor: Blue Grey',
      topMargin: 6,
    );
    addSpace(4);
    addGrid(
      buildStyleGrid(
        GeniusPdfGridStyle.striped(primaryColor: const Color(0xFF546E7A)),
      ),
      spacing: 8,
    );

    // --- Style 4: Dark (Dark Blue) ---
    addLine(
      config.isRTL
          ? 'dark — اللون الرئيسي: أزرق داكن'
          : 'dark — primaryColor: Dark Blue',
      topMargin: 6,
    );
    addSpace(4);
    addGrid(
      buildStyleGrid(
        GeniusPdfGridStyle.dark(primaryColor: const Color(0xFF1A237E)),
      ),
      spacing: 8,
    );

    // ================================================================
    // PAGE 5: More Styles with Custom Colors
    // ================================================================
    newPage();

    addSectionDivider(
      title: config.isRTL
          ? 'مثال ٧: أنماط إضافية مع ألوان مخصصة'
          : 'Example 7: More Styles with Custom Colors',
      spacing: 10,
    );

    // --- Style 5: Elegant (Brown) ---
    addLine(
      config.isRTL
          ? 'elegant — اللون الرئيسي: بني (Brown)'
          : 'elegant — primaryColor: Brown',
      topMargin: 6,
    );
    addSpace(4);
    addGrid(
      buildStyleGrid(
        GeniusPdfGridStyle.elegant(primaryColor: const Color(0xFF5D4037)),
      ),
      spacing: 8,
    );

    // --- Style 6: Pastel (Purple) ---
    addLine(
      config.isRTL
          ? 'pastel — اللون الرئيسي: بنفسجي (Purple)'
          : 'pastel — primaryColor: Purple',
      topMargin: 6,
    );
    addSpace(4);
    addGrid(
      buildStyleGrid(
        GeniusPdfGridStyle.pastel(primaryColor: const Color(0xFF7E57C2)),
      ),
      spacing: 8,
    );

    // --- Style 7: Bordered (Green) ---
    addLine(
      config.isRTL
          ? 'bordered — اللون الرئيسي: أخضر (Green)'
          : 'bordered — primaryColor: Green',
      topMargin: 6,
    );
    addSpace(4);
    addGrid(
      buildStyleGrid(
        GeniusPdfGridStyle.bordered(primaryColor: const Color(0xFF2E7D32)),
      ),
      spacing: 8,
    );

    // --- Style 8: Minimal (Orange) ---
    addLine(
      config.isRTL
          ? 'minimal — اللون الرئيسي: برتقالي (Orange)'
          : 'minimal — primaryColor: Orange',
      topMargin: 6,
    );
    addSpace(4);
    addGrid(
      buildStyleGrid(
        GeniusPdfGridStyle.minimal(primaryColor: const Color(0xFFE65100)),
      ),
      spacing: 8,
    );

    // --- Style 9: Saudi (Default Green) ---
    addLine(
      config.isRTL
          ? 'saudi — اللون الافتراضي: أخضر سعودي'
          : 'saudi — default primaryColor: Saudi Green',
      topMargin: 6,
    );
    addSpace(4);
    addGrid(
      buildStyleGrid(GeniusPdfGridStyle.saudi()),
      spacing: 8,
    );

    // --- Style 10: Invoice (Custom Red) ---
    addLine(
      config.isRTL
          ? 'invoice — اللون الرئيسي: أحمر (Red)'
          : 'invoice — primaryColor: Red',
      topMargin: 6,
    );
    addSpace(4);
    addGrid(
      buildStyleGrid(
        GeniusPdfGridStyle.invoice(primaryColor: const Color(0xFFC62828)),
      ),
      spacing: 8,
    );

    addSpace(15);

    addInfoBox(
      GeniusPdfInfoBox(
        config: config,
        title: config.isRTL
            ? 'الأنماط المتاحة v2.12.2'
            : 'Available Styles v2.12.2',
        titleAr: 'الأنماط المتاحة v2.12.2',
        items: [
          GeniusPdfLabeledValue(
            config: config,
            label: config.isRTL ? 'الأنماط' : 'Styles',
            labelAr: 'الأنماط',
            value: 'modern, classic, corporate, minimal, saudi, invoice, striped, dark, elegant, pastel, bordered',
          ),
          GeniusPdfLabeledValue(
            config: config,
            label: config.isRTL ? 'التخصيص' : 'Customization',
            labelAr: 'التخصيص',
            value: config.isRTL
                ? 'جميع الأنماط تدعم primaryColor لتخصيص اللون الرئيسي'
                : 'All styles accept primaryColor for color customization',
          ),
        ],
        style: GeniusPdfInfoBoxStyle.info(),
      ),
      spacing: 10,
    );
  }
}''',
    'media': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.media.name,
    config: config,
  ),
  fileName: 'showcase_media',
  runInBackground: false,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.media.name,
    config: config,
  ),
  fileName: 'showcase_media',
  runInBackground: false,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class QRAttachmentsDemoBuilder extends GeniusPdfDocumentBuilder {
  /// Creates a new [QRAttachmentsDemoBuilder].
  QRAttachmentsDemoBuilder({
    required GeniusPdfConfig config,
    this.userName = 'Demo User',
    this.qrUrl = 'https://genius-link.dev/invoice/demo',
    this.attachmentImages,
  }) : super(config);

  /// User name for the footer.
  final String userName;

  /// URL to encode in the QR code.
  final String qrUrl;

  /// Optional list of images to attach as pages.
  final List<GeniusPdfImage>? attachmentImages;

  @override
  void build() {
    _buildHeader();
    _buildQRCodeSection();
    _buildImageAttachmentSection();
    _buildBatchAttachmentsSection();
    _buildFooter();
  }

  // ──────────────────────────────────────────────────────────
  // Header
  // ──────────────────────────────────────────────────────────

  void _buildHeader() {
    addHeader(
      title: isRTL
          ? 'عرض رمز QR والمرفقات — الإصدار 2.7.0'
          : 'QR Code & Attachments Demo — v2.7.0',
    );
  }

  // ──────────────────────────────────────────────────────────
  // QR Code Section
  // ──────────────────────────────────────────────────────────

  void _buildQRCodeSection() {
    addSectionDivider(
      title: isRTL ? 'رموز QR' : 'QR Codes',
      spacing: 10,
    );

    // URL QR Code — centered
    addLine(
      isRTL ? 'رمز QR للرابط (وسط):' : 'URL QR Code (centered):',
      topMargin: 5,
    );
    addSpace(5);

    final urlQR = GeniusPdfQRCodeGenerator.url(
      url: qrUrl,
      config: config,
    );
    addQRCode(
      urlQR,
      alignment: GeniusPdfImageAlignment.center,
      spacing: 5,
      size: 100,
    );
    addSpace(10);

    // WiFi QR Code — start aligned
    addLine(
      isRTL ? 'رمز QR للواي فاي (بداية):' : 'WiFi QR Code (start-aligned):',
      topMargin: 5,
    );
    addSpace(5);

    final wifiQR = GeniusPdfQRCodeGenerator.wifi(
      ssid: 'GeniusOffice',
      password: 'secure123',
      config: config,
    );
    addQRCode(
      wifiQR,
      alignment: GeniusPdfImageAlignment.start,
      spacing: 5,
      size: 80,
    );
    addSpace(10);

    // vCard QR Code — end aligned
    addLine(
      isRTL
          ? 'رمز QR لبطاقة جهة اتصال (نهاية):'
          : 'vCard QR Code (end-aligned):',
      topMargin: 5,
    );
    addSpace(5);

    final vCardQR = GeniusPdfQRCodeGenerator.vCard(
      name: 'Genius Systems',
      phone: '+966501234567',
      email: 'info@genius-link.dev',
      company: 'Genius Systems LLC',
      config: config,
    );
    addQRCode(
      vCardQR,
      alignment: GeniusPdfImageAlignment.end,
      spacing: 5,
      size: 80,
    );

    addSpace(15);
  }

  // ──────────────────────────────────────────────────────────
  // Image Attachment Section
  // ──────────────────────────────────────────────────────────

  void _buildImageAttachmentSection() {
    addSectionDivider(
      title: isRTL ? 'مرفقات الصور' : 'Image Attachments',
      spacing: 10,
    );

    addLine(
      isRTL
          ? 'يمكنك إرفاق صور مباشرة أو على صفحات مستقلة.'
          : 'You can attach images inline or on dedicated pages.',
      topMargin: 5,
    );

    if (attachmentImages != null && attachmentImages!.isNotEmpty) {
      // Inline attachment with title
      addImageAttachment(
        attachmentImages!.first,
        title: 'Inline Attachment',
        titleAr: 'مرفق مضمن',
        spacing: 10,
      );
    } else {
      addLine(
        isRTL
            ? '(لم يتم تزويد صور — مرر attachmentImages لمشاهدة العرض)'
            : '(No images provided — pass attachmentImages to see the demo)',
        topMargin: 5,
      );
    }

    addSpace(10);
  }

  // ──────────────────────────────────────────────────────────
  // Batch Attachments
  // ──────────────────────────────────────────────────────────

  void _buildBatchAttachmentsSection() {
    if (attachmentImages != null && attachmentImages!.length > 1) {
      // Each additional image gets its own page via addAttachments
      addAttachments(
        attachmentImages!.sublist(1),
        titles: List.generate(
          attachmentImages!.length - 1,
          (i) => 'Attachment ${i + 2}',
        ),
        titlesAr: List.generate(
          attachmentImages!.length - 1,
          (i) => 'مرفق ${i + 2}',
        ),
      );
    }
  }

  // ──────────────────────────────────────────────────────────
  // Footer
  // ──────────────────────────────────────────────────────────

  void _buildFooter() {
    addFooter(
      userName: userName,
      showPageNumber: true,
      printTime: DateTime.now().toString().substring(0, 19),
    );
  }
}''',
    'reusable-components': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.advancedLayout.name,
    config: config,
  ),
  fileName: 'showcase_reusable_components',
  runInBackground: false,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.advancedLayout.name,
    config: config,
  ),
  fileName: 'showcase_reusable_components',
  runInBackground: false,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class AdvancedLayoutDemoBuilder extends GeniusPdfDocumentBuilder {
  /// Creates a new [AdvancedLayoutDemoBuilder].
  AdvancedLayoutDemoBuilder({
    required GeniusPdfConfig config,
    this.userName = 'Demo User',
  }) : super(config);

  /// User name for the footer.
  final String userName;

  @override
  void build() {
    _buildReportHeaderSection();
    _buildTwoColumnSection();
    _buildRichTextSection();
    _buildInfoBoxSection();
    _buildFooter();
  }

  // ──────────────────────────────────────────────────────────
  // Report Header
  // ──────────────────────────────────────────────────────────

  void _buildReportHeaderSection() {
    final header = GeniusPdfReportHeader(
      config: config,
      title: 'Advanced Layout Demo',
      titleAr: 'عرض التخطيط المتقدم',
      subtitle: 'v2.8.0 Features',
      subtitleAr: 'مميزات الإصدار 2.8.0',
      printDate: DateTime.now(),
      showPrintDate: true,
      layout: GeniusPdfReportHeaderLayout.centered,
    );

    addReportHeader(header, spacing: 0, height: 80);
    addSpace(10);
  }

  // ──────────────────────────────────────────────────────────
  // Two-Column Layout
  // ──────────────────────────────────────────────────────────

  void _buildTwoColumnSection() {
    addSectionDivider(
      title: isRTL ? 'تخطيط عمودين' : 'Two-Column Layout',
      spacing: 10,
    );

    addTwoColumns(
      leftContent: (page, bounds) {
        final box = GeniusPdfInfoBox(
          config: config,
          title: 'From',
          titleAr: 'من',
          items: [
            GeniusPdfLabeledValue(
              config: config,
              label: 'Company',
              labelAr: 'الشركة',
              value: 'Genius Systems LLC',
            ),
            GeniusPdfLabeledValue(
              config: config,
              label: 'Address',
              labelAr: 'العنوان',
              value: 'Riyadh, Saudi Arabia',
            ),
            GeniusPdfLabeledValue(
              config: config,
              label: 'VAT No.',
              labelAr: 'الرقم الضريبي',
              value: '310123456789003',
            ),
          ],
          style: const GeniusPdfInfoBoxStyle.card(),
        );
        final rect = box.draw(page: page, bounds: bounds);
        return rect.height;
      },
      rightContent: (page, bounds) {
        final box = GeniusPdfInfoBox(
          config: config,
          title: 'To',
          titleAr: 'إلى',
          items: [
            GeniusPdfLabeledValue(
              config: config,
              label: 'Customer',
              labelAr: 'العميل',
              value: 'ABC Trading Co.',
            ),
            GeniusPdfLabeledValue(
              config: config,
              label: 'Address',
              labelAr: 'العنوان',
              value: 'Jeddah, Saudi Arabia',
            ),
            GeniusPdfLabeledValue(
              config: config,
              label: 'VAT No.',
              labelAr: 'الرقم الضريبي',
              value: '310987654321003',
            ),
          ],
          style: const GeniusPdfInfoBoxStyle.card(),
        );
        final rect = box.draw(page: page, bounds: bounds);
        return rect.height;
      },
      spacing: 5,
      gap: 15,
    );

    addSpace(15);
  }

  // ──────────────────────────────────────────────────────────
  // Rich Text
  // ──────────────────────────────────────────────────────────

  void _buildRichTextSection() {
    addSectionDivider(
      title: isRTL ? 'نص منسق' : 'Rich Text',
      spacing: 10,
    );

    final richText = GeniusPdfRichTextBuilder(config: config)
        .bold(isRTL ? 'ملاحظة: ' : 'Note: ')
        .text(isRTL
            ? 'يمكنك الآن إضافة نصوص منسقة مباشرة من خلال البناء باستخدام '
            : 'You can now add rich text directly through the builder using ')
        .bold('addRichText()')
        .text(isRTL
            ? '. يدعم الخط العريض والألوان والروابط والمزيد.'
            : '. It supports bold, colors, links, and more.')
        .build();

    addRichText(richText, spacing: 5);
    addSpace(10);

    // Another rich text block.
    final statusText = GeniusPdfRichTextBuilder(config: config)
        .text(isRTL ? 'الحالة: ' : 'Status: ')
        .bold(isRTL ? 'مكتمل' : 'Complete')
        .text(isRTL ? ' — آخر تحديث: ' : ' — Last updated: ')
        .text(DateTime.now().toString().substring(0, 10))
        .build();

    addRichText(statusText, spacing: 5);
    addSpace(15);
  }

  // ──────────────────────────────────────────────────────────
  // Info Box
  // ──────────────────────────────────────────────────────────

  void _buildInfoBoxSection() {
    addSectionDivider(
      title: isRTL ? 'صندوق معلومات' : 'Info Box',
      spacing: 10,
    );

    final infoBox = GeniusPdfInfoBox(
      config: config,
      title: 'Payment Details',
      titleAr: 'تفاصيل الدفع',
      items: [
        GeniusPdfLabeledValue(
          config: config,
          label: 'Payment Method',
          labelAr: 'طريقة الدفع',
          value: 'Bank Transfer',
        ),
        GeniusPdfLabeledValue(
          config: config,
          label: 'Bank Name',
          labelAr: 'اسم البنك',
          value: 'Al Rajhi Bank',
        ),
        GeniusPdfLabeledValue(
          config: config,
          label: 'Account No.',
          labelAr: 'رقم الحساب',
          value: 'SA00 1234 5678 9012 3456',
        ),
        GeniusPdfLabeledValue(
          config: config,
          label: 'IBAN',
          labelAr: 'آيبان',
          value: 'SA0012345678901234567890',
        ),
      ],
      style: const GeniusPdfInfoBoxStyle.highlighted(),
      columns: 2,
    );

    addInfoBox(infoBox, spacing: 5);
    addSpace(15);
  }

  // ──────────────────────────────────────────────────────────
  // Footer
  // ──────────────────────────────────────────────────────────

  void _buildFooter() {
    addFooter(
      userName: userName,
      showPageNumber: true,
      printTime: DateTime.now().toString().substring(0, 19),
    );
  }
}''',
    'custom-reports': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.advancedLayout.name,
    config: config,
  ),
  fileName: 'showcase_custom_reports',
  runInBackground: false,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.advancedLayout.name,
    config: config,
  ),
  fileName: 'showcase_custom_reports',
  runInBackground: false,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class AdvancedLayoutDemoBuilder extends GeniusPdfDocumentBuilder {
  /// Creates a new [AdvancedLayoutDemoBuilder].
  AdvancedLayoutDemoBuilder({
    required GeniusPdfConfig config,
    this.userName = 'Demo User',
  }) : super(config);

  /// User name for the footer.
  final String userName;

  @override
  void build() {
    _buildReportHeaderSection();
    _buildTwoColumnSection();
    _buildRichTextSection();
    _buildInfoBoxSection();
    _buildFooter();
  }

  // ──────────────────────────────────────────────────────────
  // Report Header
  // ──────────────────────────────────────────────────────────

  void _buildReportHeaderSection() {
    final header = GeniusPdfReportHeader(
      config: config,
      title: 'Advanced Layout Demo',
      titleAr: 'عرض التخطيط المتقدم',
      subtitle: 'v2.8.0 Features',
      subtitleAr: 'مميزات الإصدار 2.8.0',
      printDate: DateTime.now(),
      showPrintDate: true,
      layout: GeniusPdfReportHeaderLayout.centered,
    );

    addReportHeader(header, spacing: 0, height: 80);
    addSpace(10);
  }

  // ──────────────────────────────────────────────────────────
  // Two-Column Layout
  // ──────────────────────────────────────────────────────────

  void _buildTwoColumnSection() {
    addSectionDivider(
      title: isRTL ? 'تخطيط عمودين' : 'Two-Column Layout',
      spacing: 10,
    );

    addTwoColumns(
      leftContent: (page, bounds) {
        final box = GeniusPdfInfoBox(
          config: config,
          title: 'From',
          titleAr: 'من',
          items: [
            GeniusPdfLabeledValue(
              config: config,
              label: 'Company',
              labelAr: 'الشركة',
              value: 'Genius Systems LLC',
            ),
            GeniusPdfLabeledValue(
              config: config,
              label: 'Address',
              labelAr: 'العنوان',
              value: 'Riyadh, Saudi Arabia',
            ),
            GeniusPdfLabeledValue(
              config: config,
              label: 'VAT No.',
              labelAr: 'الرقم الضريبي',
              value: '310123456789003',
            ),
          ],
          style: const GeniusPdfInfoBoxStyle.card(),
        );
        final rect = box.draw(page: page, bounds: bounds);
        return rect.height;
      },
      rightContent: (page, bounds) {
        final box = GeniusPdfInfoBox(
          config: config,
          title: 'To',
          titleAr: 'إلى',
          items: [
            GeniusPdfLabeledValue(
              config: config,
              label: 'Customer',
              labelAr: 'العميل',
              value: 'ABC Trading Co.',
            ),
            GeniusPdfLabeledValue(
              config: config,
              label: 'Address',
              labelAr: 'العنوان',
              value: 'Jeddah, Saudi Arabia',
            ),
            GeniusPdfLabeledValue(
              config: config,
              label: 'VAT No.',
              labelAr: 'الرقم الضريبي',
              value: '310987654321003',
            ),
          ],
          style: const GeniusPdfInfoBoxStyle.card(),
        );
        final rect = box.draw(page: page, bounds: bounds);
        return rect.height;
      },
      spacing: 5,
      gap: 15,
    );

    addSpace(15);
  }

  // ──────────────────────────────────────────────────────────
  // Rich Text
  // ──────────────────────────────────────────────────────────

  void _buildRichTextSection() {
    addSectionDivider(
      title: isRTL ? 'نص منسق' : 'Rich Text',
      spacing: 10,
    );

    final richText = GeniusPdfRichTextBuilder(config: config)
        .bold(isRTL ? 'ملاحظة: ' : 'Note: ')
        .text(isRTL
            ? 'يمكنك الآن إضافة نصوص منسقة مباشرة من خلال البناء باستخدام '
            : 'You can now add rich text directly through the builder using ')
        .bold('addRichText()')
        .text(isRTL
            ? '. يدعم الخط العريض والألوان والروابط والمزيد.'
            : '. It supports bold, colors, links, and more.')
        .build();

    addRichText(richText, spacing: 5);
    addSpace(10);

    // Another rich text block.
    final statusText = GeniusPdfRichTextBuilder(config: config)
        .text(isRTL ? 'الحالة: ' : 'Status: ')
        .bold(isRTL ? 'مكتمل' : 'Complete')
        .text(isRTL ? ' — آخر تحديث: ' : ' — Last updated: ')
        .text(DateTime.now().toString().substring(0, 10))
        .build();

    addRichText(statusText, spacing: 5);
    addSpace(15);
  }

  // ──────────────────────────────────────────────────────────
  // Info Box
  // ──────────────────────────────────────────────────────────

  void _buildInfoBoxSection() {
    addSectionDivider(
      title: isRTL ? 'صندوق معلومات' : 'Info Box',
      spacing: 10,
    );

    final infoBox = GeniusPdfInfoBox(
      config: config,
      title: 'Payment Details',
      titleAr: 'تفاصيل الدفع',
      items: [
        GeniusPdfLabeledValue(
          config: config,
          label: 'Payment Method',
          labelAr: 'طريقة الدفع',
          value: 'Bank Transfer',
        ),
        GeniusPdfLabeledValue(
          config: config,
          label: 'Bank Name',
          labelAr: 'اسم البنك',
          value: 'Al Rajhi Bank',
        ),
        GeniusPdfLabeledValue(
          config: config,
          label: 'Account No.',
          labelAr: 'رقم الحساب',
          value: 'SA00 1234 5678 9012 3456',
        ),
        GeniusPdfLabeledValue(
          config: config,
          label: 'IBAN',
          labelAr: 'آيبان',
          value: 'SA0012345678901234567890',
        ),
      ],
      style: const GeniusPdfInfoBoxStyle.highlighted(),
      columns: 2,
    );

    addInfoBox(infoBox, spacing: 5);
    addSpace(15);
  }

  // ──────────────────────────────────────────────────────────
  // Footer
  // ──────────────────────────────────────────────────────────

  void _buildFooter() {
    addFooter(
      userName: userName,
      showPageNumber: true,
      printTime: DateTime.now().toString().substring(0, 19),
    );
  }
}''',
    'preview': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.basic.name,
    config: config,
  ),
  fileName: 'showcase_preview',
  runInBackground: false,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.basic.name,
    config: config,
  ),
  fileName: 'showcase_preview',
  runInBackground: false,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class _BasicDocument extends GeniusPdfDocumentBuilder {
  _BasicDocument(super.config);
  @override
  void build() {
    addHeader(title: 'Genius PDF developer showcase');
    addLine('A compact working document generated by the example application.');
    addSpace(12);
    addLine('Use the action toolbar to preview, save, open, share, or print it.');
    addFooter(userName: 'Example app', showPageNumber: true);
  }
}''',
    'delivery': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.basic.name,
    config: config,
  ),
  fileName: 'showcase_delivery',
  runInBackground: false,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.basic.name,
    config: config,
  ),
  fileName: 'showcase_delivery',
  runInBackground: false,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class _BasicDocument extends GeniusPdfDocumentBuilder {
  _BasicDocument(super.config);
  @override
  void build() {
    addHeader(title: 'Genius PDF developer showcase');
    addLine('A compact working document generated by the example application.');
    addSpace(12);
    addLine('Use the action toolbar to preview, save, open, share, or print it.');
    addFooter(userName: 'Example app', showPageNumber: true);
  }
}''',
    'background-generation': r'''final config = geniusPdfConfig.copyWith(
  textDirection: settings.textDirection,
);

PdfWorkbench(
  builderFactory: () => createShowcaseBuilder(
    ShowcaseDemoKind.basic.name,
    config: config,
  ),
  fileName: 'showcase_background_generation',
  runInBackground: true,
);

// This is the Generate action executed by PdfWorkbench.
final result = await geniusPdfClient.generate(
  builder: createShowcaseBuilder(
    ShowcaseDemoKind.basic.name,
    config: config,
  ),
  fileName: 'showcase_background_generation',
  runInBackground: true,
);

// -----------------------------------------------------------------
// Actual document builder used by this screen
// -----------------------------------------------------------------
class _BasicDocument extends GeniusPdfDocumentBuilder {
  _BasicDocument(super.config);
  @override
  void build() {
    addHeader(title: 'Genius PDF developer showcase');
    addLine('A compact working document generated by the example application.');
    addSpace(12);
    addLine('Use the action toolbar to preview, save, open, share, or print it.');
    addFooter(userName: 'Example app', showPageNumber: true);
  }
}''',
  };

  static const Map<String, String> _reference = <String, String>{
    'configuration': r'''GeniusPdfConfig showcaseConfig({TextDirection direction = TextDirection.ltr}''',
    'report-composer': r'''List<int> buildComposerDemoReport({
  required GeniusPdfConfig config,
  String userName = 'Demo User',
}''',
  };

  /// Exact Dart source for the builder/generation path used by a workbench
  /// destination in the current example application.
  static String workbench(ShowcaseDestination destination) =>
      _workbench[destination.id] ?? '';

  /// Real repository source for a reference page. Empty means that the page
  /// is documentation/reference only and does not execute a generation path.
  static String reference(ShowcaseDestination destination) =>
      _reference[destination.id] ?? '';
}
