import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:logger/logger.dart';
import 'package:open_file/open_file.dart';
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';

import '../builders/pdf_document_builder.dart';
import '../models/pdf_result.dart';

/// Service for handling PDF generation, saving, and sharing operations.
///
/// This service provides methods to generate PDFs from builders,
/// save them to disk, open them, and share them. All operations
/// support both foreground and background execution.
///
/// ## Example
/// ```dart
/// final service = PdfService();
///
/// // Generate and open a PDF
/// final result = await service.generateAndOpen(
///   builder: invoiceBuilder,
///   fileName: 'invoice_123',
///   onStart: () => showLoading(),
///   onComplete: (result) => hideLoading(),
/// );
///
/// // Handle result
/// result.when(
///   onSuccess: (success) => print('Saved to: ${success.filePath}'),
///   onFailure: (failure) => print('Error: ${failure.message}'),
/// );
/// ```
class GeniusPdfService {
  /// Creates a new [GeniusPdfService] instance.
  const GeniusPdfService();

  /// Generates a PDF from the given builder and returns the bytes.
  ///
  /// ## Parameters
  /// - [builder]: The document builder to generate from (required).
  /// - [runInBackground]: Run generation in a separate isolate.
  ///
  /// ## Returns
  /// A [GeniusPdfResult] containing the generated bytes or an error.
  Future<GeniusPdfResult> generate({
    required GeniusPdfDocumentBuilder builder,
    required String fileName,
    bool runInBackground = true,
  }) async {
    try {
      List<int> bytes;

      if (runInBackground) {
        bytes = await compute(_generatePdfBytes, builder);
      } else {
        bytes = builder.generate();
      }

      return GeniusPdfSuccess(
        bytes: Uint8List.fromList(bytes),
        fileName: fileName,
      );
    } catch (e, st) {
      Logger().e('Error generating PDF: $e', stackTrace: st);
      return GeniusPdfFailure.fromException(e, st);
    } finally {
      builder.dispose();
    }
  }

  /// Generates a PDF and saves it to the documents directory.
  ///
  /// ## Parameters
  /// - [builder]: The document builder to generate from (required).
  /// - [fileName]: Name of the file (without extension).
  /// - [runInBackground]: Run generation in a separate isolate.
  ///
  /// ## Returns
  /// A [GeniusPdfResult] with the file path on success.
  Future<GeniusPdfResult> generateAndSave({
    required GeniusPdfDocumentBuilder builder,
    required String fileName,
    bool runInBackground = true,
  }) async {
    try {
      List<int> bytes;

      if (runInBackground) {
        bytes = await compute(_generatePdfBytes, builder);
      } else {
        bytes = builder.generate();
      }

      final dir = await getApplicationDocumentsDirectory();
      final filePath = '${dir.path}/$fileName.pdf';
      final file = File(filePath);
      await file.writeAsBytes(bytes);

      return GeniusPdfSuccess(
        bytes: Uint8List.fromList(bytes),
        fileName: fileName,
        filePath: filePath,
      );
    } catch (e, st) {
      Logger().e('Error generating PDF: $e', stackTrace: st);
      return GeniusPdfFailure.fromException(e, st);
    } finally {
      builder.dispose();
    }
  }

  /// Generates a PDF, saves it, and opens it with the default viewer.
  ///
  /// ## Parameters
  /// - [builder]: The document builder to generate from (required).
  /// - [fileName]: Name of the file (without extension).
  /// - [onStart]: Called when generation starts.
  /// - [onComplete]: Called when generation completes successfully.
  /// - [onError]: Called if an error occurs.
  /// - [runInBackground]: Run generation in a separate isolate.
  ///
  /// ## Returns
  /// A [GeniusPdfResult] with the file path on success.
  Future<GeniusPdfResult> generateAndOpen({
    required GeniusPdfDocumentBuilder builder,
    required String fileName,
    PdfGenerationCallback? onStart,
    PdfSuccessCallback? onComplete,
    PdfErrorCallback? onError,
    bool runInBackground = true,
  }) async {
    onStart?.call();

    try {
      final result = await generateAndSave(
        builder: builder,
        fileName: fileName,
        runInBackground: runInBackground,
      );

      return result.when(
        onSuccess: (success) async {
          await OpenFile.open(success.filePath!);
          onComplete?.call(success);
          return success;
        },
        onFailure: (failure) {
          onError?.call(failure);
          return failure;
        },
      );
    } catch (e, st) {
      Logger().e('Error generating PDF: $e', stackTrace: st);
      final failure = GeniusPdfFailure.fromException(e, st);
      onError?.call(failure);
      return failure;
    }
  }

  /// Generates a PDF and shares it using the system share dialog.
  ///
  /// ## Parameters
  /// - [builder]: The document builder to generate from (required).
  /// - [fileName]: Name of the file (without extension).
  /// - [onStart]: Called when generation starts.
  /// - [onComplete]: Called when sharing is initiated.
  /// - [onError]: Called if an error occurs.
  /// - [runInBackground]: Run generation in a separate isolate.
  ///
  /// ## Returns
  /// A [GeniusPdfResult] on success.
  Future<GeniusPdfResult> generateAndShare({
    required GeniusPdfDocumentBuilder builder,
    required String fileName,
    PdfGenerationCallback? onStart,
    PdfSuccessCallback? onComplete,
    PdfErrorCallback? onError,
    bool runInBackground = true,
  }) async {
    onStart?.call();

    try {
      final result = await generate(
        builder: builder,
        fileName: fileName,
        runInBackground: runInBackground,
      );

      return result.when(
        onSuccess: (success) async {
          await Printing.sharePdf(
            bytes: success.bytes,
            filename: '$fileName.pdf',
          );
          onComplete?.call(success);
          return success;
        },
        onFailure: (failure) {
          onError?.call(failure);
          return failure;
        },
      );
    } catch (e, st) {
      Logger().e('Error generating PDF: $e', stackTrace: st);
      final failure = GeniusPdfFailure.fromException(e, st);
      onError?.call(failure);
      return failure;
    }
  }

  /// Prints a PDF using the system print dialog.
  ///
  /// ## Parameters
  /// - [bytes]: The PDF bytes to print (required).
  /// - [documentName]: Name for the print job.
  Future<bool> print({
    required Uint8List bytes,
    required String documentName,
  }) async {
    return Printing.layoutPdf(
      onLayout: (_) => bytes,
      name: documentName,
    );
  }

  /// Saves PDF bytes to a specific path.
  ///
  /// ## Parameters
  /// - [bytes]: The PDF bytes to save (required).
  /// - [path]: Full path including filename (required).
  Future<File> saveToPath({
    required Uint8List bytes,
    required String path,
  }) async {
    final file = File(path);
    await file.writeAsBytes(bytes);
    return file;
  }
}

/// Helper function for compute isolate.
List<int> _generatePdfBytes(GeniusPdfDocumentBuilder builder) {
  return builder.generate();
}
