// GENERATED BY split_v2_architecture_examples_with_pdf_preview.py
// Focused V2 Architecture host: exactly one concrete demo per screen.

// ignore_for_file: depend_on_referenced_packages

import 'dart:async';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/features/architecture/models/documents/invoice_document.dart';
import 'package:genius_pdf_example/features/architecture/models/documents/report_document.dart';
import 'package:genius_pdf_example/features/architecture/models/documents/simple_document.dart';
import 'package:genius_pdf_example/shared/presentation/widgets/feature_example_page.dart';

import 'package:genius_pdf_example/localizations/pdf_generator_localization.dart';
/// Every concrete demo formerly hosted by the V2 Architecture aggregate page.
enum V2ArchitectureExample {
  simpleDocument,
  invoice,
  multiPageReport,
  registerPlugin,
  listPlugins,
  initializePlugins,
  resetPluginManager,
  registerServices,
  resolveDependencies,
  lazySingleton,
  resetContainer,
  documentCreatedEvent,
  renderProgressEvents,
  clearEventLog,
}

/// Renders exactly one V2 Architecture example.
///
/// PDF-producing Fluent API demos keep their generated bytes in memory and
/// display them in [GeniusPdfPreviewWidget]. Opening the PDF is a separate,
/// explicit action.
class V2ArchitectureSingleExampleHost extends StatefulWidget {
  const V2ArchitectureSingleExampleHost({
    super.key,
    required this.example,
    required this.usageCode,
  });

  final V2ArchitectureExample example;
  final String usageCode;

  @override
  State<V2ArchitectureSingleExampleHost> createState() =>
      _V2ArchitectureSingleExampleHostState();
}

class _V2ArchitectureSingleExampleHostState
    extends State<V2ArchitectureSingleExampleHost> {
  bool _isLoading = false;
  bool _isOpening = false;
  String _status = '';
  Uint8List? _pdfBytes;
  String? _pdfFileName;
  final List<String> _eventLog = <String>[];
  StreamSubscription? _eventSubscription;

  @override
  void initState() {
    super.initState();
    _setupEventListener();
  }

  void _setupEventListener() {
    _eventSubscription = GeniusPdfEventBus.instance.events.listen((event) {
      if (!mounted) return;
      setState(() {
        _eventLog.insert(
          0,
          '${DateTime.now().toString().substring(11, 19)} - ${event.name}',
        );
        if (_eventLog.length > 20) _eventLog.removeLast();
      });
    });
  }

  @override
  void didUpdateWidget(covariant V2ArchitectureSingleExampleHost oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.example != widget.example) {
      _pdfBytes = null;
      _pdfFileName = null;
      _status = '';
    }
  }

  @override
  void dispose() {
    _eventSubscription?.cancel();
    super.dispose();
  }

  bool get _isPdfExample => switch (widget.example) {
        V2ArchitectureExample.simpleDocument ||
        V2ArchitectureExample.invoice ||
        V2ArchitectureExample.multiPageReport => true,
        _ => false,
      };

  bool get _isEventExample => switch (widget.example) {
        V2ArchitectureExample.documentCreatedEvent ||
        V2ArchitectureExample.renderProgressEvents ||
        V2ArchitectureExample.clearEventLog => true,
        _ => false,
      };

  String get _title => switch (widget.example) {
        V2ArchitectureExample.simpleDocument => 'Simple Document',
        V2ArchitectureExample.invoice => 'Invoice',
        V2ArchitectureExample.multiPageReport => 'Multi-page Report',
        V2ArchitectureExample.registerPlugin => 'Register Demo Plugin',
        V2ArchitectureExample.listPlugins => 'List Registered Plugins',
        V2ArchitectureExample.initializePlugins => 'Initialize All Plugins',
        V2ArchitectureExample.resetPluginManager => 'Reset Plugin Manager',
        V2ArchitectureExample.registerServices => 'Register Services',
        V2ArchitectureExample.resolveDependencies => 'Resolve Dependencies',
        V2ArchitectureExample.lazySingleton => 'Lazy Singleton',
        V2ArchitectureExample.resetContainer => 'Reset Container',
        V2ArchitectureExample.documentCreatedEvent => 'Document Created Event',
        V2ArchitectureExample.renderProgressEvents => 'Render Progress Events',
        V2ArchitectureExample.clearEventLog => 'Clear Event Log',
      };

  String get _description => switch (widget.example) {
        V2ArchitectureExample.simpleDocument =>
          'Generate a simple Fluent API document and inspect the PDF inline.',
        V2ArchitectureExample.invoice =>
          'Generate the Fluent API invoice and inspect the exact PDF output.',
        V2ArchitectureExample.multiPageReport =>
          'Generate the multi-page Fluent API report and inspect page output.',
        V2ArchitectureExample.registerPlugin =>
          'Register one demo plugin through GeniusPluginManager.',
        V2ArchitectureExample.listPlugins =>
          'Inspect the plugins currently registered in GeniusPluginManager.',
        V2ArchitectureExample.initializePlugins =>
          'Initialize all registered plugins.',
        V2ArchitectureExample.resetPluginManager =>
          'Reset the plugin manager and clear registered plugins.',
        V2ArchitectureExample.registerServices =>
          'Register singleton, factory, and lazy-singleton services.',
        V2ArchitectureExample.resolveDependencies =>
          'Resolve the services currently registered in the DI container.',
        V2ArchitectureExample.lazySingleton =>
          'Demonstrate that a lazy singleton is instantiated once.',
        V2ArchitectureExample.resetContainer =>
          'Reset the dependency-injection container.',
        V2ArchitectureExample.documentCreatedEvent =>
          'Emit one GeniusDocumentCreatedEvent and inspect the event log.',
        V2ArchitectureExample.renderProgressEvents =>
          'Emit render-progress and completion events over time.',
        V2ArchitectureExample.clearEventLog =>
          'Clear all events captured by this focused example host.',
      };

  IconData get _icon => switch (widget.example) {
        V2ArchitectureExample.simpleDocument => Icons.description_outlined,
        V2ArchitectureExample.invoice => Icons.receipt_long_outlined,
        V2ArchitectureExample.multiPageReport => Icons.article_outlined,
        V2ArchitectureExample.registerPlugin => Icons.add_circle_outline,
        V2ArchitectureExample.listPlugins => Icons.list_alt_outlined,
        V2ArchitectureExample.initializePlugins => Icons.play_circle_outline,
        V2ArchitectureExample.resetPluginManager => Icons.restart_alt_outlined,
        V2ArchitectureExample.registerServices => Icons.add_box_outlined,
        V2ArchitectureExample.resolveDependencies => Icons.manage_search_outlined,
        V2ArchitectureExample.lazySingleton => Icons.timer_outlined,
        V2ArchitectureExample.resetContainer => Icons.delete_sweep_outlined,
        V2ArchitectureExample.documentCreatedEvent => Icons.add_circle_outline,
        V2ArchitectureExample.renderProgressEvents => Icons.trending_up_outlined,
        V2ArchitectureExample.clearEventLog => Icons.clear_all_outlined,
      };

  String get _actionLabel => switch (widget.example) {
        V2ArchitectureExample.simpleDocument => 'Build Simple Document',
        V2ArchitectureExample.invoice => 'Build Invoice',
        V2ArchitectureExample.multiPageReport => 'Build Multi-page Report',
        V2ArchitectureExample.registerPlugin => 'Register Demo Plugin',
        V2ArchitectureExample.listPlugins => 'List Registered Plugins',
        V2ArchitectureExample.initializePlugins => 'Initialize All Plugins',
        V2ArchitectureExample.resetPluginManager => 'Reset Plugin Manager',
        V2ArchitectureExample.registerServices => 'Register Services',
        V2ArchitectureExample.resolveDependencies => 'Resolve Dependencies',
        V2ArchitectureExample.lazySingleton => 'Demo Lazy Singleton',
        V2ArchitectureExample.resetContainer => 'Reset Container',
        V2ArchitectureExample.documentCreatedEvent => 'Emit Document Created',
        V2ArchitectureExample.renderProgressEvents => 'Emit Render Progress',
        V2ArchitectureExample.clearEventLog => 'Clear Event Log',
      };

  @override
  Widget build(BuildContext context) {
    return FeatureExamplePage(
      title: _title,
      description: _description,
      icon: _icon,
      code: widget.usageCode,
      contentTitle: _isPdfExample
          ? 'PDF preview'
          : _isEventExample
              ? 'Event log'
              : 'Action result',
      contentDescription: _isPdfExample
          ? 'The preview uses the exact bytes produced by the generator shown in Dart usage code.'
          : 'This screen executes only this architecture example.',
      actions: <Widget>[
        FilledButton.icon(
          onPressed: _isLoading || _isOpening ? null : _runCurrentExample,
          icon: _isLoading
              ? const SizedBox.square(
                  dimension: 18,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
              : const Icon(Icons.play_arrow_rounded),
          label: Text(_isLoading ? 'Running…' : _actionLabel),
        ),
        if (_isPdfExample)
          OutlinedButton.icon(
            onPressed: _pdfBytes == null || _isLoading || _isOpening
                ? null
                : _openPreviewPdf,
            icon: const Icon(Icons.open_in_new_rounded),
            label: Text(_isOpening ? 'Opening…' : 'Open PDF'),
          ),
      ],
      content: _buildContent(),
      statusMessage: _status.isEmpty ? 'Ready for action.' : _status,
      statusTone: _status.startsWith('Error:')
          ? FeatureExampleTone.danger
          : _isLoading
              ? FeatureExampleTone.info
              : _pdfBytes != null
                  ? FeatureExampleTone.success
                  : FeatureExampleTone.neutral,
      codeHeight: 760,
    );
  }

  Widget _buildContent() {
    if (_isPdfExample) return _buildPdfPreview();
    if (_isEventExample) return _buildEventLogCard();

    final colors = Theme.of(context).colorScheme;
    return Container(
      constraints: const BoxConstraints(minHeight: 260),
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        color: colors.surfaceContainerLow,
        border: Border.all(color: colors.outlineVariant),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Center(
        child: Text(
          _status.isEmpty
              ? 'Press $_actionLabel to run this example.'
              : _status,
          textAlign: TextAlign.center,
        ),
      ),
    );
  }

  Widget _buildPdfPreview() {
    final bytes = _pdfBytes;
    if (_isLoading) {
      return  SizedBox(
        height: 700,
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              CircularProgressIndicator(),
              SizedBox(height: 12),
              Text(pdfLocalization.generatingPdfPreview),
            ],
          ),
        ),
      );
    }

    if (bytes == null) {
      return  SizedBox(
        height: 700,
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Icon(Icons.picture_as_pdf_outlined, size: 48),
              SizedBox(height: 12),
              Text(pdfLocalization.noPdfGeneratedYet),
              SizedBox(height: 6),
              Text(pdfLocalization.pressActionButtonGeneratePreviewDesc),
            ],
          ),
        ),
      );
    }

    return SizedBox(
      height: 760,
      child: GeniusPdfPreviewWidget(
        pdfData: bytes,
        canChangeOrientation: false,
        canChangePageFormat: false,
        allowFullscreen: true,
        fullscreenTitle: _title,
        maxPageWidth: 900,
      ),
    );
  }

  Widget _buildEventLogCard() {
    final colors = Theme.of(context).colorScheme;
    return Container(
      constraints: const BoxConstraints(minHeight: 300),
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: colors.surfaceContainerLow,
        border: Border.all(color: colors.outlineVariant),
        borderRadius: BorderRadius.circular(12),
      ),
      child: _eventLog.isEmpty
          ?  Center(child: Text(pdfLocalization.noEventsEmittedYet))
          : ListView.separated(
              shrinkWrap: true,
              physics: const NeverScrollableScrollPhysics(),
              itemCount: _eventLog.length > 12 ? 12 : _eventLog.length,
              separatorBuilder: (_, _) => const Divider(height: 12),
              itemBuilder: (context, index) => Text(_eventLog[index]),
            ),
    );
  }

  Future<void> _runCurrentExample() async {
    _pdfBytes = null;
    _pdfFileName = null;

    switch (widget.example) {
      case V2ArchitectureExample.simpleDocument:
        await _buildSimpleDocument();
        break;
      case V2ArchitectureExample.invoice:
        await _buildInvoice();
        break;
      case V2ArchitectureExample.multiPageReport:
        await _buildMultiPageReport();
        break;
      case V2ArchitectureExample.registerPlugin:
        await _registerDemoPlugin();
        break;
      case V2ArchitectureExample.listPlugins:
        await _listPlugins();
        break;
      case V2ArchitectureExample.initializePlugins:
        await _initializePlugins();
        break;
      case V2ArchitectureExample.resetPluginManager:
        await _resetPluginManager();
        break;
      case V2ArchitectureExample.registerServices:
        await _registerServices();
        break;
      case V2ArchitectureExample.resolveDependencies:
        await _resolveDependencies();
        break;
      case V2ArchitectureExample.lazySingleton:
        await _demoLazySingleton();
        break;
      case V2ArchitectureExample.resetContainer:
        await _resetContainer();
        break;
      case V2ArchitectureExample.documentCreatedEvent:
        _emitDocumentCreated();
        break;
      case V2ArchitectureExample.renderProgressEvents:
        _emitRenderProgress();
        break;
      case V2ArchitectureExample.clearEventLog:
        _clearEventLog();
        break;
    }
  }

  Future<void> _openPreviewPdf() async {
    final bytes = _pdfBytes;
    final fileName = _pdfFileName;
    if (bytes == null || fileName == null || _isOpening) return;

    setState(() => _isOpening = true);
    try {
      await demoDocuments.saveAndOpen(bytes: bytes, fileName: fileName);
    } finally {
      if (mounted) setState(() => _isOpening = false);
    }
  }

  // ============ Fluent API Demos ============

  Future<void> _buildSimpleDocument() async {
    setState(() {
      _isLoading = true;
      _status = 'Building document with Fluent API...';
    });

    try {
      final bytes = await buildSimpleDocumentBytes();
      if (!mounted) return;
      setState(() {
        _pdfBytes = bytes;
        _pdfFileName = 'simple-doc.pdf';
        _status = 'Document built successfully. Preview is ready.';
      });
    } catch (e) {
      if (mounted) setState(() => _status = 'Error: $e');
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _buildInvoice() async {
    setState(() {
      _isLoading = true;
      _status = 'Building invoice...';
    });

    try {
      final bytes = await buildInvoiceDocumentBytes();
      if (!mounted) return;
      setState(() {
        _pdfBytes = bytes;
        _pdfFileName = 'invoice-001.pdf';
        _status = 'Invoice built successfully. Preview is ready.';
      });
    } catch (e) {
      if (mounted) setState(() => _status = 'Error: $e');
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _buildMultiPageReport() async {
    setState(() {
      _isLoading = true;
      _status = 'Building multi-page report...';
    });

    try {
      final bytes = await buildMultiPageReportBytes();
      if (!mounted) return;
      setState(() {
        _pdfBytes = bytes;
        _pdfFileName = 'monthly-report.pdf';
        _status = 'Multi-page report built successfully. Preview is ready.';
      });
    } catch (e) {
      if (mounted) setState(() => _status = 'Error: $e');
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  // ============ Plugin Demos ============

  Future<void> _registerDemoPlugin() async {
    setState(() {
      _isLoading = true;
      _status = 'Registering demo plugin...';
    });

    try {
      final manager = GeniusPluginManager.instance;
      final result = await manager.register(_DemoPlugin());

      setState(() {
        _status = result
            ? 'Demo plugin registered successfully!\n'
                'Plugin ID: demo-plugin\n'
                'Version: 1.0.0'
            : 'Plugin already registered or registration failed.';
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _listPlugins() async {
    setState(() {
      _isLoading = true;
      _status = 'Listing plugins...';
    });

    try {
      final manager = GeniusPluginManager.instance;
      final plugins = manager.plugins;

      if (plugins.isEmpty) {
        setState(() {
          _status = 'No plugins registered.\n'
              'Use "Register Demo Plugin" to add a plugin.';
        });
      } else {
        final buffer = StringBuffer('Registered Plugins:\n\n');
        for (final plugin in plugins) {
          buffer.writeln('• ${plugin.name} (${plugin.id})');
          buffer.writeln('  Version: ${plugin.version}');
          buffer.writeln('  Priority: ${plugin.priority}');
          buffer.writeln('  Initialized: ${manager.isInitialized(plugin.id)}');
          buffer.writeln('');
        }
        setState(() {
          _status = buffer.toString();
        });
      }
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _initializePlugins() async {
    setState(() {
      _isLoading = true;
      _status = 'Initializing plugins...';
    });

    try {
      final manager = GeniusPluginManager.instance;
      await manager.initializeAll();

      setState(() {
        _status = 'All plugins initialized!\n'
            'Total plugins: ${manager.count}';
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _resetPluginManager() async {
    setState(() {
      _isLoading = true;
      _status = 'Resetting plugin manager...';
    });

    try {
      GeniusPluginManager.resetInstance();

      setState(() {
        _status = 'Plugin manager reset successfully!\n'
            'All plugins have been unregistered.';
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  // ============ DI Demos ============

  Future<void> _registerServices() async {
    setState(() {
      _isLoading = true;
      _status = 'Registering services...';
    });

    try {
      final container = GeniusPdfContainer.instance;

      container.registerSingleton<String>('Global Config Value',
          name: 'config');

      container.registerFactory<int>(
          () => DateTime.now().millisecondsSinceEpoch,
          name: 'timestamp');

      container.registerLazySingleton<List<String>>(
        () => ['Item 1', 'Item 2', 'Item 3'],
        name: 'items',
      );

      setState(() {
        _status = 'Services registered successfully!\n'
            '• config (singleton): String\n'
            '• timestamp (factory): int\n'
            '• items (lazy singleton): List<String>';
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _resolveDependencies() async {
    setState(() {
      _isLoading = true;
      _status = 'Resolving dependencies...';
    });

    try {
      final container = GeniusPdfContainer.instance;
      final buffer = StringBuffer('Resolved Dependencies:\n\n');

      if (container.isRegistered<String>(name: 'config')) {
        final config = container.get<String>(name: 'config');
        buffer.writeln('config: $config');
      } else {
        buffer.writeln('config: Not registered');
      }

      if (container.isRegistered<int>(name: 'timestamp')) {
        final ts1 = container.get<int>(name: 'timestamp');
        await Future.delayed(const Duration(milliseconds: 10));
        final ts2 = container.get<int>(name: 'timestamp');
        buffer.writeln('timestamp (1st call): $ts1');
        buffer.writeln('timestamp (2nd call): $ts2');
        buffer.writeln('(Different values = factory creates new instances)');
      } else {
        buffer.writeln('timestamp: Not registered');
      }

      if (container.isRegistered<List<String>>(name: 'items')) {
        final items = container.get<List<String>>(name: 'items');
        buffer.writeln('items: $items');
      } else {
        buffer.writeln('items: Not registered');
      }

      setState(() {
        _status = buffer.toString();
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _demoLazySingleton() async {
    setState(() {
      _isLoading = true;
      _status = 'Demonstrating lazy singleton...';
    });

    try {
      final container = GeniusPdfContainer.instance;

      var creationCount = 0;
      container.registerLazySingleton<Map<String, int>>(() {
        creationCount++;
        return {
          'creationNumber': creationCount,
          'time': DateTime.now().millisecond
        };
      }, name: 'lazyDemo');

      final buffer = StringBuffer('Lazy Singleton Demo:\n\n');

      buffer.writeln('Before first access: creationCount = $creationCount');

      final first = container.get<Map<String, int>>(name: 'lazyDemo');
      buffer.writeln('First access: $first');
      buffer.writeln('After first access: creationCount = $creationCount');

      final second = container.get<Map<String, int>>(name: 'lazyDemo');
      buffer.writeln('Second access: $second');
      buffer.writeln('After second access: creationCount = $creationCount');

      buffer.writeln('\n(Same value = lazy singleton created only once)');

      setState(() {
        _status = buffer.toString();
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _resetContainer() async {
    setState(() {
      _isLoading = true;
      _status = 'Resetting container...';
    });

    try {
      GeniusPdfContainer.reset();

      setState(() {
        _status = 'DI Container reset successfully!\n'
            'All registrations have been cleared.';
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  // ============ Event Demos ============

  void _emitDocumentCreated() {
    final eventBus = GeniusPdfEventBus.instance;

    eventBus.emit(GeniusDocumentCreatedEvent(
      documentId: 'doc-${DateTime.now().millisecondsSinceEpoch}',
      title: pdfLocalization.demoDocument,
    ));

    setState(() {
      _status = 'DocumentCreatedEvent emitted!\n'
          'Check the event log above.';
    });
  }

  void _emitRenderProgress() {
    final eventBus = GeniusPdfEventBus.instance;

    for (var i = 1; i <= 5; i++) {
      Future.delayed(Duration(milliseconds: i * 200), () {
        eventBus.emit(GeniusRenderProgressEvent(
          documentId: 'doc-render',
          currentPage: i,
          totalPages: 5,
        ));
      });
    }

    Future.delayed(const Duration(milliseconds: 1200), () {
      eventBus.emit(GeniusRenderCompletedEvent(
        documentId: 'doc-render',
        duration: const Duration(seconds: 1),
      ));
    });

    setState(() {
      _status = 'Emitting render progress events...\n'
          'Watch the event log for updates.';
    });
  }

  void _clearEventLog() {
    setState(() {
      _eventLog.clear();
      _status = 'Event log cleared.';
    });
  }
}

/// Demo plugin for testing plugin system.
class _DemoPlugin extends GeniusPdfPlugin {
  @override
  String get id => 'demo-plugin';

  @override
  String get name => 'Demo Plugin';

  @override
  String get version => '1.0.0';

  @override
  String get description => 'A demo plugin for testing the plugin system';

  @override
  int get priority => 10;

  @override
  Future<void> initialize() async {
    await Future.delayed(const Duration(milliseconds: 100));
  }

  @override
  void onEnable() {}

  @override
  void onDisable() {}
}
