name: genius_pdf_example
description: Example app demonstrating genius_link_pdf_generator features.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"
dependencies:
  super_navigation_sidebar: ^3.3.0
  super_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  genius_link_pdf_generator:
    path: ../
  cupertino_icons: ^1.0.8
  intl: ">=0.20.0 <0.30.0"
  logger: ^2.6.1
  flutter_syntax_view: ^4.1.7
  open_file: ^3.5.11
  path_provider: ^2.1.5
  pdf: ^3.11.3
  syncfusion_flutter_pdf: ^32.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # The following section is specific to Flutter.
  generate: true # Add this line

  assets:
    - assets/fonts/
    - assets/fonts/din/
    - assets/fonts/hacen/
    - assets/fonts/cairo/
    - assets/fonts/open_sans/
    - assets/images/

  fonts:
    - family: hacen
      fonts:
        - asset: assets/fonts/hacen/hacenTunisia.ttf
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo/cairoRegular.ttf
        - asset: assets/fonts/cairo/tahoma.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 400
    - family: din
      fonts:
        - asset: assets/fonts/din/din.ttf
        - asset: assets/fonts/din/din_bold.ttf
          weight: 700


