// Generated by migrate_text_getting_architecture_sharing_custom_report_configuration_to_global_manager.py

import 'dart:isolate';
import 'dart:typed_data';

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/features/architecture/models/documents/invoice_document.dart';
import 'package:genius_pdf_example/features/architecture/models/documents/report_document.dart';
import 'package:genius_pdf_example/features/architecture/models/documents/simple_document.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _worker(Map<String, Object?> message) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final exampleId = message['exampleId']! as String;

  final Uint8List bytes = switch (exampleId) {
    'simpleDocument' => await buildSimpleDocumentBytes(config: config),
    'invoice' => await buildInvoiceDocumentBytes(config: config),
    'multiPageReport' => await buildMultiPageReportBytes(config: config),
    _ => throw ArgumentError.value(
        exampleId,
        'exampleId',
        'Unsupported V2 Architecture PDF example',
      ),
  };

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates one PDF-producing V2 Architecture demo outside the UI isolate.
Future<Uint8List> generateV2ArchitecturePdfInBackground({
  required String exampleId,
}) async {
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(geniusPdfConfig),
    'exampleId': exampleId,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _worker(message),
    debugName: 'architecture-v2-$exampleId',
  );
  return transferred.materialize().asUint8List();
}
