// Generated by migrate_text_getting_architecture_sharing_custom_report_configuration_to_global_manager.py

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/features/architecture/models/documents/s06_erp_calc_verification_documents.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _worker(Map<String, Object?> message) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final apiName = message['apiName']! as String;

  final Uint8List bytes = switch (apiName) {
    'buildS06AfterTaxDiscountVerificationPdf' => await buildS06AfterTaxDiscountVerificationPdf(config),
    'buildS06BaselineVerificationPdf' => await buildS06BaselineVerificationPdf(config),
    'buildS06BeforeTaxDiscountVerificationPdf' => await buildS06BeforeTaxDiscountVerificationPdf(config),
    'buildS06LongMultiPageVerificationPdf' => await buildS06LongMultiPageVerificationPdf(config),
    'buildS06MultiCurrencyVerificationPdf' => await buildS06MultiCurrencyVerificationPdf(config),
    'buildS06MultiTaxVerificationPdf' => await buildS06MultiTaxVerificationPdf(config),
    'buildS06OptionalNullsVerificationPdf' => await buildS06OptionalNullsVerificationPdf(config),
    'buildS06PaidDueVerificationPdf' => await buildS06PaidDueVerificationPdf(config),
    'buildS06RoundingVerificationPdf' => await buildS06RoundingVerificationPdf(config),
    'buildS06ZeroNegativeVerificationPdf' => await buildS06ZeroNegativeVerificationPdf(config),
    _ => throw ArgumentError.value(
        apiName,
        'apiName',
        'Unsupported architecture verification example',
      ),
  };

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates one architecture verification PDF outside the UI isolate.
Future<Uint8List> generateArchitectureVerificationInBackground({
  required String apiName,
  required bool isRtl,
}) async {
  final config = geniusPdfConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'apiName': apiName,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _worker(message),
    debugName: 'architecture-verification-$apiName',
  );
  return transferred.materialize().asUint8List();
}
