
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/shared/application/services/example_pdf_generation.dart';
import 'package:genius_pdf_example/features/export/models/documents/template_image_export_examples.dart';
import 'package:genius_pdf_example/features/templates/models/documents/export_template_background_generators.dart';
import 'package:genius_pdf_example/features/templates/models/documents/template_example_build.dart';
import 'package:genius_pdf_example/shared/presentation/controllers/demo_document_controller.dart';
import 'package:genius_pdf_example/shared/presentation/widgets/feature_example_page.dart';

import 'package:genius_pdf_example/localizations/pdf_generator_localization.dart';
/// Signature used by focused template-image-export examples.
typedef TemplateImageExporter = Future<TemplateImageExportResult> Function({
  required bool isRtl,
  required GeniusExportFormat format,
  required GeniusImageQuality quality,
  required DemoDocumentController documents,
});

/// Generates PDF source bytes for an image template on a background isolate.
typedef TemplateImageBackgroundPdfGenerator =
    Future<TemplateBackgroundPdfBatch> Function({required bool isRtl});

/// Builds PDF source documents that should be generated by the app-wide
/// [GeniusPdfGenerationManager] before rasterization.
typedef TemplateImagePdfBuildsBuilder = List<TemplateExampleBuild> Function({
  required bool isRtl,
});

/// Builds template-specific settings next to image export controls.
typedef TemplateImageAdditionalSettingsBuilder = Widget Function(
  BuildContext context,
  bool disabled,
);

/// Focused example screen for exporting one PDF template as PNG/JPEG images.
///
/// Nothing is generated during initialization. The export starts only when the
/// user presses **Run export**. All exported pages are previewed from the exact
/// bytes that were persisted by the example generator.
class TemplateImageExportDetailScreen extends StatefulWidget {
  const TemplateImageExportDetailScreen({
    super.key,
    required this.category,
    required this.title,
    required this.description,
    required this.icon,
    this.exportTemplate,
    this.backgroundPdfGenerator,
    this.pdfBuildsBuilder,
    required this.usageCode,
    this.initialRtl = false,
    this.additionalSettingsBuilder,
    this.configurationRevision,
  }) : assert(
          exportTemplate != null ||
              backgroundPdfGenerator != null ||
              pdfBuildsBuilder != null,
          'Provide exportTemplate, backgroundPdfGenerator, or pdfBuildsBuilder.',
        );

  final String category;
  final String title;
  final String description;
  final IconData icon;
  final TemplateImageExporter? exportTemplate;

  /// Optional split-thread PDF source generator for heavy examples.
  final TemplateImageBackgroundPdfGenerator? backgroundPdfGenerator;

  /// Optional manager-backed builder source.
  ///
  /// Builders returned here are submitted to the global
  /// [GeniusPdfGenerationManager] with `runInBackground: true`. The manager
  /// owns builder disposal after each job.
  final TemplateImagePdfBuildsBuilder? pdfBuildsBuilder;

  final String usageCode;
  final bool initialRtl;

  /// Optional template-specific customization controls.
  final TemplateImageAdditionalSettingsBuilder? additionalSettingsBuilder;

  /// Changes invalidate the previously exported preview.
  final Object? configurationRevision;

  @override
  State<TemplateImageExportDetailScreen> createState() =>
      _TemplateImageExportDetailScreenState();
}

class _TemplateImageExportDetailScreenState
    extends State<TemplateImageExportDetailScreen> {
  late bool _isRtl;
  GeniusExportFormat _format = GeniusExportFormat.png;
  GeniusImageQuality _quality = GeniusImageQuality.high;
  TemplateImageExportResult? _result;
  Object? _error;
  bool _running = false;
  bool _opening = false;
  int _pageIndex = 0;

  @override
  void initState() {
    super.initState();
    _isRtl = widget.initialRtl;
  }

  @override
  void didUpdateWidget(covariant TemplateImageExportDetailScreen oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.configurationRevision != widget.configurationRevision) {
      _invalidate();
    }
  }

  void _invalidate() {
    _result = null;
    _error = null;
    _pageIndex = 0;
  }

  void _setRtl(bool value) {
    if (_running || _opening || value == _isRtl) return;
    setState(() {
      _isRtl = value;
      _invalidate();
    });
  }

  void _setFormat(GeniusExportFormat value) {
    if (_running || _opening || value == _format) return;
    setState(() {
      _format = value;
      _invalidate();
    });
  }

  void _setQuality(GeniusImageQuality value) {
    if (_running || _opening || value == _quality) return;
    setState(() {
      _quality = value;
      _invalidate();
    });
  }

  Future<void> _run() async {
    if (_running || _opening) return;
    setState(() {
      _running = true;
      _error = null;
    });

    try {
      final pdfBuildsBuilder = widget.pdfBuildsBuilder;
      final backgroundPdfGenerator = widget.backgroundPdfGenerator;
      final TemplateImageExportResult result;
      if (pdfBuildsBuilder != null) {
        result = await _exportManagedPdfBuilds(
          pdfBuildsBuilder(isRtl: _isRtl),
          format: _format,
          quality: _quality,
        );
      } else if (backgroundPdfGenerator != null) {
        final batch = await backgroundPdfGenerator(isRtl: _isRtl);
        result = await _exportBackgroundPdfBatch(
          batch,
          format: _format,
          quality: _quality,
        );
      } else {
        result = await widget.exportTemplate!(
          isRtl: _isRtl,
          format: _format,
          quality: _quality,
          documents: demoDocuments,
        );
      }
      if (!mounted) return;
      setState(() {
        _result = result;
        _pageIndex = 0;
      });
    } catch (error) {
      if (!mounted) return;
      setState(() {
        _error = error;
        _result = null;
      });
    } finally {
      if (mounted) setState(() => _running = false);
    }
  }

  Future<TemplateImageExportResult> _exportManagedPdfBuilds(
    List<TemplateExampleBuild> builds, {
    required GeniusExportFormat format,
    required GeniusImageQuality quality,
  }) async {
    if (builds.isEmpty) {
      throw StateError('No PDF source builders were provided.');
    }

    final pdfDocuments = <Uint8List>[];
    final fileNames = <String>[];
    var submitted = 0;
    try {
      for (var index = 0; index < builds.length; index++) {
        final build = builds[index];
        submitted = index + 1;
        final success = await generateExamplePdf(
          builder: build.builder,
          fileName: build.fileName,
          metadata: <String, dynamic>{
            'screen': widget.title,
            'category': widget.category,
            'workflow': 'template-image-source',
            'sourceIndex': index,
          },
        );
        pdfDocuments.add(success.bytes);
        fileNames.add(build.fileName);
      }
    } finally {
      // The manager owns every submitted builder. Dispose only builders that
      // were never handed to the queue because a prior job failed.
      for (var index = submitted; index < builds.length; index++) {
        builds[index].builder.dispose();
      }
    }

    return _exportBackgroundPdfBatch(
      TemplateBackgroundPdfBatch(
        pdfDocuments: pdfDocuments,
        fileNames: fileNames,
      ),
      format: format,
      quality: quality,
    );
  }

  Future<TemplateImageExportResult> _exportBackgroundPdfBatch(
    TemplateBackgroundPdfBatch batch, {
    required GeniusExportFormat format,
    required GeniusImageQuality quality,
  }) async {
    final pages = <Uint8List>[];
    final paths = <String>[];

    for (var documentIndex = 0;
        documentIndex < batch.pdfDocuments.length;
        documentIndex++) {
      PdfDocument? document;
      try {
        document = PdfDocument(inputBytes: batch.pdfDocuments[documentIndex]);
        final results = await document.exportToImages(
          format: format,
          quality: quality,
        );

        for (var pageIndex = 0; pageIndex < results.length; pageIndex++) {
          switch (results[pageIndex]) {
            case GeniusExportSuccess(:final data):
              pages.add(data);
              paths.add(
                await demoDocuments.saveBytes(
                  bytes: data,
                  fileName:
                      '${batch.fileNames[documentIndex]}_${pageIndex + 1}.${format.extension}',
                ),
              );
            case GeniusExportFailure(:final message):
              throw StateError(message);
          }
        }
      } finally {
        document?.dispose();
      }
    }

    if (pages.isEmpty) {
      throw StateError(
        'The background-generated template did not produce image pages.',
      );
    }

    return TemplateImageExportResult(
      pages: pages,
      filePaths: paths,
      format: format,
      quality: quality,
    );
  }

  Future<void> _openCurrentImage() async {
    final result = _result;
    if (result == null || result.filePaths.isEmpty || _running || _opening) {
      return;
    }

    final safeIndex = _pageIndex.clamp(0, result.filePaths.length - 1).toInt();
    setState(() => _opening = true);
    try {
      await demoDocuments.open(result.filePaths[safeIndex]);
    } finally {
      if (mounted) setState(() => _opening = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final result = _result;
    final status = _running
        ? 'Exporting ${widget.title} to ${_format.displayName}…'
        : _error != null
            ? 'Export failed: $_error'
            : result == null
                ? 'Ready. Configure the image export and press Run export.'
                : 'Exported ${result.pageCount} page(s) as '
                    '${result.format.displayName} at '
                    '${result.quality.displayName} quality.';

    return FeatureExamplePage(
      title: '${widget.title} → Image',
      description: widget.description,
      icon: widget.icon,
      contentTitle: 'Image preview',
      contentDescription:
          pdfLocalization.previewExportedBytesSavedExampleDesc,
      settings: _buildSettings(),
      actions: <Widget>[
        FilledButton.icon(
          onPressed: (_running || _opening) ? null : _run,
          icon: _running
              ? const SizedBox.square(
                  dimension: 18,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
              : const Icon(Icons.image_outlined),
          label: Text(_running ? 'Exporting…' : 'Run export'),
        ),
        OutlinedButton.icon(
          onPressed: result == null || _running || _opening
              ? null
              : _openCurrentImage,
          icon: const Icon(Icons.open_in_new_rounded),
          label: Text(_opening ? 'Opening…' : 'Open image'),
        ),
      ],
      content: _ImagePreview(
        result: result,
        error: _error,
        running: _running,
        pageIndex: _pageIndex,
        onPageChanged: (index) => setState(() => _pageIndex = index),
      ),
      code: widget.usageCode,
      codeHeight: 720,
      statusMessage: status,
      statusTone: _error != null
          ? FeatureExampleTone.danger
          : _running
              ? FeatureExampleTone.info
              : result != null
                  ? FeatureExampleTone.success
                  : FeatureExampleTone.neutral,
    );
  }

  Widget _buildSettings() {
    final baseSettings = Wrap(
      spacing: 16,
      runSpacing: 12,
      crossAxisAlignment: WrapCrossAlignment.center,
      children: <Widget>[
        SegmentedButton<bool>(
          segments: <ButtonSegment<bool>>[
            ButtonSegment<bool>(value: false, label: Text(pdfLocalization.ltr)),
            ButtonSegment<bool>(value: true, label: Text(pdfLocalization.rtl)),
          ],
          selected: <bool>{_isRtl},
          onSelectionChanged: _running || _opening
              ? null
              : (selection) => _setRtl(selection.first),
        ),
        SegmentedButton<GeniusExportFormat>(
          segments: <ButtonSegment<GeniusExportFormat>>[
            ButtonSegment<GeniusExportFormat>(
              value: GeniusExportFormat.png,
              label: Text(pdfLocalization.png),
              icon: Icon(Icons.image_outlined),
            ),
            ButtonSegment<GeniusExportFormat>(
              value: GeniusExportFormat.jpeg,
              label: Text(pdfLocalization.jpeg),
              icon: Icon(Icons.photo_outlined),
            ),
          ],
          selected: <GeniusExportFormat>{_format},
          onSelectionChanged: _running || _opening
              ? null
              : (selection) => _setFormat(selection.first),
        ),
        DropdownButton<GeniusImageQuality>(
          value: _quality,
          onChanged: _running || _opening
              ? null
              : (value) {
                  if (value != null) _setQuality(value);
                },
          items: GeniusImageQuality.values
              .map(
                (quality) => DropdownMenuItem<GeniusImageQuality>(
                  value: quality,
                  child: Text(
                    '${quality.displayName} (${quality.dpi} DPI)',
                  ),
                ),
              )
              .toList(growable: false),
        ),
      ],
    );

    final additional = widget.additionalSettingsBuilder;
    if (additional == null) return baseSettings;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        baseSettings,
        const SizedBox(height: 16),
        additional(context, _running || _opening),
      ],
    );
  }
}

class _ImagePreview extends StatelessWidget {
  const _ImagePreview({
    required this.result,
    required this.error,
    required this.running,
    required this.pageIndex,
    required this.onPageChanged,
  });

  final TemplateImageExportResult? result;
  final Object? error;
  final bool running;
  final int pageIndex;
  final ValueChanged<int> onPageChanged;

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).colorScheme;

    if (running) {
      return  SizedBox(
        height: 560,
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              CircularProgressIndicator(),
              SizedBox(height: 12),
              Text(pdfLocalization.rasterizingTemplatePages),
            ],
          ),
        ),
      );
    }

    if (error != null) {
      return SizedBox(
        height: 560,
        child: Center(
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Text(
              '$error',
              textAlign: TextAlign.center,
              style: TextStyle(color: colors.error),
            ),
          ),
        ),
      );
    }

    final value = result;
    if (value == null) {
      return  SizedBox(
        height: 560,
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Icon(Icons.image_search_outlined, size: 48),
              SizedBox(height: 12),
              Text(pdfLocalization.noExportedImageYet),
              SizedBox(height: 6),
              Text(pdfLocalization.pressRunExportGeneratePreviewDesc),
            ],
          ),
        ),
      );
    }

    final safeIndex = pageIndex.clamp(0, value.pages.length - 1).toInt();
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: <Widget>[
        Row(
          children: <Widget>[
            Text('Page ${safeIndex + 1} / ${value.pages.length}'),
            const Spacer(),
            if (value.pages.length > 1) ...<Widget>[
              IconButton(
                tooltip: pdfLocalization.previousPage,
                onPressed: safeIndex > 0
                    ? () => onPageChanged(safeIndex - 1)
                    : null,
                icon: const Icon(Icons.chevron_left_rounded),
              ),
              IconButton(
                tooltip: pdfLocalization.nextPage,
                onPressed: safeIndex < value.pages.length - 1
                    ? () => onPageChanged(safeIndex + 1)
                    : null,
                icon: const Icon(Icons.chevron_right_rounded),
              ),
            ],
          ],
        ),
        const SizedBox(height: 8),
        Container(
          height: 520,
          alignment: Alignment.topCenter,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            color: colors.surfaceContainerLowest,
            border: Border.all(color: colors.outlineVariant),
            borderRadius: BorderRadius.circular(12),
          ),
          child: InteractiveViewer(
            minScale: 0.5,
            maxScale: 5,
            child: SingleChildScrollView(
              child: Image.memory(
                value.pages[safeIndex],
                fit: BoxFit.contain,
                gaplessPlayback: true,
              ),
            ),
          ),
        ),
      ],
    );
  }
}
