// Global manager/background migration for verification examples
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

import 'package:genius_pdf_example/shared/application/services/example_pdf_generation.dart';
import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/shared/presentation/widgets/code_viewer.dart';

import 'package:genius_pdf_example/localizations/pdf_generator_localization.dart';
typedef VerificationPdfGenerator = Future<Uint8List> Function(
  GeniusPdfConfig config,
);

typedef VerificationPdfBackgroundGenerator = Future<Uint8List> Function({
  required bool isRtl,
});

/// Shared page for one focused verification example.
///
/// The document is never generated during [initState]. Generation starts only
/// after the user presses **Run example**. The same generated bytes are used by
/// the inline preview and by **Open PDF**.
class VerificationExampleDetailScreen extends StatefulWidget {
  const VerificationExampleDetailScreen({
    super.key,
    required this.sprint,
    required this.title,
    required this.description,
    required this.apiName,
    required this.icon,
    this.generator,
    this.backgroundGenerator,
    required this.usageCode,
    required this.fileName,
    this.initialRtl = false,
    this.controls = const <Widget>[],
    this.configurationVersion,
    this.showGenerationToast = true,
    this.jobPriority = GeniusPdfJobPriority.normal,
  }) : assert(
          generator != null || backgroundGenerator != null,
          'Provide generator or backgroundGenerator.',
        );

  final String sprint;
  final String title;
  final String description;
  final String apiName;
  final IconData icon;
  final VerificationPdfGenerator? generator;
  final VerificationPdfBackgroundGenerator? backgroundGenerator;
  final String usageCode;
  final String fileName;
  final bool initialRtl;

  /// Optional scenario-specific controls that are not the example selector.
  final List<Widget> controls;

  /// Changing this value invalidates the current PDF preview.
  final Object? configurationVersion;

  /// Whether the app-wide generation observer should show Toasts.
  final bool showGenerationToast;

  /// Queue priority used by the global generation manager.
  final GeniusPdfJobPriority jobPriority;

  @override
  State<VerificationExampleDetailScreen> createState() =>
      _VerificationExampleDetailScreenState();
}

class _VerificationExampleDetailScreenState
    extends State<VerificationExampleDetailScreen> {
  late bool _isRtl;
  Uint8List? _previewData;
  String? _previewFilePath;
  Object? _error;
  bool _running = false;
  bool _opening = false;

  @override
  void initState() {
    super.initState();
    _isRtl = widget.initialRtl;
  }

  @override
  void didUpdateWidget(covariant VerificationExampleDetailScreen oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.configurationVersion != widget.configurationVersion) {
      _previewData = null;
      _previewFilePath = null;
      _error = null;
    }
  }

  GeniusPdfConfig get _config => geniusPdfConfig.copyWith(
        textDirection: _isRtl ? TextDirection.rtl : TextDirection.ltr,
      );

  void _setDirection(bool rtl) {
    if (rtl == _isRtl || _running || _opening) return;
    setState(() {
      _isRtl = rtl;
      _previewData = null;
      _previewFilePath = null;
      _error = null;
    });
  }

  Future<void> _run() async {
    if (_running || _opening) return;
    setState(() {
      _running = true;
      _error = null;
    });

    try {
      final backgroundGenerator = widget.backgroundGenerator;
      if (backgroundGenerator != null) {
        final fileName = widget.fileName.toLowerCase().endsWith('.pdf')
            ? widget.fileName.substring(0, widget.fileName.length - 4)
            : widget.fileName;

        final success = await generateExamplePdf(
          builder: ExampleBackgroundPdfBuilder(
            config: geniusPdfConfig,
            backgroundGenerator: () => backgroundGenerator(isRtl: _isRtl),
          ),
          fileName: fileName,
          priority: widget.jobPriority,
          metadata: <String, dynamic>{
            'feature': 'verification',
            'screen': widget.title,
            'sprint': widget.sprint,
            'apiName': widget.apiName,
            'workflow': 'verification-preview',
            'showGenerationToast': widget.showGenerationToast,
          },
        );

        if (!mounted) return;
        setState(() {
          _previewData = success.bytes;
          _previewFilePath = success.filePath;
        });
      } else {
        final bytes = await widget.generator!(_config);
        if (!mounted) return;
        setState(() {
          _previewData = bytes;
          _previewFilePath = null;
        });
      }
    } catch (error) {
      if (!mounted) return;
      setState(() {
        _error = error;
        _previewData = null;
        _previewFilePath = null;
      });
    } finally {
      if (mounted) setState(() => _running = false);
    }
  }

  Future<void> _openPdf() async {
    final bytes = _previewData;
    if (bytes == null || _running || _opening) return;

    setState(() => _opening = true);
    try {
      final filePath = _previewFilePath;
      if (filePath != null && filePath.isNotEmpty) {
        await demoDocuments.open(filePath);
      } else {
        await demoDocuments.saveAndOpen(
          bytes: bytes,
          fileName: widget.fileName,
        );
      }
    } finally {
      if (mounted) setState(() => _opening = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final colors = theme.colorScheme;

    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Icon(widget.icon, size: 30, color: colors.primary),
              const SizedBox(width: 14),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(widget.sprint, style: theme.textTheme.labelLarge),
                    const SizedBox(height: 4),
                    Text(widget.title, style: theme.textTheme.headlineSmall),
                    const SizedBox(height: 6),
                    Text(widget.description, style: theme.textTheme.bodyMedium),
                    const SizedBox(height: 4),
                    Text(widget.apiName, style: theme.textTheme.labelMedium),
                  ],
                ),
              ),
            ],
          ),
          const SizedBox(height: 20),
          Wrap(
            spacing: 10,
            runSpacing: 10,
            crossAxisAlignment: WrapCrossAlignment.center,
            children: [
              SegmentedButton<bool>(
                segments:  [
                  ButtonSegment(value: false, label: Text(pdfLocalization.ltr)),
                  ButtonSegment(value: true, label: Text(pdfLocalization.rtl)),
                ],
                selected: <bool>{_isRtl},
                onSelectionChanged: (_running || _opening)
                    ? null
                    : (selection) => _setDirection(selection.first),
              ),
              FilledButton.icon(
                onPressed: (_running || _opening) ? null : _run,
                icon: _running
                    ? const SizedBox(
                        width: 18,
                        height: 18,
                        child: CircularProgressIndicator(strokeWidth: 2),
                      )
                    : const Icon(Icons.play_arrow_rounded),
                label: Text(
                  _running
                      ? 'Running…'
                      : _previewData == null
                          ? 'Run example'
                          : 'Run again',
                ),
              ),
              OutlinedButton.icon(
                onPressed: _previewData == null || _running || _opening
                    ? null
                    : _openPdf,
                icon: const Icon(Icons.open_in_new_rounded),
                label: Text(_opening ? 'Opening…' : 'Open PDF'),
              ),
              ...widget.controls,
            ],
          ),
          const SizedBox(height: 20),
          LayoutBuilder(
            builder: (context, constraints) {
              final preview = _PreviewPanel(
                data: _previewData,
                error: _error,
                running: _running,
              );
              final code = CodeViewer(
                code: widget.usageCode,
                title: pdfLocalization.dartUsageCode,
              );

              if (constraints.maxWidth >= 1100) {
                return Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(child: preview),
                    const SizedBox(width: 20),
                    Expanded(child: code),
                  ],
                );
              }

              return Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  preview,
                  const SizedBox(height: 20),
                  code,
                ],
              );
            },
          ),
        ],
      ),
    );
  }
}

class _PreviewPanel extends StatelessWidget {
  const _PreviewPanel({
    required this.data,
    required this.error,
    required this.running,
  });

  final Uint8List? data;
  final Object? error;
  final bool running;

  @override
  Widget build(BuildContext context) {
    final colors = Theme.of(context).colorScheme;
    Widget child;

    if (running) {
      child =  Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            CircularProgressIndicator(),
            SizedBox(height: 12),
            Text(pdfLocalization.generatingPreview),
          ],
        ),
      );
    } else if (error != null) {
      child = Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Text(
            'Generation failed:\n$error',
            textAlign: TextAlign.center,
            style: TextStyle(color: colors.error),
          ),
        ),
      );
    } else if (data == null) {
      child =  Center(
        child: Padding(
          padding: EdgeInsets.all(24),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(Icons.picture_as_pdf_outlined, size: 42),
              SizedBox(height: 12),
              Text(pdfLocalization.readyToRun),
              SizedBox(height: 6),
              Text(
                pdfLocalization.pressRunExampleGenerateDocumentShowDesc2,
                textAlign: TextAlign.center,
              ),
            ],
          ),
        ),
      );
    } else {
      child = GeniusPdfPreviewWidget(
        pdfData: data!,
        canChangeOrientation: false,
        canChangePageFormat: false,
      );
    }

    return Card(
      clipBehavior: Clip.antiAlias,
      child: SizedBox(
        height: 720,
        child: child,
      ),
    );
  }
}
