// Generated by migrate_text_getting_architecture_sharing_custom_report_configuration_to_global_manager.py

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart';

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/features/components/models/documents/components/data_grid_invoice_footer_rows_demo_builder.dart';
import 'package:genius_pdf_example/features/components/models/documents/components/grid_qrcode_zatca_invoice_demo_builder.dart';
import 'package:genius_pdf_example/features/components/models/documents/components/grid_watermark_confidential_audit_demo_builder.dart';
import 'package:genius_pdf_example/features/components/models/documents/components/headers_invoice_header_demo_builder.dart';
import 'package:genius_pdf_example/features/components/models/documents/components/info_box_customer_company_info_boxes_demo_builder.dart';
import 'package:genius_pdf_example/features/components/models/documents/components/rich_text_fluent_formatting_demo_builder.dart';
import 'package:genius_pdf_example/features/components/models/documents/components/summary_basic_invoice_summary_demo_builder.dart';
import 'package:genius_pdf_example/features/getting_started/models/documents/s00_baseline/s00_long_content_demo_builder.dart';
import 'package:genius_pdf_example/features/getting_started/models/documents/s00_baseline/s00_mixed_baseline_demo_builder.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

TransferableTypedData _worker(Map<String, Object?> message) {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final apiName = message['apiName']! as String;

  final GeniusPdfDocumentBuilder builder = switch (apiName) {
    'BasicInvoiceSummaryDemoBuilder' => BasicInvoiceSummaryDemoBuilder(config),
    'CustomerCompanyInfoBoxesDemoBuilder' => CustomerCompanyInfoBoxesDemoBuilder(config),
    'DataGridInvoiceFooterRowsDemoBuilder' => DataGridInvoiceFooterRowsDemoBuilder(config),
    'GridQrcodeZatcaInvoiceDemoBuilder' => GridQrcodeZatcaInvoiceDemoBuilder(config),
    'GridWatermarkConfidentialAuditDemoBuilder' => GridWatermarkConfidentialAuditDemoBuilder(config),
    'InvoiceHeaderDemoBuilder' => InvoiceHeaderDemoBuilder(config),
    'RichTextFluentFormattingDemoBuilder' => RichTextFluentFormattingDemoBuilder(config),
    'S00LongContentDemoBuilder' => S00LongContentDemoBuilder(config),
    'S00MixedBaselineDemoBuilder' => S00MixedBaselineDemoBuilder(config),
    _ => throw ArgumentError.value(
        apiName,
        'apiName',
        'Unsupported S00 baseline builder',
      ),
  };

  try {
    return TransferableTypedData.fromList(
      <Uint8List>[Uint8List.fromList(builder.generate())],
    );
  } finally {
    builder.dispose();
  }
}

/// Generates one Getting Started S00 baseline PDF on a worker isolate.
Future<Uint8List> generateGettingStartedBaselineInBackground({
  required String apiName,
  required bool isRtl,
}) async {
  final config = geniusPdfConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'apiName': apiName,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _worker(message),
    debugName: 'getting-started-$apiName',
  );
  return transferred.materialize().asUint8List();
}
