import 'dart:typed_data';

import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;
import 'package:pdf/pdf.dart' hide PdfFont;
import 'package:pdf/widgets.dart' as pw;
import 'package:syncfusion_flutter_pdf/pdf.dart';

Future<Uint8List> buildSimpleDocumentBytes() async {
  return GeniusPdfBuilder(
        id: 'simple-doc',
        config: GeniusPdfConfig(baseFont: PdfStandardFont(PdfFontFamily.helvetica, 10)),
      )
      .metadata(title: 'Simple Document', author: 'Demo')
      .pageFormat(PdfPageFormat.a4)
      .addPage((page) => page
          .header('Welcome to V2 Architecture')
          .spacer(12)
          .paragraph(
              'This document demonstrates a detailed, component-rich layout '
              'using the enhanced Fluent API. It includes headers, subheaders, '
              'tables, lists, dividers, rich text, and styled containers.')
          .spacer(10)
          .subheader('Highlights')
          .bulletList([
            'Plugin System for extensibility',
            'Dependency Injection container',
            'Event-driven architecture',
            'Smart caching system',
            'Platform compatibility',
          ])
          .spacer(10)
          .numberedList([
            'Define content with chainable methods',
            'Generate bytes in-memory',
            'Save and open with one flow',
          ])
          .spacer(10)
          .divider()
          .spacer(10)
          .subheader('Quick Overview')
          .table(
            [
              ['Fluent API', 'Document building', 'Stable'],
              ['Plugins', 'Extensibility layer', 'Beta'],
              ['DI', 'Service resolution', 'Stable'],
              ['Events', 'Lifecycle tracking', 'Stable'],
            ],
            headers: ['Module', 'Purpose', 'Status'],
          )
          .spacer(10)
          .richText([
            pw.TextSpan(text: 'Note: ', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            const pw.TextSpan(text: 'You can mix built-in components with custom widgets '),
            pw.TextSpan(text: 'to build complex layouts.', style: pw.TextStyle(color: PdfColors.blueGrey)),
          ])
          .spacer(10)
          .container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey200,
              borderRadius: pw.BorderRadius.circular(6),
              border: pw.Border.all(color: PdfColors.grey400),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Summary Card', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 6),
                pw.Text('This container demonstrates styled boxes and custom layout.'),
              ],
            ),
          )
          .spacer(10)
          .row([
            pw.Expanded(child: pw.Text('Left Column: Status')), 
            pw.Text('Active', style: pw.TextStyle(color: PdfColors.green)),
          ])
          .spacer(12)
          .footer('Generated by Genius Link PDF Generator')
          .build())
      .buildBytes();
}
