// Generated by migrate_text_getting_architecture_sharing_custom_report_configuration_to_global_manager.py

import 'dart:isolate';
import 'dart:typed_data';
import 'dart:ui';

import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart';

import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _worker(Map<String, Object?> message) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );

  final document = PdfDocument();
  try {
    final page = document.pages.add();
    final graphics = page.graphics;
    final font = PdfTrueTypeFont(config.baseFontBytes, 12);
    final titleFont = PdfTrueTypeFont(
      config.baseFontBytes,
      18,
      style: PdfFontStyle.bold,
    );

    graphics.drawString(
      'Genius Link PDF Generator',
      titleFont,
      brush: PdfSolidBrush(PdfColor(0, 51, 102)),
      bounds: const Rect.fromLTWH(50, 50, 500, 30),
      format: PdfStringFormat(textDirection: config.pdfTextDirection),
    );
    graphics.drawString(
      'Sharing Demo Document (v2.3.x)',
      font,
      brush: PdfSolidBrush(PdfColor(100, 100, 100)),
      bounds: const Rect.fromLTWH(50, 90, 500, 30),
      format: PdfStringFormat(textDirection: config.pdfTextDirection),
    );
    graphics.drawLine(
      PdfPen(PdfColor(0, 51, 102), width: 2),
      const Offset(50, 130),
      const Offset(550, 130),
    );
    graphics.drawString(
      'Generated: ${DateTime.now().toString().split('.').first}',
      font,
      brush: PdfSolidBrush(PdfColor(100, 100, 100)),
      bounds: const Rect.fromLTWH(50, 150, 500, 30),
      format: PdfStringFormat(textDirection: config.pdfTextDirection),
    );
    graphics.drawString(
      'This document demonstrates the sharing capabilities '
      'of the Genius Link PDF Generator library.',
      font,
      brush: PdfSolidBrush(PdfColor(0, 0, 0)),
      bounds: const Rect.fromLTWH(50, 200, 500, 100),
      format: PdfStringFormat(textDirection: config.pdfTextDirection),
    );

    const features = <String>[
      '• Unified sharing service',
      '• Email with attachments',
      '• Bluetooth/Nearby Share',
      '• WhatsApp & Telegram',
      '• Local storage saving',
    ];
    var yPos = 320.0;
    for (final feature in features) {
      graphics.drawString(
        feature,
        font,
        brush: PdfSolidBrush(PdfColor(0, 0, 0)),
        bounds: Rect.fromLTWH(50, yPos, 500, 25),
        format: PdfStringFormat(textDirection: config.pdfTextDirection),
      );
      yPos += 30;
    }

    return TransferableTypedData.fromList(
      <Uint8List>[Uint8List.fromList(await document.save())],
    );
  } finally {
    document.dispose();
  }
}

/// Generates the Sharing feature's sample PDF outside the UI isolate.
Future<Uint8List> generateSharingSamplePdfInBackground({
  required GeniusPdfConfig config,
}) async {
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
  };
  final transferred = await Isolate.run<TransferableTypedData>(
    () => _worker(message),
    debugName: 'sharing-sample-pdf',
  );
  return transferred.materialize().asUint8List();
}
