import 'dart:ui';
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;
import '../../app/dependencies/example_dependencies.dart';
import '../../features/components/models/documents/components/data_grid_demo_builder.dart';
import '../../features/components/models/documents/components/headers_demo_builder.dart';
import '../../features/showcase/models/documents/advanced_layout_demo_document.dart';
import '../../features/showcase/models/documents/qr_attachments_demo_document.dart';

GeniusPdfConfig showcaseConfig({TextDirection direction = TextDirection.ltr}) =>
    geniusPdfConfig.copyWith(textDirection: direction);

GeniusPdfDocumentBuilder createShowcaseBuilder(String kind, {GeniusPdfConfig? config}) {
  final resolved = config ?? showcaseConfig();
  switch (kind) {
    case 'headers':
      return HeadersDemoBuilder(resolved);
    case 'grid':
      return DataGridDemoBuilder(resolved);
    case 'media':
      return QRAttachmentsDemoBuilder(config: resolved);
    case 'advancedLayout':
      return AdvancedLayoutDemoBuilder(config: resolved);
    case 'typography':
      return _TypographyDocument(resolved);
    case 'directionality':
      return _DirectionalityDocument(config ?? showcaseConfig(direction: TextDirection.rtl));
    default:
      return _BasicDocument(resolved);
  }
}

class _BasicDocument extends GeniusPdfDocumentBuilder {
  _BasicDocument(super.config);
  @override
  void build() {
    addHeader(title: 'Genius PDF developer showcase');
    addLine('A compact working document generated by the example application.');
    addSpace(12);
    addLine('Use the action toolbar to preview, save, open, share, or print it.');
    addFooter(userName: 'Example app', showPageNumber: true);
  }
}

class _TypographyDocument extends GeniusPdfDocumentBuilder {
  _TypographyDocument(super.config);
  @override
  void build() {
    addHeader(title: 'Text and typography');
    addLine('Body copy rendered with the configured primary font.');
    addLine('Bold and heading roles are supplied independently by GeniusPdfConfig.');
    addSpace(12);
    addRichText(
      GeniusPdfRichText(
        config: config,
        spans: const [
          GeniusPdfTextSpan(text: 'Rich text combines '),
          GeniusPdfTextSpan(text: 'emphasis', isBold: true),
          GeniusPdfTextSpan(text: ', color and structured inline content.'),
        ],
      ),
    );
    addFooter(userName: 'Typography demo', showPageNumber: true);
  }
}

class _DirectionalityDocument extends GeniusPdfDocumentBuilder {
  _DirectionalityDocument(super.config);
  @override
  void build() {
    addHeader(title: 'تقرير ثنائي اللغة');
    addLine('يدعم المستند اتجاه الكتابة من اليمين إلى اليسار.');
    addLine('Genius PDF also supports LTR content in the same application.');
    addSpace(12);
    addLine('Arabic / English • العربية / English');
    addFooter(userName: 'مثال المطورين', showPageNumber: true);
  }
}
