// Generated by migrate_barcode_business_components_to_global_manager.py
//
// Isolate-safe dispatcher for Business Templates verification examples.

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s08_doc_families_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s09_migrated_tx_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s12_sales_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s13_purchasing_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s14_accounting_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s15_inventory_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s16_pos_retail_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s17_hr_payroll_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s18_mfg_quality_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s19_assets_projects_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s20_service_logistics_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s21_crm_pack_verification_documents.dart';
import 'package:genius_pdf_example/features/business_templates/models/documents/s26_industries_verification_documents.dart';

Future<TransferableTypedData> _worker(Map<String, Object?> message) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final apiName = message['apiName']! as String;

  late final Uint8List bytes;
  switch (apiName) {
    case 'buildS08AnalyticalVerificationPdf':
      bytes = await buildS08AnalyticalVerificationPdf(config);
      break;
    case 'buildS08CertificateVerificationPdf':
      bytes = await buildS08CertificateVerificationPdf(config);
      break;
    case 'buildS08CustomSlotsVerificationPdf':
      bytes = await buildS08CustomSlotsVerificationPdf(config);
      break;
    case 'buildS08LabelVerificationPdf':
      bytes = await buildS08LabelVerificationPdf(config);
      break;
    case 'buildS08LongMultiPageVerificationPdf':
      bytes = await buildS08LongMultiPageVerificationPdf(config);
      break;
    case 'buildS08OperationalVerificationPdf':
      bytes = await buildS08OperationalVerificationPdf(config);
      break;
    case 'buildS08RegisterVerificationPdf':
      bytes = await buildS08RegisterVerificationPdf(config);
      break;
    case 'buildS08StatementVerificationPdf':
      bytes = await buildS08StatementVerificationPdf(config);
      break;
    case 'buildS08ThermalVerificationPdf':
      bytes = await buildS08ThermalVerificationPdf(config);
      break;
    case 'buildS08TransactionVerificationPdf':
      bytes = await buildS08TransactionVerificationPdf(config);
      break;
    case 'buildS08VoucherVerificationPdf':
      bytes = await buildS08VoucherVerificationPdf(config);
      break;
    case 'buildS09BilingualVerificationPdf':
      bytes = await buildS09BilingualVerificationPdf(config);
      break;
    case 'buildS09LongContentVerificationPdf':
      bytes = await buildS09LongContentVerificationPdf(config);
      break;
    case 'buildS09NullOptionalVerificationPdf':
      bytes = await buildS09NullOptionalVerificationPdf(config);
      break;
    case 'buildS09PurchaseOrder50VerificationPdf':
      bytes = await buildS09PurchaseOrder50VerificationPdf(config);
      break;
    case 'buildS09Quotation1VerificationPdf':
      bytes = await buildS09Quotation1VerificationPdf(config);
      break;
    case 'buildS09TaxInvoice500VerificationPdf':
      bytes = await buildS09TaxInvoice500VerificationPdf(config);
      break;
    case 'buildS12BackorderVerificationPdf':
      bytes = await buildS12BackorderVerificationPdf(config);
      break;
    case 'buildS12ByCustomerVerificationPdf':
      bytes = await buildS12ByCustomerVerificationPdf(config);
      break;
    case 'buildS12ByItemVerificationPdf':
      bytes = await buildS12ByItemVerificationPdf(config);
      break;
    case 'buildS12BySalespersonVerificationPdf':
      bytes = await buildS12BySalespersonVerificationPdf(config);
      break;
    case 'buildS12CommissionVerificationPdf':
      bytes = await buildS12CommissionVerificationPdf(config);
      break;
    case 'buildS12CustomerAgingVerificationPdf':
      bytes = await buildS12CustomerAgingVerificationPdf(config);
      break;
    case 'buildS12CustomerReceiptVerificationPdf':
      bytes = await buildS12CustomerReceiptVerificationPdf(config);
      break;
    case 'buildS12DebitNoteVerificationPdf':
      bytes = await buildS12DebitNoteVerificationPdf(config);
      break;
    case 'buildS12PackingVerificationPdf':
      bytes = await buildS12PackingVerificationPdf(config);
      break;
    case 'buildS12PickingVerificationPdf':
      bytes = await buildS12PickingVerificationPdf(config);
      break;
    case 'buildS12PosVerificationPdf':
      bytes = await buildS12PosVerificationPdf(config);
      break;
    case 'buildS12PriceListVerificationPdf':
      bytes = await buildS12PriceListVerificationPdf(config);
      break;
    case 'buildS12ProformaVerificationPdf':
      bytes = await buildS12ProformaVerificationPdf(config);
      break;
    case 'buildS12SalesOrderVerificationPdf':
      bytes = await buildS12SalesOrderVerificationPdf(config);
      break;
    case 'buildS12SalesRegisterVerificationPdf':
      bytes = await buildS12SalesRegisterVerificationPdf(config);
      break;
    case 'buildS12SalesReturnVerificationPdf':
      bytes = await buildS12SalesReturnVerificationPdf(config);
      break;
    case 'buildS13ComparisonVerificationPdf':
      bytes = await buildS13ComparisonVerificationPdf(config);
      break;
    case 'buildS13GrnVerificationPdf':
      bytes = await buildS13GrnVerificationPdf(config);
      break;
    case 'buildS13OutstandingPoVerificationPdf':
      bytes = await buildS13OutstandingPoVerificationPdf(config);
      break;
    case 'buildS13PurchaseAnalysisVerificationPdf':
      bytes = await buildS13PurchaseAnalysisVerificationPdf(config);
      break;
    case 'buildS13PurchaseCreditVerificationPdf':
      bytes = await buildS13PurchaseCreditVerificationPdf(config);
      break;
    case 'buildS13PurchaseDebitVerificationPdf':
      bytes = await buildS13PurchaseDebitVerificationPdf(config);
      break;
    case 'buildS13PurchaseInvoiceVerificationPdf':
      bytes = await buildS13PurchaseInvoiceVerificationPdf(config);
      break;
    case 'buildS13PurchaseOrderVerificationPdf':
      bytes = await buildS13PurchaseOrderVerificationPdf(config);
      break;
    case 'buildS13PurchaseRegisterVerificationPdf':
      bytes = await buildS13PurchaseRegisterVerificationPdf(config);
      break;
    case 'buildS13RequisitionVerificationPdf':
      bytes = await buildS13RequisitionVerificationPdf(config);
      break;
    case 'buildS13RfqVerificationPdf':
      bytes = await buildS13RfqVerificationPdf(config);
      break;
    case 'buildS13SupplierAgingVerificationPdf':
      bytes = await buildS13SupplierAgingVerificationPdf(config);
      break;
    case 'buildS13SupplierQuotationVerificationPdf':
      bytes = await buildS13SupplierQuotationVerificationPdf(config);
      break;
    case 'buildS13SupplierReturnVerificationPdf':
      bytes = await buildS13SupplierReturnVerificationPdf(config);
      break;
    case 'buildS13SupplierStatementVerificationPdf':
      bytes = await buildS13SupplierStatementVerificationPdf(config);
      break;
    case 'buildS14AccountStatementVerificationPdf':
      bytes = await buildS14AccountStatementVerificationPdf(config);
      break;
    case 'buildS14ApAgingVerificationPdf':
      bytes = await buildS14ApAgingVerificationPdf(config);
      break;
    case 'buildS14ArAgingVerificationPdf':
      bytes = await buildS14ArAgingVerificationPdf(config);
      break;
    case 'buildS14BankBookVerificationPdf':
      bytes = await buildS14BankBookVerificationPdf(config);
      break;
    case 'buildS14BankReconciliationVerificationPdf':
      bytes = await buildS14BankReconciliationVerificationPdf(config);
      break;
    case 'buildS14BudgetVsActualVerificationPdf':
      bytes = await buildS14BudgetVsActualVerificationPdf(config);
      break;
    case 'buildS14CashBookVerificationPdf':
      bytes = await buildS14CashBookVerificationPdf(config);
      break;
    case 'buildS14CostCenterStatementVerificationPdf':
      bytes = await buildS14CostCenterStatementVerificationPdf(config);
      break;
    case 'buildS14CostCenterTrialBalanceVerificationPdf':
      bytes = await buildS14CostCenterTrialBalanceVerificationPdf(config);
      break;
    case 'buildS14CustomerBalancesVerificationPdf':
      bytes = await buildS14CustomerBalancesVerificationPdf(config);
      break;
    case 'buildS14GeneralLedgerVerificationPdf':
      bytes = await buildS14GeneralLedgerVerificationPdf(config);
      break;
    case 'buildS14JournalEntryVerificationPdf':
      bytes = await buildS14JournalEntryVerificationPdf(config);
      break;
    case 'buildS14JournalRegisterVerificationPdf':
      bytes = await buildS14JournalRegisterVerificationPdf(config);
      break;
    case 'buildS14MultiPeriodVerificationPdf':
      bytes = await buildS14MultiPeriodVerificationPdf(config);
      break;
    case 'buildS14PaymentRegisterVerificationPdf':
      bytes = await buildS14PaymentRegisterVerificationPdf(config);
      break;
    case 'buildS14PettyCashVerificationPdf':
      bytes = await buildS14PettyCashVerificationPdf(config);
      break;
    case 'buildS14ProjectFinancialVerificationPdf':
      bytes = await buildS14ProjectFinancialVerificationPdf(config);
      break;
    case 'buildS14ReceiptRegisterVerificationPdf':
      bytes = await buildS14ReceiptRegisterVerificationPdf(config);
      break;
    case 'buildS14ReconciliationVerificationPdf':
      bytes = await buildS14ReconciliationVerificationPdf(config);
      break;
    case 'buildS14SupplierBalancesVerificationPdf':
      bytes = await buildS14SupplierBalancesVerificationPdf(config);
      break;
    case 'buildS14TaxBreakdownVerificationPdf':
      bytes = await buildS14TaxBreakdownVerificationPdf(config);
      break;
    case 'buildS14TaxRegisterVerificationPdf':
      bytes = await buildS14TaxRegisterVerificationPdf(config);
      break;
    case 'buildS14VatSummaryVerificationPdf':
      bytes = await buildS14VatSummaryVerificationPdf(config);
      break;
    case 'buildS15AdjustmentVerificationPdf':
      bytes = await buildS15AdjustmentVerificationPdf(config);
      break;
    case 'buildS15AvailabilityVerificationPdf':
      bytes = await buildS15AvailabilityVerificationPdf(config);
      break;
    case 'buildS15BatchLabelVerificationPdf':
      bytes = await buildS15BatchLabelVerificationPdf(config);
      break;
    case 'buildS15BatchReportVerificationPdf':
      bytes = await buildS15BatchReportVerificationPdf(config);
      break;
    case 'buildS15CycleCountVerificationPdf':
      bytes = await buildS15CycleCountVerificationPdf(config);
      break;
    case 'buildS15ExpiryReportVerificationPdf':
      bytes = await buildS15ExpiryReportVerificationPdf(config);
      break;
    case 'buildS15ItemCardVerificationPdf':
      bytes = await buildS15ItemCardVerificationPdf(config);
      break;
    case 'buildS15ItemLabelVerificationPdf':
      bytes = await buildS15ItemLabelVerificationPdf(config);
      break;
    case 'buildS15LocationLabelVerificationPdf':
      bytes = await buildS15LocationLabelVerificationPdf(config);
      break;
    case 'buildS15MinMaxVerificationPdf':
      bytes = await buildS15MinMaxVerificationPdf(config);
      break;
    case 'buildS15ReconciliationVerificationPdf':
      bytes = await buildS15ReconciliationVerificationPdf(config);
      break;
    case 'buildS15ReorderVerificationPdf':
      bytes = await buildS15ReorderVerificationPdf(config);
      break;
    case 'buildS15SerialLabelVerificationPdf':
      bytes = await buildS15SerialLabelVerificationPdf(config);
      break;
    case 'buildS15SerialReportVerificationPdf':
      bytes = await buildS15SerialReportVerificationPdf(config);
      break;
    case 'buildS15ShelfLabelVerificationPdf':
      bytes = await buildS15ShelfLabelVerificationPdf(config);
      break;
    case 'buildS15SlowDeadVerificationPdf':
      bytes = await buildS15SlowDeadVerificationPdf(config);
      break;
    case 'buildS15StockCountVerificationPdf':
      bytes = await buildS15StockCountVerificationPdf(config);
      break;
    case 'buildS15StockIssueVerificationPdf':
      bytes = await buildS15StockIssueVerificationPdf(config);
      break;
    case 'buildS15StockLedgerVerificationPdf':
      bytes = await buildS15StockLedgerVerificationPdf(config);
      break;
    case 'buildS15StockReceiptVerificationPdf':
      bytes = await buildS15StockReceiptVerificationPdf(config);
      break;
    case 'buildS15StockTransferVerificationPdf':
      bytes = await buildS15StockTransferVerificationPdf(config);
      break;
    case 'buildS15ValuationVerificationPdf':
      bytes = await buildS15ValuationVerificationPdf(config);
      break;
    case 'buildS15WarehouseTransferVerificationPdf':
      bytes = await buildS15WarehouseTransferVerificationPdf(config);
      break;
    case 'buildS16BarcodeLabelVerificationPdf':
      bytes = await buildS16BarcodeLabelVerificationPdf(config);
      break;
    case 'buildS16CashDrawerVerificationPdf':
      bytes = await buildS16CashDrawerVerificationPdf(config);
      break;
    case 'buildS16ExchangeVerificationPdf':
      bytes = await buildS16ExchangeVerificationPdf(config);
      break;
    case 'buildS16GiftVerificationPdf':
      bytes = await buildS16GiftVerificationPdf(config);
      break;
    case 'buildS16KotVerificationPdf':
      bytes = await buildS16KotVerificationPdf(config);
      break;
    case 'buildS16PaymentSummaryVerificationPdf':
      bytes = await buildS16PaymentSummaryVerificationPdf(config);
      break;
    case 'buildS16PriceLabelVerificationPdf':
      bytes = await buildS16PriceLabelVerificationPdf(config);
      break;
    case 'buildS16PromotionLabelVerificationPdf':
      bytes = await buildS16PromotionLabelVerificationPdf(config);
      break;
    case 'buildS16Receipt58VerificationPdf':
      bytes = await buildS16Receipt58VerificationPdf(config);
      break;
    case 'buildS16Receipt80VerificationPdf':
      bytes = await buildS16Receipt80VerificationPdf(config);
      break;
    case 'buildS16RefundVerificationPdf':
      bytes = await buildS16RefundVerificationPdf(config);
      break;
    case 'buildS16ShiftCloseVerificationPdf':
      bytes = await buildS16ShiftCloseVerificationPdf(config);
      break;
    case 'buildS16ShiftOpenVerificationPdf':
      bytes = await buildS16ShiftOpenVerificationPdf(config);
      break;
    case 'buildS16XReportVerificationPdf':
      bytes = await buildS16XReportVerificationPdf(config);
      break;
    case 'buildS16ZReportVerificationPdf':
      bytes = await buildS16ZReportVerificationPdf(config);
      break;
    case 'buildS17AllowancesVerificationPdf':
      bytes = await buildS17AllowancesVerificationPdf(config);
      break;
    case 'buildS17AttendanceVerificationPdf':
      bytes = await buildS17AttendanceVerificationPdf(config);
      break;
    case 'buildS17DeductionsVerificationPdf':
      bytes = await buildS17DeductionsVerificationPdf(config);
      break;
    case 'buildS17EmployeeActionVerificationPdf':
      bytes = await buildS17EmployeeActionVerificationPdf(config);
      break;
    case 'buildS17EmployeeListVerificationPdf':
      bytes = await buildS17EmployeeListVerificationPdf(config);
      break;
    case 'buildS17EmployeeProfileVerificationPdf':
      bytes = await buildS17EmployeeProfileVerificationPdf(config);
      break;
    case 'buildS17EmploymentCertificateVerificationPdf':
      bytes = await buildS17EmploymentCertificateVerificationPdf(config);
      break;
    case 'buildS17EmploymentContractVerificationPdf':
      bytes = await buildS17EmploymentContractVerificationPdf(config);
      break;
    case 'buildS17EndOfServiceVerificationPdf':
      bytes = await buildS17EndOfServiceVerificationPdf(config);
      break;
    case 'buildS17ExperienceCertificateVerificationPdf':
      bytes = await buildS17ExperienceCertificateVerificationPdf(config);
      break;
    case 'buildS17FinalSettlementVerificationPdf':
      bytes = await buildS17FinalSettlementVerificationPdf(config);
      break;
    case 'buildS17LeaveBalanceVerificationPdf':
      bytes = await buildS17LeaveBalanceVerificationPdf(config);
      break;
    case 'buildS17LeaveRequestVerificationPdf':
      bytes = await buildS17LeaveRequestVerificationPdf(config);
      break;
    case 'buildS17LoanAdvanceVerificationPdf':
      bytes = await buildS17LoanAdvanceVerificationPdf(config);
      break;
    case 'buildS17OvertimeVerificationPdf':
      bytes = await buildS17OvertimeVerificationPdf(config);
      break;
    case 'buildS17PayrollSheetVerificationPdf':
      bytes = await buildS17PayrollSheetVerificationPdf(config);
      break;
    case 'buildS17PayrollSummaryVerificationPdf':
      bytes = await buildS17PayrollSummaryVerificationPdf(config);
      break;
    case 'buildS17PayslipVerificationPdf':
      bytes = await buildS17PayslipVerificationPdf(config);
      break;
    case 'buildS17SalaryCertificateVerificationPdf':
      bytes = await buildS17SalaryCertificateVerificationPdf(config);
      break;
    case 'buildS17TimesheetVerificationPdf':
      bytes = await buildS17TimesheetVerificationPdf(config);
      break;
    case 'buildS18AuditVerificationPdf':
      bytes = await buildS18AuditVerificationPdf(config);
      break;
    case 'buildS18BomVerificationPdf':
      bytes = await buildS18BomVerificationPdf(config);
      break;
    case 'buildS18CalibrationVerificationPdf':
      bytes = await buildS18CalibrationVerificationPdf(config);
      break;
    case 'buildS18CapaVerificationPdf':
      bytes = await buildS18CapaVerificationPdf(config);
      break;
    case 'buildS18CoaVerificationPdf':
      bytes = await buildS18CoaVerificationPdf(config);
      break;
    case 'buildS18FinalInspectionVerificationPdf':
      bytes = await buildS18FinalInspectionVerificationPdf(config);
      break;
    case 'buildS18InProcessInspectionVerificationPdf':
      bytes = await buildS18InProcessInspectionVerificationPdf(config);
      break;
    case 'buildS18IncomingInspectionVerificationPdf':
      bytes = await buildS18IncomingInspectionVerificationPdf(config);
      break;
    case 'buildS18JobCardVerificationPdf':
      bytes = await buildS18JobCardVerificationPdf(config);
      break;
    case 'buildS18LaborVerificationPdf':
      bytes = await buildS18LaborVerificationPdf(config);
      break;
    case 'buildS18MachineOperationVerificationPdf':
      bytes = await buildS18MachineOperationVerificationPdf(config);
      break;
    case 'buildS18MaterialIssueVerificationPdf':
      bytes = await buildS18MaterialIssueVerificationPdf(config);
      break;
    case 'buildS18MaterialRequirementVerificationPdf':
      bytes = await buildS18MaterialRequirementVerificationPdf(config);
      break;
    case 'buildS18MaterialReturnVerificationPdf':
      bytes = await buildS18MaterialReturnVerificationPdf(config);
      break;
    case 'buildS18NcrVerificationPdf':
      bytes = await buildS18NcrVerificationPdf(config);
      break;
    case 'buildS18NestedTablesVerificationPdf':
      bytes = await buildS18NestedTablesVerificationPdf(config);
      break;
    case 'buildS18ProductionOrderVerificationPdf':
      bytes = await buildS18ProductionOrderVerificationPdf(config);
      break;
    case 'buildS18ProductionReceiptVerificationPdf':
      bytes = await buildS18ProductionReceiptVerificationPdf(config);
      break;
    case 'buildS18QualityChecklistVerificationPdf':
      bytes = await buildS18QualityChecklistVerificationPdf(config);
      break;
    case 'buildS18QualityInspectionVerificationPdf':
      bytes = await buildS18QualityInspectionVerificationPdf(config);
      break;
    case 'buildS18RoutingVerificationPdf':
      bytes = await buildS18RoutingVerificationPdf(config);
      break;
    case 'buildS18ScrapVerificationPdf':
      bytes = await buildS18ScrapVerificationPdf(config);
      break;
    case 'buildS18VarianceVerificationPdf':
      bytes = await buildS18VarianceVerificationPdf(config);
      break;
    case 'buildS18WipVerificationPdf':
      bytes = await buildS18WipVerificationPdf(config);
      break;
    case 'buildS18WorkOrderVerificationPdf':
      bytes = await buildS18WorkOrderVerificationPdf(config);
      break;
    case 'buildS19AssetAssignmentVerificationPdf':
      bytes = await buildS19AssetAssignmentVerificationPdf(config);
      break;
    case 'buildS19AssetCardVerificationPdf':
      bytes = await buildS19AssetCardVerificationPdf(config);
      break;
    case 'buildS19AssetCountVerificationPdf':
      bytes = await buildS19AssetCountVerificationPdf(config);
      break;
    case 'buildS19AssetDisposalVerificationPdf':
      bytes = await buildS19AssetDisposalVerificationPdf(config);
      break;
    case 'buildS19AssetLabelVerificationPdf':
      bytes = await buildS19AssetLabelVerificationPdf(config);
      break;
    case 'buildS19AssetMaintenanceVerificationPdf':
      bytes = await buildS19AssetMaintenanceVerificationPdf(config);
      break;
    case 'buildS19AssetMovementVerificationPdf':
      bytes = await buildS19AssetMovementVerificationPdf(config);
      break;
    case 'buildS19AssetRegisterVerificationPdf':
      bytes = await buildS19AssetRegisterVerificationPdf(config);
      break;
    case 'buildS19AssetReturnVerificationPdf':
      bytes = await buildS19AssetReturnVerificationPdf(config);
      break;
    case 'buildS19AssetTransferVerificationPdf':
      bytes = await buildS19AssetTransferVerificationPdf(config);
      break;
    case 'buildS19CompletionCertificateVerificationPdf':
      bytes = await buildS19CompletionCertificateVerificationPdf(config);
      break;
    case 'buildS19DepreciationVerificationPdf':
      bytes = await buildS19DepreciationVerificationPdf(config);
      break;
    case 'buildS19MilestoneVerificationPdf':
      bytes = await buildS19MilestoneVerificationPdf(config);
      break;
    case 'buildS19MultiPeriodFinancialsVerificationPdf':
      bytes = await buildS19MultiPeriodFinancialsVerificationPdf(config);
      break;
    case 'buildS19ProgressVerificationPdf':
      bytes = await buildS19ProgressVerificationPdf(config);
      break;
    case 'buildS19ProjectBillingVerificationPdf':
      bytes = await buildS19ProjectBillingVerificationPdf(config);
      break;
    case 'buildS19ProjectBudgetVerificationPdf':
      bytes = await buildS19ProjectBudgetVerificationPdf(config);
      break;
    case 'buildS19ProjectCostVerificationPdf':
      bytes = await buildS19ProjectCostVerificationPdf(config);
      break;
    case 'buildS19ProjectExpenseVerificationPdf':
      bytes = await buildS19ProjectExpenseVerificationPdf(config);
      break;
    case 'buildS19ProjectProfitabilityVerificationPdf':
      bytes = await buildS19ProjectProfitabilityVerificationPdf(config);
      break;
    case 'buildS19ProjectPurchasingVerificationPdf':
      bytes = await buildS19ProjectPurchasingVerificationPdf(config);
      break;
    case 'buildS19ProjectSummaryVerificationPdf':
      bytes = await buildS19ProjectSummaryVerificationPdf(config);
      break;
    case 'buildS19ProjectTimesheetVerificationPdf':
      bytes = await buildS19ProjectTimesheetVerificationPdf(config);
      break;
    case 'buildS19ResourceUtilizationVerificationPdf':
      bytes = await buildS19ResourceUtilizationVerificationPdf(config);
      break;
    case 'buildS20ContainerListVerificationPdf':
      bytes = await buildS20ContainerListVerificationPdf(config);
      break;
    case 'buildS20DispatchNoteVerificationPdf':
      bytes = await buildS20DispatchNoteVerificationPdf(config);
      break;
    case 'buildS20FreightSummaryVerificationPdf':
      bytes = await buildS20FreightSummaryVerificationPdf(config);
      break;
    case 'buildS20InspectionVerificationPdf':
      bytes = await buildS20InspectionVerificationPdf(config);
      break;
    case 'buildS20MaintenanceChecklistVerificationPdf':
      bytes = await buildS20MaintenanceChecklistVerificationPdf(config);
      break;
    case 'buildS20MaintenanceWorkOrderVerificationPdf':
      bytes = await buildS20MaintenanceWorkOrderVerificationPdf(config);
      break;
    case 'buildS20ManifestVerificationPdf':
      bytes = await buildS20ManifestVerificationPdf(config);
      break;
    case 'buildS20PackingListVerificationPdf':
      bytes = await buildS20PackingListVerificationPdf(config);
      break;
    case 'buildS20PalletLabelVerificationPdf':
      bytes = await buildS20PalletLabelVerificationPdf(config);
      break;
    case 'buildS20PreventiveScheduleVerificationPdf':
      bytes = await buildS20PreventiveScheduleVerificationPdf(config);
      break;
    case 'buildS20ProfileMatrixVerificationPdf':
      bytes = await buildS20ProfileMatrixVerificationPdf(config);
      break;
    case 'buildS20ProofOfDeliveryVerificationPdf':
      bytes = await buildS20ProofOfDeliveryVerificationPdf(config);
      break;
    case 'buildS20ServiceCompletionVerificationPdf':
      bytes = await buildS20ServiceCompletionVerificationPdf(config);
      break;
    case 'buildS20ServiceHistoryVerificationPdf':
      bytes = await buildS20ServiceHistoryVerificationPdf(config);
      break;
    case 'buildS20ServiceOrderVerificationPdf':
      bytes = await buildS20ServiceOrderVerificationPdf(config);
      break;
    case 'buildS20ShipmentVerificationPdf':
      bytes = await buildS20ShipmentVerificationPdf(config);
      break;
    case 'buildS20ShippingLabelVerificationPdf':
      bytes = await buildS20ShippingLabelVerificationPdf(config);
      break;
    case 'buildS20SparePartsVerificationPdf':
      bytes = await buildS20SparePartsVerificationPdf(config);
      break;
    case 'buildS20TechnicianReportVerificationPdf':
      bytes = await buildS20TechnicianReportVerificationPdf(config);
      break;
    case 'buildS20TripReportVerificationPdf':
      bytes = await buildS20TripReportVerificationPdf(config);
      break;
    case 'buildS20TripSheetVerificationPdf':
      bytes = await buildS20TripSheetVerificationPdf(config);
      break;
    case 'buildS20WarrantyVerificationPdf':
      bytes = await buildS20WarrantyVerificationPdf(config);
      break;
    case 'buildS20WaybillVerificationPdf':
      bytes = await buildS20WaybillVerificationPdf(config);
      break;
    case 'buildS21ActivityVerificationPdf':
      bytes = await buildS21ActivityVerificationPdf(config);
      break;
    case 'buildS21CallVerificationPdf':
      bytes = await buildS21CallVerificationPdf(config);
      break;
    case 'buildS21ContractVerificationPdf':
      bytes = await buildS21ContractVerificationPdf(config);
      break;
    case 'buildS21CustomerVerificationPdf':
      bytes = await buildS21CustomerVerificationPdf(config);
      break;
    case 'buildS21HistoryVerificationPdf':
      bytes = await buildS21HistoryVerificationPdf(config);
      break;
    case 'buildS21LeadVerificationPdf':
      bytes = await buildS21LeadVerificationPdf(config);
      break;
    case 'buildS21OpportunityVerificationPdf':
      bytes = await buildS21OpportunityVerificationPdf(config);
      break;
    case 'buildS21PipelineVerificationPdf':
      bytes = await buildS21PipelineVerificationPdf(config);
      break;
    case 'buildS21PresentationVerificationPdf':
      bytes = await buildS21PresentationVerificationPdf(config);
      break;
    case 'buildS21ProposalVerificationPdf':
      bytes = await buildS21ProposalVerificationPdf(config);
      break;
    case 'buildS21VisitVerificationPdf':
      bytes = await buildS21VisitVerificationPdf(config);
      break;
    case 'buildS26ConstructionVerificationPdf':
      bytes = await buildS26ConstructionVerificationPdf(config);
      break;
    case 'buildS26HealthcareEducationVerificationPdf':
      bytes = await buildS26HealthcareEducationVerificationPdf(config);
      break;
    case 'buildS26MobilityDistributionHospitalityVerificationPdf':
      bytes = await buildS26MobilityDistributionHospitalityVerificationPdf(config);
      break;
    case 'buildS26RestaurantVerificationPdf':
      bytes = await buildS26RestaurantVerificationPdf(config);
      break;
    case 'buildS26RetailVerificationPdf':
      bytes = await buildS26RetailVerificationPdf(config);
      break;
    default:
      throw ArgumentError.value(
        apiName,
        'apiName',
        'Unsupported Business Templates verification example',
      );
  }

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates a Business Templates verification document outside the UI isolate.
Future<Uint8List> generateBusinessVerificationInBackground({
  required String apiName,
  required bool isRtl,
}) async {
  final config = geniusPdfConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'apiName': apiName,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _worker(message),
    debugName: 'business-verification-$apiName',
  );
  return transferred.materialize().asUint8List();
}
