// Generated by migrate_modern_vouchers_printing_security_to_global_manager.py
// Background dispatcher for Security S23 PDF examples.

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

import 'package:genius_pdf_example/features/security/models/documents/s23_compliance_archive_verification_documents.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _worker(Map<String, Object?> message) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final apiName = message['apiName']! as String;

  final Uint8List bytes = switch (apiName) {
    'buildS23ArchiveMetadataVerificationPdf' => await buildS23ArchiveMetadataVerificationPdf(config),
    'buildS23CopyVerificationPdf' => await buildS23CopyVerificationPdf(config),
    'buildS23CountryTenantFallbackVerificationPdf' => await buildS23CountryTenantFallbackVerificationPdf(config),
    'buildS23MissingRequiredFieldVerificationPdf' => await buildS23MissingRequiredFieldVerificationPdf(config),
    'buildS23OriginalVerificationPdf' => await buildS23OriginalVerificationPdf(config),
    'buildS23ReprintVerificationPdf' => await buildS23ReprintVerificationPdf(config),
    'buildS23SecurityPolicyVerificationPdf' => await buildS23SecurityPolicyVerificationPdf(config),
    _ => throw ArgumentError.value(
        apiName,
        'apiName',
        'Unsupported Security S23 background example',
      ),
  };

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Runs one Security S23 document generator outside the UI isolate.
Future<Uint8List> generateSecurityVerificationInBackground({
  required String apiName,
  required bool isRtl,
  required GeniusPdfConfig rootConfig,
}) async {
  final config = rootConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'apiName': apiName,
  };

  final result = await Isolate.run<TransferableTypedData>(
    () => _worker(message),
    debugName: 'security-s23-$apiName',
  );
  return result.materialize().asUint8List();
}
