// Generated by migrate_modern_vouchers_printing_security_to_global_manager.py
// Isolate-safe implementation of the focused Security PDF examples.
//
// Generation code is derived from SecuritySingleExampleHost so the migration
// preserves the examples' current security/watermark/signature behavior while
// moving document construction off the UI isolate.

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

final class _SecurityWorkerGenerator {
  const _SecurityWorkerGenerator(this.config);

  final GeniusPdfConfig config;

  Future<Uint8List> generate(String exampleName) {
    final generator = this;
    return switch (exampleName) {
    'confidentialWatermark' => generator._generateConfidentialWatermarkPdf(),
    'draftWatermark' => generator._generateDraftWatermarkPdf(),
    'copyWatermark' => generator._generateCopyWatermarkPdf(),
    'tiledWatermark' => generator._generateTiledWatermarkPdf(),
    'customWatermark' => generator._generateCustomWatermarkPdf(),
    'passwordProtection' => generator._generatePasswordProtectedPdf(),
    'readOnlyProtection' => generator._generateReadOnlyPdf(),
    'printOnlyProtection' => generator._generatePrintOnlyPdf(),
    'fullProtection' => generator._generateFullProtectionPdf(),
    'aes256Encryption' => generator._generateAes256EncryptedPdf(),
    'visualSignature' => generator._generateVisualSignaturePdf(),
    'detailedSignature' => generator._generateDetailedSignaturePdf(),
    'multipleSignatures' => generator._generateMultipleSignaturesPdf(),
    'customPositionSignature' => generator._generateCustomPositionSignaturePdf(),
    'comprehensiveSecurity' => generator._generateComprehensiveDemo(),
      _ => throw ArgumentError.value(
          exampleName,
          'exampleName',
          'Unsupported Security background example',
        ),
    };
  }

  Future<Uint8List> _generateConfidentialWatermarkPdf() async {
    const type = 'confidential';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Watermark Demo - ${type.toUpperCase()}');

              document.addWatermark(GeniusPdfWatermark.confidential(
                    config: config,
                  ));

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateDraftWatermarkPdf() async {
    const type = 'draft';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Watermark Demo - ${type.toUpperCase()}');

              document.addWatermark(GeniusPdfWatermark.draft(
                    config: config,
                  ));

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateCopyWatermarkPdf() async {
    const type = 'copy';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Watermark Demo - ${type.toUpperCase()}');

              document.addWatermark(GeniusPdfWatermark.copy(
                    config: config,
                  ));

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateTiledWatermarkPdf() async {
    const type = 'tiled';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Watermark Demo - ${type.toUpperCase()}');

              GeniusPdfWatermark.tiled(
                    config: config,
                    GeniusTiledWatermarkSettings(
                      text: 'SAMPLE',
                      fontSize: 20,
                      color: const Color(0xFF808080),
                      opacity: 0.1,
                      horizontalSpacing: 100,
                      verticalSpacing: 80,
                    ),
                  ).applyToDocument(document);

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateCustomWatermarkPdf() async {
    const type = 'custom';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Watermark Demo - ${type.toUpperCase()}');

              GeniusPdfWatermark.text(
                    config: config,
                    GeniusTextWatermarkSettings(
                      text: 'GENIUS LINK',
                      fontSize: 50,
                      color: const Color(0xFF2196F3),
                      opacity: 0.15,
                      rotation: -30,
                      isBold: true,
                    ),
                  ).applyToDocument(document);

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generatePasswordProtectedPdf() async {
    const type = 'password';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Encrypted Document - ${type.toUpperCase()}');

        final infoFont = config.baseFont;
        String encryptionInfo = '';

              document.protectWithPassword(password: 'demo123');
                  encryptionInfo =
                      'Password: demo123\nEncryption: AES-256\nPermissions: All';

        graphics.drawRectangle(
          brush: PdfSolidBrush(PdfColor(255, 255, 200)),
          pen: PdfPen(PdfColor(200, 200, 0)),
          bounds: Rect.fromLTWH(50, 200, pageSize.width - 100, 100),
        );
        graphics.drawString(
          'Encryption Details:\n$encryptionInfo',
          infoFont,
          brush: PdfSolidBrush(PdfColor(0, 0, 0)),
          bounds: Rect.fromLTWH(60, 210, pageSize.width - 120, 80),
          format: PdfStringFormat(textDirection: config.pdfTextDirection),
        );

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateReadOnlyPdf() async {
    const type = 'readonly';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Encrypted Document - ${type.toUpperCase()}');

        final infoFont = config.baseFont;
        String encryptionInfo = '';

              GeniusPdfSecurityService.applySecurity(
                    document,
                    GeniusPdfSecuritySettings.readOnly(ownerPassword: 'admin123'),
                  );
                  encryptionInfo =
                      'Owner Password: admin123\nPermissions: Read & Print Only';

        graphics.drawRectangle(
          brush: PdfSolidBrush(PdfColor(255, 255, 200)),
          pen: PdfPen(PdfColor(200, 200, 0)),
          bounds: Rect.fromLTWH(50, 200, pageSize.width - 100, 100),
        );
        graphics.drawString(
          'Encryption Details:\n$encryptionInfo',
          infoFont,
          brush: PdfSolidBrush(PdfColor(0, 0, 0)),
          bounds: Rect.fromLTWH(60, 210, pageSize.width - 120, 80),
          format: PdfStringFormat(textDirection: config.pdfTextDirection),
        );

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generatePrintOnlyPdf() async {
    const type = 'printonly';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Encrypted Document - ${type.toUpperCase()}');

        final infoFont = config.baseFont;
        String encryptionInfo = '';

              GeniusPdfSecurityService.applySecurity(
                    document,
                    GeniusPdfSecuritySettings.printOnly(ownerPassword: 'admin123'),
                  );
                  encryptionInfo = 'Owner Password: admin123\nPermissions: Print Only';

        graphics.drawRectangle(
          brush: PdfSolidBrush(PdfColor(255, 255, 200)),
          pen: PdfPen(PdfColor(200, 200, 0)),
          bounds: Rect.fromLTWH(50, 200, pageSize.width - 100, 100),
        );
        graphics.drawString(
          'Encryption Details:\n$encryptionInfo',
          infoFont,
          brush: PdfSolidBrush(PdfColor(0, 0, 0)),
          bounds: Rect.fromLTWH(60, 210, pageSize.width - 120, 80),
          format: PdfStringFormat(textDirection: config.pdfTextDirection),
        );

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateFullProtectionPdf() async {
    const type = 'full';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Encrypted Document - ${type.toUpperCase()}');

        final infoFont = config.baseFont;
        String encryptionInfo = '';

              GeniusPdfSecurityService.applySecurity(
                    document,
                    GeniusPdfSecuritySettings.fullProtection(
                      userPassword: 'user123',
                      ownerPassword: 'admin123',
                    ),
                  );
                  encryptionInfo =
                      'User Password: user123\nOwner Password: admin123\nPermissions: None';

        graphics.drawRectangle(
          brush: PdfSolidBrush(PdfColor(255, 255, 200)),
          pen: PdfPen(PdfColor(200, 200, 0)),
          bounds: Rect.fromLTWH(50, 200, pageSize.width - 100, 100),
        );
        graphics.drawString(
          'Encryption Details:\n$encryptionInfo',
          infoFont,
          brush: PdfSolidBrush(PdfColor(0, 0, 0)),
          bounds: Rect.fromLTWH(60, 210, pageSize.width - 120, 80),
          format: PdfStringFormat(textDirection: config.pdfTextDirection),
        );

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateAes256EncryptedPdf() async {
    const type = 'aes256';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Encrypted Document - ${type.toUpperCase()}');

        final infoFont = config.baseFont;
        String encryptionInfo = '';

              GeniusPdfSecurityService.applySecurity(
                    document,
                    GeniusPdfSecuritySettings(
                      userPassword: 'secure123',
                      ownerPassword: 'admin123',
                      encryptionLevel: GeniusPdfEncryptionLevel.aes256,
                      permissions: GeniusPdfPermissions.readOnly(),
                      encryptMetadata: true,
                    ),
                  );
                  encryptionInfo =
                      'User Password: secure123\nOwner Password: admin123\nEncryption: AES-256 Bit';

        graphics.drawRectangle(
          brush: PdfSolidBrush(PdfColor(255, 255, 200)),
          pen: PdfPen(PdfColor(200, 200, 0)),
          bounds: Rect.fromLTWH(50, 200, pageSize.width - 100, 100),
        );
        graphics.drawString(
          'Encryption Details:\n$encryptionInfo',
          infoFont,
          brush: PdfSolidBrush(PdfColor(0, 0, 0)),
          bounds: Rect.fromLTWH(60, 210, pageSize.width - 120, 80),
          format: PdfStringFormat(textDirection: config.pdfTextDirection),
        );

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateVisualSignaturePdf() async {
    const type = 'visual';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Signed Document - ${type.toUpperCase()}');

              final signature = GeniusPdfDigitalSignature(
                    config: config,
                    settings: GeniusDigitalSignatureSettings(
                      signerName: 'John Doe',
                      pageNumber: 0,
                    ),
                  );
                  signature.drawOnPage(page);

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateDetailedSignaturePdf() async {
    const type = 'detailed';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Signed Document - ${type.toUpperCase()}');

              final signature = GeniusPdfDigitalSignature(
                    config: config,
                    settings: GeniusDigitalSignatureSettings(
                      signerName: 'Jane Smith',
                      reason: 'Document Review and Approval',
                      location: 'Riyadh, Saudi Arabia',
                      contactInfo: 'jane.smith@company.com',
                      appearance: const GeniusSignatureAppearance(
                        showName: true,
                        showDate: true,
                        showReason: true,
                        showLocation: true,
                      ),
                      pageNumber: 0,
                    ),
                  );
                  signature.drawOnPage(page);

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateMultipleSignaturesPdf() async {
    const type = 'multiple';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Signed Document - ${type.toUpperCase()}');

              final sig1 = GeniusPdfDigitalSignature(
                    config: config,
                    settings: GeniusDigitalSignatureSettings(
                      signerName: 'Reviewer 1',
                      reason: 'Technical Review',
                      bounds: Rect.fromLTWH(50, pageSize.height - 130, 180, 90),
                      pageNumber: 0,
                    ),
                  );
                  sig1.drawOnPage(
                      page, Rect.fromLTWH(50, pageSize.height - 130, 180, 90));

                  final sig2 = GeniusPdfDigitalSignature(
                    config: config,
                    settings: GeniusDigitalSignatureSettings(
                      signerName: 'Reviewer 2',
                      reason: 'Management Approval',
                      bounds: Rect.fromLTWH(
                          pageSize.width - 230, pageSize.height - 130, 180, 90),
                      pageNumber: 0,
                    ),
                  );
                  sig2.drawOnPage(
                      page,
                      Rect.fromLTWH(
                          pageSize.width - 230, pageSize.height - 130, 180, 90));

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateCustomPositionSignaturePdf() async {
    const type = 'custom';

        final document = PdfDocument();
        final page = document.pages.add();
        final graphics = page.graphics;
        final pageSize = page.getClientSize();

        _addSampleContent(
            graphics, pageSize, 'Signed Document - ${type.toUpperCase()}');

              final signature = GeniusPdfDigitalSignature(
                    config: config,
                    settings: GeniusDigitalSignatureSettings(
                      signerName: 'CEO Signature',
                      reason: 'Final Approval',
                      location: 'Head Office',
                      appearance: GeniusSignatureAppearance(
                        showName: true,
                        showDate: true,
                        showReason: true,
                        showLocation: true,
                        backgroundColor: const Color(0xFFE8F5E9),
                        borderColor: const Color(0xFF4CAF50),
                        textColor: const Color(0xFF1B5E20),
                      ),
                      bounds: Rect.fromLTWH(pageSize.width / 2 - 100, 300, 200, 100),
                      pageNumber: 0,
                    ),
                  );
                  signature.drawOnPage(
                      page, Rect.fromLTWH(pageSize.width / 2 - 100, 300, 200, 100));

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  Future<Uint8List> _generateComprehensiveDemo() async {

        final document = PdfDocument();

        final page1 = document.pages.add();
        _addSampleContent(
            page1.graphics, page1.getClientSize(), 'Page 1: Watermark Demo');

        final page2 = document.pages.add();
        _addSampleContent(
            page2.graphics, page2.getClientSize(), 'Page 2: Tiled Watermark');

        final page3 = document.pages.add();

        GeniusPdfWatermark.text(
          config: config,
          GeniusTextWatermarkSettings.confidential(opacity: 0.15),
        ).applyToPage(page1);

        GeniusPdfWatermark.tiled(
          config: config,
          GeniusTiledWatermarkSettings(
            text: 'SAMPLE',
            fontSize: 18,
            opacity: 0.08,
          ),
        ).applyToPage(page2);

        final signature = GeniusPdfDigitalSignature(
          config: config,
          settings: GeniusDigitalSignatureSettings(
            signerName: 'Document Admin',
            reason: 'Comprehensive Demo',
            location: 'Demo Location',
            appearance: const GeniusSignatureAppearance(
              showName: true,
              showDate: true,
              showReason: true,
              showLocation: true,
            ),
            pageNumber: 2,
          ),
        );
        signature.drawOnPage(page3);

        document.protectWithPassword(
          password: 'demo123',
          permissions: GeniusPdfPermissions.printOnly(),
        );

    try {
      return Uint8List.fromList(await document.save());
    } finally {
      document.dispose();
    }
  }

  void _addSampleContent(PdfGraphics graphics, Size pageSize, String title) {
      graphics.drawString(
        title,
        config.baseFont,
        brush: PdfSolidBrush(PdfColor(0, 0, 0)),
        bounds: Rect.fromLTWH(50, 50, pageSize.width - 100, 40),
        format: PdfStringFormat(
          alignment: PdfTextAlignment.center,
          textDirection: config.pdfTextDirection,
        ),
      );

      const sampleText = '''
  This is a sample document demonstrating the security features of the Genius Link PDF Generator library.

  The library provides comprehensive security features including:
  • Text, diagonal, and tiled watermarks
  • Password protection with AES-256 encryption
  • Granular permission controls
  • Digital signatures with customizable appearance

  This document was generated to showcase these features in action.
  ''';

      graphics.drawString(
        sampleText,
        config.boldFont,
        brush: PdfSolidBrush(PdfColor(50, 50, 50)),
        bounds: Rect.fromLTWH(50, 120, pageSize.width - 100, 200),
        format: PdfStringFormat(textDirection: config.pdfTextDirection),
      );

      _drawSampleTable(
          graphics, Rect.fromLTWH(50, 350, pageSize.width - 100, 150));
    }

  void _drawSampleTable(PdfGraphics graphics, Rect bounds) {
      const columns = ['Feature', 'Status', 'Description'];
      final rows = [
        ['Watermarks', 'Active', 'Text & pattern watermarks'],
        ['Encryption', 'AES-256', 'High-grade encryption'],
        ['Permissions', 'Configured', 'Custom access control'],
        ['Signatures', 'Supported', 'Digital signing'],
      ];

      final cellWidth = bounds.width / 3;
      const cellHeight = 25.0;

      graphics.drawRectangle(
        brush: PdfSolidBrush(PdfColor(41, 128, 185)),
        bounds: Rect.fromLTWH(bounds.left, bounds.top, bounds.width, cellHeight),
      );

      for (int i = 0; i < columns.length; i++) {
        graphics.drawString(
          columns[i],
          config.boldFont,
          brush: PdfSolidBrush(PdfColor(255, 255, 255)),
          bounds: Rect.fromLTWH(bounds.left + i * cellWidth + 5, bounds.top + 5,
              cellWidth - 10, cellHeight - 10),
          format: PdfStringFormat(textDirection: config.pdfTextDirection),
        );
      }

      for (int r = 0; r < rows.length; r++) {
        final y = bounds.top + cellHeight * (r + 1);
        final bgColor =
            r % 2 == 0 ? PdfColor(248, 249, 250) : PdfColor(255, 255, 255);

        graphics.drawRectangle(
          brush: PdfSolidBrush(bgColor),
          pen: PdfPen(PdfColor(220, 220, 220)),
          bounds: Rect.fromLTWH(bounds.left, y, bounds.width, cellHeight),
        );

        for (int c = 0; c < rows[r].length; c++) {
          graphics.drawString(
            rows[r][c],
            config.baseFont,
            brush: PdfSolidBrush(PdfColor(50, 50, 50)),
            bounds: Rect.fromLTWH(bounds.left + c * cellWidth + 5, y + 5,
                cellWidth - 10, cellHeight - 10),
            format: PdfStringFormat(textDirection: config.pdfTextDirection),
          );
        }
      }
    }
}

Future<TransferableTypedData> _securityWorker(
  Map<String, Object?> message,
) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final bytes = await _SecurityWorkerGenerator(config).generate(
    message['exampleName']! as String,
  );
  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates one focused Security example outside the UI isolate.
Future<Uint8List> generateSecurityExampleInBackground({
  required String exampleName,
  required GeniusPdfConfig config,
}) async {
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'exampleName': exampleName,
  };
  final result = await Isolate.run<TransferableTypedData>(
    () => _securityWorker(message),
    debugName: 'security-$exampleName',
  );
  return result.materialize().asUint8List();
}
