// Generated by migrate_barcode_business_components_to_global_manager.py
//
// Isolate-safe dispatcher for Components verification examples.

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';
import 'package:genius_pdf_example/features/components/models/documents/s02_components_rtl_verification_documents.dart';
import 'package:genius_pdf_example/features/components/models/documents/s07_erp_components_verification_documents.dart';

Future<TransferableTypedData> _worker(Map<String, Object?> message) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final apiName = message['apiName']! as String;

  late final Uint8List bytes;
  switch (apiName) {
    case 'buildS02DataGridVerificationPdf':
      bytes = await buildS02DataGridVerificationPdf(config);
      break;
    case 'buildS02InfoBoxVerificationPdf':
      bytes = await buildS02InfoBoxVerificationPdf(config);
      break;
    case 'buildS02LongMultiPageVerificationPdf':
      bytes = await buildS02LongMultiPageVerificationPdf(config);
      break;
    case 'buildS02MatrixVerificationPdf':
      bytes = await buildS02MatrixVerificationPdf(config);
      break;
    case 'buildS02MediaVerificationPdf':
      bytes = await buildS02MediaVerificationPdf(config);
      break;
    case 'buildS02NestedOverrideVerificationPdf':
      bytes = await buildS02NestedOverrideVerificationPdf(config);
      break;
    case 'buildS02ReportHeaderVerificationPdf':
      bytes = await buildS02ReportHeaderVerificationPdf(config);
      break;
    case 'buildS02RichTextVerificationPdf':
      bytes = await buildS02RichTextVerificationPdf(config);
      break;
    case 'buildS02SummaryVerificationPdf':
      bytes = await buildS02SummaryVerificationPdf(config);
      break;
    case 'buildS07BilingualVerificationPdf':
      bytes = await buildS07BilingualVerificationPdf(config);
      break;
    case 'buildS07CompositionVerificationPdf':
      bytes = await buildS07CompositionVerificationPdf(config);
      break;
    case 'buildS07EmptyStateVerificationPdf':
      bytes = await buildS07EmptyStateVerificationPdf(config);
      break;
    case 'buildS07FinancialVerificationPdf':
      bytes = await buildS07FinancialVerificationPdf(config);
      break;
    case 'buildS07IdentityPartyVerificationPdf':
      bytes = await buildS07IdentityPartyVerificationPdf(config);
      break;
    case 'buildS07LongMultiPageVerificationPdf':
      bytes = await buildS07LongMultiPageVerificationPdf(config);
      break;
    case 'buildS07NullCollapseVerificationPdf':
      bytes = await buildS07NullCollapseVerificationPdf(config);
      break;
    case 'buildS07OperationalVerificationPdf':
      bytes = await buildS07OperationalVerificationPdf(config);
      break;
    default:
      throw ArgumentError.value(
        apiName,
        'apiName',
        'Unsupported Components verification example',
      );
  }

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates a Components verification document outside the UI isolate.
Future<Uint8List> generateComponentsVerificationInBackground({
  required String apiName,
  required bool isRtl,
}) async {
  final config = geniusPdfConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'apiName': apiName,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _worker(message),
    debugName: 'components-verification-$apiName',
  );
  return transferred.materialize().asUint8List();
}
