// Generated by migrate_barcode_business_components_to_global_manager.py
//
// Isolate-safe focused Component example generation.

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/features/components/models/documents/components_demo_documents.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _componentWorker(
  Map<String, Object?> message,
) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final bytes = await buildComponentDemoBytes(
    component: message['componentId']! as String,
    config: config,
  );
  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates one focused Component example outside the UI isolate.
Future<Uint8List> generateComponentExampleInBackground({
  required String componentId,
  required bool isRtl,
}) async {
  final config = geniusPdfConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'componentId': componentId,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _componentWorker(message),
    debugName: 'component-$componentId',
  );
  return transferred.materialize().asUint8List();
}
