// Generated by use_global_manager_toasts_in_showcase_tables_template_engine.py
//
// Sendable GeniusPdfConfig snapshot helpers for example-app background isolates.

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show Size, TextDirection;
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

/// Captures the parts of [GeniusPdfConfig] required by example generators.
///
/// Font and branding bytes are moved with [TransferableTypedData] so large
/// assets are not repeatedly copied between the root isolate and worker.
Map<String, Object?> captureExamplePdfConfig(GeniusPdfConfig config) {
  final assets = config.assetsOrNull;

  TransferableTypedData transfer(Uint8List bytes) =>
      TransferableTypedData.fromList(<Uint8List>[bytes]);

  return <String, Object?>{
    'baseFont': transfer(config.baseFontBytes),
    'boldFont':
        config.boldFontBytes == null ? null : transfer(config.boldFontBytes!),
    'headerFont':
        config.headerFontBytes == null ? null : transfer(config.headerFontBytes!),
    'smallFont':
        config.smallFontBytes == null ? null : transfer(config.smallFontBytes!),
    'baseFontSize': config.baseFontSize,
    'boldFontSize': config.boldFontSize,
    'headerFontSize': config.headerFontSize,
    'smallFontSize': config.smallFontSize,
    'pageWidth': config.pageSize.width,
    'pageHeight': config.pageSize.height,
    'marginLeft': config.margins.left,
    'marginTop': config.margins.top,
    'marginRight': config.margins.right,
    'marginBottom': config.margins.bottom,
    'isRtl': config.textDirection == TextDirection.rtl,
    if (assets != null) ...<String, Object?>{
      'assetPrimaryFont': transfer(assets.primaryFont),
      'assetSecondaryFont': assets.secondaryFont == null
          ? null
          : transfer(assets.secondaryFont!),
      'assetHeaderImage':
          assets.headerImage == null ? null : transfer(assets.headerImage!),
      'assetLogo': assets.logo == null ? null : transfer(assets.logo!),
      'assetSquareLogo':
          assets.squareLogo == null ? null : transfer(assets.squareLogo!),
      'assetBackgroundImage': assets.backgroundImage == null
          ? null
          : transfer(assets.backgroundImage!),
      'assetLabelImage':
          assets.labelImage == null ? null : transfer(assets.labelImage!),
    },
  };
}

Uint8List? _materialize(Object? value) {
  if (value == null) return null;
  return (value as TransferableTypedData).materialize().asUint8List();
}

/// Rebuilds an isolate-local configuration from [captureExamplePdfConfig].
GeniusPdfConfig restoreExamplePdfConfig(Map<String, Object?> message) {
  final primaryAsset = _materialize(message['assetPrimaryFont']);
  final margins = PdfMargins()
    ..left = (message['marginLeft']! as num).toDouble()
    ..top = (message['marginTop']! as num).toDouble()
    ..right = (message['marginRight']! as num).toDouble()
    ..bottom = (message['marginBottom']! as num).toDouble();

  return GeniusPdfConfig.createSync(
    baseFontBytes: _materialize(message['baseFont'])!,
    boldFontBytes: _materialize(message['boldFont']),
    headerFontBytes: _materialize(message['headerFont']),
    smallFontBytes: _materialize(message['smallFont']),
    baseFontSize: (message['baseFontSize']! as num).toDouble(),
    boldFontSize: (message['boldFontSize']! as num).toDouble(),
    headerFontSize: (message['headerFontSize']! as num).toDouble(),
    smallFontSize: (message['smallFontSize']! as num).toDouble(),
    pageSize: Size(
      (message['pageWidth']! as num).toDouble(),
      (message['pageHeight']! as num).toDouble(),
    ),
    textDirection:
        message['isRtl']! as bool ? TextDirection.rtl : TextDirection.ltr,
    margins: margins,
    assetData: primaryAsset == null
        ? null
        : GeniusPdfAssetsData(
            primaryFont: primaryAsset,
            secondaryFont: _materialize(message['assetSecondaryFont']),
            headerImage: _materialize(message['assetHeaderImage']),
            logo: _materialize(message['assetLogo']),
            squareLogo: _materialize(message['assetSquareLogo']),
            backgroundImage: _materialize(message['assetBackgroundImage']),
            labelImage: _materialize(message['assetLabelImage']),
          ),
  );
}
