// Generated by migrate_text_getting_architecture_sharing_custom_report_configuration_to_global_manager.py

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/features/configuration/models/documents/s05_formatting_theme_verification_documents.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _worker(Map<String, Object?> message) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final apiName = message['apiName']! as String;

  final Uint8List bytes = switch (apiName) {
    'buildS05AccountingVerificationPdf' => await buildS05AccountingVerificationPdf(config),
    'buildS05ArabicDigitsVerificationPdf' => await buildS05ArabicDigitsVerificationPdf(config),
    'buildS05ConsistencyVerificationPdf' => await buildS05ConsistencyVerificationPdf(config),
    'buildS05CurrenciesVerificationPdf' => await buildS05CurrenciesVerificationPdf(config),
    'buildS05LongMultiPageVerificationPdf' => await buildS05LongMultiPageVerificationPdf(config),
    'buildS05NullsUnitsExchangeVerificationPdf' => await buildS05NullsUnitsExchangeVerificationPdf(config),
    'buildS05PrecisionVerificationPdf' => await buildS05PrecisionVerificationPdf(config),
    'buildS05ThemeTokensVerificationPdf' => await buildS05ThemeTokensVerificationPdf(config),
    _ => throw ArgumentError.value(
        apiName,
        'apiName',
        'Unsupported configuration verification example',
      ),
  };

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates one configuration verification PDF outside the UI isolate.
Future<Uint8List> generateConfigurationVerificationInBackground({
  required String apiName,
  required bool isRtl,
}) async {
  final config = geniusPdfConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'apiName': apiName,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _worker(message),
    debugName: 'configuration-$apiName',
  );
  return transferred.materialize().asUint8List();
}
