// Generated by migrate_text_getting_architecture_sharing_custom_report_configuration_to_global_manager.py

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';

import 'package:genius_pdf_example/features/text_typography/models/documents/s01_directionality_verification_documents.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _worker(Map<String, Object?> message) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final apiName = message['apiName']! as String;

  final Uint8List bytes = switch (apiName) {
    'buildS01AutoInheritanceVerificationPdf' => await buildS01AutoInheritanceVerificationPdf(config),
    'buildS01LegacyTemplateJsonVerificationPdf' => await buildS01LegacyTemplateJsonVerificationPdf(config),
    'buildS01LogicalGeometryVerificationPdf' => await buildS01LogicalGeometryVerificationPdf(config),
    'buildS01LongMultiPageVerificationPdf' => await buildS01LongMultiPageVerificationPdf(config),
    'buildS01MediaPolicyVerificationPdf' => await buildS01MediaPolicyVerificationPdf(config),
    'buildS01MixedTextVerificationPdf' => await buildS01MixedTextVerificationPdf(config),
    'buildS01NestedOverridesVerificationPdf' => await buildS01NestedOverridesVerificationPdf(config),
    'buildS01PrecedenceVerificationPdf' => await buildS01PrecedenceVerificationPdf(config),
    'buildS01ValueMatrixVerificationPdf' => await buildS01ValueMatrixVerificationPdf(config),
    _ => throw ArgumentError.value(
        apiName,
        'apiName',
        'Unsupported text_typography verification example',
      ),
  };

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates one text_typography verification PDF outside the UI isolate.
Future<Uint8List> generateTextTypographyVerificationInBackground({
  required String apiName,
  required bool isRtl,
}) async {
  final config = geniusPdfConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'apiName': apiName,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _worker(message),
    debugName: 'text-typography-$apiName',
  );
  return transferred.materialize().asUint8List();
}
