// Generated by migrate_barcode_business_components_to_global_manager.py
//
// Isolate-safe Barcode / QR demo generation.

import 'dart:isolate';
import 'dart:typed_data';
import 'dart:ui' show Color, Rect;

import 'package:flutter/material.dart' show TextDirection;
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

enum BarcodeBackgroundDocumentKind { oneDimensional, qrCodes, allInOne }

Future<TransferableTypedData> _barcodeWorker(
  Map<String, Object?> message,
) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final kind = BarcodeBackgroundDocumentKind.values.byName(
    message['kind']! as String,
  );
  final isRtl = message['isRtl']! as bool;

  final document = PdfDocument();
  try {
    switch (kind) {
      case BarcodeBackgroundDocumentKind.oneDimensional:
        _build1D(document, config, isRtl);
        break;
      case BarcodeBackgroundDocumentKind.qrCodes:
        _buildQr(document, config, isRtl);
        break;
      case BarcodeBackgroundDocumentKind.allInOne:
        _buildAll(document, config, isRtl);
        break;
    }

    final bytes = Uint8List.fromList(await document.save());
    return TransferableTypedData.fromList(<Uint8List>[bytes]);
  } finally {
    document.dispose();
  }
}

void _drawTitle({
  required PdfPage page,
  required GeniusPdfConfig config,
  required bool isRtl,
  required String en,
  required String ar,
  double fontSize = 18,
  double top = 20,
  double height = 30,
}) {
  final pageSize = page.getClientSize();
  final font = PdfTrueTypeFont(config.assets.primaryFont.toList(), fontSize);
  page.graphics.drawString(
    isRtl ? ar : en,
    font,
    brush: PdfSolidBrush(PdfColor(33, 150, 243)),
    bounds: Rect.fromLTWH(20, top, pageSize.width - 40, height),
    format: PdfStringFormat(
      alignment: PdfTextAlignment.center,
      textDirection:
          isRtl ? PdfTextDirection.rightToLeft : PdfTextDirection.leftToRight,
    ),
  );
}

void _build1D(PdfDocument document, GeniusPdfConfig config, bool isRtl) {
  final page = document.pages.add();
  final pageSize = page.getClientSize();
  _drawTitle(
    page: page,
    config: config,
    isRtl: isRtl,
    en: '1D Barcodes Demo',
    ar: 'الرموز الشريطية 1D',
  );

  double y = 70;
  final ean13 = GeniusPdfBarcode.ean13(
    config: config,
    data: '5901234123457',
    caption: 'Product Code',
    captionAr: 'رمز المنتج',
    style: const GeniusPdfBarcodeStyle.retail(),
  );
  final first = ean13.draw(
    page: page,
    bounds: Rect.fromLTWH(20, y, pageSize.width - 40, 100),
  );
  y = first.bottom + 20;

  final code128 = GeniusPdfBarcode.code128(
    config: config,
    data: 'GENIUS-PDF-2025',
    caption: 'Reference Number',
    captionAr: 'الرقم المرجعي',
    style: const GeniusPdfBarcodeStyle.document(),
  );
  final second = code128.draw(
    page: page,
    bounds: Rect.fromLTWH(20, y, pageSize.width - 40, 100),
  );
  y = second.bottom + 20;

  GeniusPdfBarcode.shipping(
    config: config,
    data: '1Z999AA10123456784',
    trackingLabel: 'Tracking Number',
    trackingLabelAr: 'رقم التتبع',
  ).draw(
    page: page,
    bounds: Rect.fromLTWH(20, y, pageSize.width - 40, 110),
  );
}

void _buildQr(PdfDocument document, GeniusPdfConfig config, bool isRtl) {
  final page = document.pages.add();
  final pageSize = page.getClientSize();
  _drawTitle(
    page: page,
    config: config,
    isRtl: isRtl,
    en: 'QR Codes Demo',
    ar: 'رموز QR',
  );

  double y = 70;
  final halfWidth = (pageSize.width - 60) / 2;

  GeniusPdfQRCodeGenerator.url(
    config: config,
    url: 'https://github.com/GeniusSystems24',
    caption: 'Visit Website',
    captionAr: 'زيارة الموقع',
    style: const GeniusPdfQRCodeStyle(),
  ).draw(
    page: page,
    bounds: Rect.fromLTWH(20, y, halfWidth, 140),
  );

  GeniusPdfQRCodeGenerator.zatca(
    config: config,
    sellerName: 'شركة الأمل للتجارة',
    vatNumber: '300123456789003',
    timestamp: DateTime.now(),
    total: 34615,
    vatAmount: 4515,
    style: const GeniusPdfQRCodeStyle.invoice(),
  ).draw(
    page: page,
    bounds: Rect.fromLTWH(40 + halfWidth, y, halfWidth, 140),
  );

  y += 160;
  GeniusPdfQRCodeGenerator.wifi(
    config: config,
    ssid: 'GeniusOffice',
    password: 'Genius@2025',
    style: GeniusPdfQRCodeStyle.branded(
      primaryColor: const Color(0xFF4CAF50),
    ),
  ).draw(
    page: page,
    bounds: Rect.fromLTWH(20, y, halfWidth, 140),
  );

  GeniusPdfQRCodeGenerator.vCard(
    config: config,
    name: isRtl ? 'أحمد محمد' : 'Ahmed Mohammed',
    phone: '+966501234567',
    email: 'ahmed@example.com',
    company: isRtl ? 'شركة الأمل' : 'Al-Amal Co.',
    style: const GeniusPdfQRCodeStyle.payment(),
  ).draw(
    page: page,
    bounds: Rect.fromLTWH(40 + halfWidth, y, halfWidth, 140),
  );
}

void _buildAll(PdfDocument document, GeniusPdfConfig config, bool isRtl) {
  final page = document.pages.add();
  final pageSize = page.getClientSize();
  _drawTitle(
    page: page,
    config: config,
    isRtl: isRtl,
    en: 'Complete Barcode & QR Code Demo',
    ar: 'عرض شامل - الرموز الشريطية و QR',
    fontSize: 16,
    top: 15,
    height: 25,
  );

  final sectionFont = PdfTrueTypeFont(config.assets.primaryFont.toList(), 12);
  double y = 50;
  void section(String en, String ar) {
    page.graphics.drawString(
      isRtl ? ar : en,
      sectionFont,
      brush: PdfSolidBrush(PdfColor(100, 100, 100)),
      bounds: Rect.fromLTWH(20, y, pageSize.width - 40, 20),
      format: PdfStringFormat(
        alignment: PdfTextAlignment.center,
        textDirection: isRtl
            ? PdfTextDirection.rightToLeft
            : PdfTextDirection.leftToRight,
      ),
    );
    y += 25;
  }

  section('— 1D Barcodes —', '— الرموز الشريطية 1D —');
  final half = (pageSize.width - 60) / 2;
  final first = GeniusPdfBarcode.ean13(
    config: config,
    data: '5901234123457',
    caption: 'EAN-13',
    style: const GeniusPdfBarcodeStyle.compact(),
  ).draw(page: page, bounds: Rect.fromLTWH(20, y, half, 80));

  GeniusPdfBarcode.code128(
    config: config,
    data: 'GENIUS-2025',
    caption: 'Code 128',
    style: const GeniusPdfBarcodeStyle.compact(),
  ).draw(
    page: page,
    bounds: Rect.fromLTWH((pageSize.width + 20) / 2, y, half, 80),
  );

  y = first.bottom + 15;
  section('— QR Codes —', '— رموز QR —');
  final qrWidth = (pageSize.width - 80) / 3;

  GeniusPdfQRCodeGenerator.url(
    config: config,
    url: 'https://genius.systems',
    caption: 'URL',
    captionAr: 'رابط',
    style: const GeniusPdfQRCodeStyle.compact(),
  ).draw(page: page, bounds: Rect.fromLTWH(20, y, qrWidth, 90));

  GeniusPdfQRCodeGenerator.zatca(
    config: config,
    sellerName: 'شركة الأمل',
    vatNumber: '300123456789003',
    timestamp: DateTime.now(),
    total: 34615,
    vatAmount: 4515,
    style: const GeniusPdfQRCodeStyle.compact(),
  ).draw(
    page: page,
    bounds: Rect.fromLTWH(40 + qrWidth, y, qrWidth, 90),
  );

  GeniusPdfQRCodeGenerator.wifi(
    config: config,
    ssid: 'Office',
    password: 'pass123',
    style: const GeniusPdfQRCodeStyle.compact(),
  ).draw(
    page: page,
    bounds: Rect.fromLTWH(60 + qrWidth * 2, y, qrWidth, 90),
  );
}

/// Generates one Barcode/QR demo PDF on a worker isolate.
Future<Uint8List> generateBarcodeDocumentInBackground({
  required BarcodeBackgroundDocumentKind kind,
  required bool isRtl,
}) async {
  final config = geniusPdfConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'kind': kind.name,
    'isRtl': isRtl,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _barcodeWorker(message),
    debugName: 'barcode-${kind.name}',
  );
  return transferred.materialize().asUint8List();
}
