// Generated by use_global_manager_toasts_in_showcase_tables_template_engine.py

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/s10_family_merge_verification_documents.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/s22_engine_vnext_verification_documents.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/s25_template_designer_verification_documents.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_builtin_invoice.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_builtin_letter.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_builtin_report.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_contract.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_invoice.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_json_letter.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_json_memo.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_purchase_order.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_quotation.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_receipt.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_report.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_timesheet.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _verificationWorker(
  Map<String, Object?> message,
) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final apiName = message['apiName']! as String;
  final rowCount = message['rowCount'] as int? ?? 10;
  final profile = message['profile'] as String? ?? 'a4-portrait';
  final rows = message['rows'] as int? ?? 10;

  final Uint8List bytes = switch (apiName) {
    'buildS10FamilyAuditVerificationPdf' =>
      await buildS10FamilyAuditVerificationPdf(config),

    'buildS22SchemaVerificationPdf' =>
      await buildS22SchemaVerificationPdf(config, rowCount: rowCount),
    'buildS22LegacyMigrationVerificationPdf' =>
      await buildS22LegacyMigrationVerificationPdf(config, rowCount: rowCount),
    'buildS22ExpressionsVerificationPdf' =>
      await buildS22ExpressionsVerificationPdf(config, rowCount: rowCount),
    'buildS22LargeLoopVerificationPdf' =>
      await buildS22LargeLoopVerificationPdf(config, rowCount: rowCount),
    'buildS22CompositionVerificationPdf' =>
      await buildS22CompositionVerificationPdf(config, rowCount: rowCount),
    'buildS22ScopedRegistryVerificationPdf' =>
      await buildS22ScopedRegistryVerificationPdf(config, rowCount: rowCount),
    'buildS22DirectionalityVerificationPdf' =>
      await buildS22DirectionalityVerificationPdf(config, rowCount: rowCount),
    'buildS22InvalidExpressionVerificationPdf' =>
      await buildS22InvalidExpressionVerificationPdf(
        config,
        rowCount: rowCount,
      ),

    'buildS25MetadataVerificationPdf' =>
      await buildS25MetadataVerificationPdf(
        config,
        profile: profile,
        rows: rows,
      ),
    'buildS25AuthoringVerificationPdf' =>
      await buildS25AuthoringVerificationPdf(
        config,
        profile: profile,
        rows: rows,
      ),
    'buildS25ExpressionsVerificationPdf' =>
      await buildS25ExpressionsVerificationPdf(
        config,
        profile: profile,
        rows: rows,
      ),
    'buildS25ComponentsStylesVerificationPdf' =>
      await buildS25ComponentsStylesVerificationPdf(
        config,
        profile: profile,
        rows: rows,
      ),
    'buildS25ValidationVerificationPdf' =>
      await buildS25ValidationVerificationPdf(
        config,
        profile: profile,
        rows: rows,
      ),
    'buildS25MultiPageVerificationPdf' =>
      await buildS25MultiPageVerificationPdf(
        config,
        profile: profile,
        rows: rows,
      ),

    _ => throw ArgumentError.value(
        apiName,
        'apiName',
        'Unsupported template-engine verification example',
      ),
  };

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates one Template Engine verification PDF on a worker isolate.
Future<Uint8List> generateTemplateEngineVerificationInBackground({
  required String apiName,
  required bool isRtl,
  int? rowCount,
  String? profile,
  int? rows,
}) async {
  final config = geniusPdfConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'apiName': apiName,
    if (rowCount != null) 'rowCount': rowCount,
    if (profile != null) 'profile': profile,
    if (rows != null) 'rows': rows,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _verificationWorker(message),
    debugName: 'template-engine-$apiName',
  );
  return transferred.materialize().asUint8List();
}

Future<TransferableTypedData> _actionWorker(
  Map<String, Object?> message,
) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final actionId = message['actionId']! as String;

  final Uint8List bytes = switch (actionId) {
    'invoice' => (await buildTemplateInvoiceBytes(config)).bytes,
    'report' => (await buildTemplateReportBytes(config)).bytes,
    'purchase_order' => (await buildTemplatePurchaseOrderBytes(config)).bytes,
    'receipt' => (await buildTemplateReceiptBytes(config)).bytes,
    'quotation' => (await buildTemplateQuotationBytes(config)).bytes,
    'contract' => (await buildTemplateContractBytes(config)).bytes,
    'timesheet' => (await buildTemplateTimesheetBytes(config)).bytes,
    'json_letter' => (await buildTemplateFromJsonLetterBytes(config)).bytes,
    'json_memo' => (await buildTemplateFromJsonMemoBytes(config)).bytes,
    'builtin_invoice' => (await buildBuiltInInvoiceBytes(config)).bytes,
    'builtin_report' => (await buildBuiltInReportBytes(config)).bytes,
    'builtin_letter' => (await buildBuiltInLetterBytes(config)).bytes,
    _ => throw ArgumentError.value(
        actionId,
        'actionId',
        'Unsupported Template Engine document action',
      ),
  };

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates one of the legacy Template Engine demo actions in a worker isolate.
Future<Uint8List> generateTemplateEngineActionInBackground({
  required String actionId,
}) async {
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(geniusPdfConfig),
    'actionId': actionId,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _actionWorker(message),
    debugName: 'template-engine-action-$actionId',
  );
  return transferred.materialize().asUint8List();
}
