// GENERATED BY redesign_remaining_multi_example_screens.py
// Internal single-example host. Navigation never exposes a tabbed aggregate UI.

import 'package:flutter/material.dart';
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;
import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart'
    show geniusPdfConfig;
import 'package:genius_pdf_example/features/sharing/presentation/controllers/sharing_demo_controller.dart';

import 'package:genius_pdf_example/app/theme/app_theme.dart';

import 'package:genius_pdf_example/shared/presentation/widgets/feature_example_page.dart';

import 'package:genius_pdf_example/localizations/pdf_generator_localization.dart';
/// Demo screen for Sharing features (v2.3.x).
class SharingSingleExampleHost extends StatefulWidget {
  const SharingSingleExampleHost({
    super.key,
    this.initialTab = 0,
    this.controller,
  });

  final int initialTab;

  final SharingDemoController? controller;

  @override
  State<SharingSingleExampleHost> createState() =>
      _SharingSingleExampleHostState();
}

class _SharingSingleExampleHostState extends State<SharingSingleExampleHost> {
  late final SharingDemoController _controller;
  late final bool _ownsController;
  @override
  void initState() {
    super.initState();
    _ownsController = widget.controller == null;
    _controller =
        widget.controller ?? SharingDemoController(config: geniusPdfConfig);
    _controller.addListener(_onControllerChanged);
    _controller.initialize();
  }

  void _onControllerChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
_controller.removeListener(_onControllerChanged);
    if (_ownsController) _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return ValueListenableBuilder<ThemeMode>(
      valueListenable: themeController,
      builder: (context, themeMode, _) {
        final isDark = themeMode == ThemeMode.dark;
        final index = widget.initialTab.clamp(0, 4);

        return switch (index) {
          0 => _buildQuickShareTab(isDark),
          1 => _buildEmailTab(isDark),
          2 => _buildBluetoothTab(isDark),
          3 => _buildAppsTab(isDark),
          4 => _buildHistoryTab(isDark),
          _ => _buildQuickShareTab(isDark),
        };
      },
    );
  }
  Widget _buildQuickShareTab(bool isDark) {
    return FeatureExamplePage(
      title: pdfLocalization.quickShare,
      description: pdfLocalization.sharePdfsThroughTheUnifiedSharingService,
      icon: Icons.flash_on_rounded,
      code: '''final service = GeniusPdfSharingService();
await service.share(pdfBytes, fileName: 'document.pdf');''',
      contentTitle: 'Share actions',
      content: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          FeatureActionGrid(
            children: <Widget>[
              _buildShareButton(
                isDark: isDark,
                label: pdfLocalization.systemShareSheet,
                icon: Icons.share_rounded,
                gradient: AppColors.primaryGradient,
                onPressed: () => _shareViaSystem(),
              ),
              _buildShareButton(
                isDark: isDark,
                label: pdfLocalization.shareViaEmail,
                icon: Icons.email_rounded,
                gradient: AppColors.infoGradient,
                onPressed: () => _shareViaEmail(),
              ),
              _buildShareButton(
                isDark: isDark,
                label: pdfLocalization.shareViaBluetooth,
                icon: Icons.bluetooth_rounded,
                gradient: AppColors.purpleGradient,
                onPressed: () => _shareViaBluetooth(),
              ),
              _buildShareButton(
                isDark: isDark,
                label: pdfLocalization.saveToLocalStorage,
                icon: Icons.save_rounded,
                gradient: AppColors.successGradient,
                onPressed: () => _saveToLocal(),
              ),
            ],
          ),
          if (_controller.contacts.isNotEmpty) ...<Widget>[
            const SizedBox(height: 18),
            _buildSectionTitle(isDark, pdfLocalization.quickShareContacts),
            const SizedBox(height: 8),
            ..._controller.contacts.map(
              (contact) => _buildContactCard(isDark, contact),
            ),
          ],
        ],
      ),
      statusMessage: _controller.status.isEmpty
          ? 'Ready to share.'
          : _controller.status,
      statusTone: _controller.isLoading
          ? FeatureExampleTone.info
          : FeatureExampleTone.neutral,
    );
  }

  Widget _buildEmailTab(bool isDark) {
    return FeatureExamplePage(
      title: pdfLocalization.emailSharing,
      description: pdfLocalization.pdfEmailSharesReuseMessageTemplatesDesc,
      icon: Icons.email_rounded,
      code: '''await sharing.shareByEmail(
  pdfBytes,
  subject: 'PDF document',
  recipients: recipients,
);''',
      contentTitle: 'Email actions',
      content: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          FeatureActionGrid(
            children: <Widget>[
              _buildShareButton(
                isDark: isDark,
                label: pdfLocalization.composeEmail,
                icon: Icons.edit_rounded,
                gradient: AppColors.primaryGradient,
                onPressed: () => _composeEmail(),
              ),
              _buildShareButton(
                isDark: isDark,
                label: pdfLocalization.openGmail,
                icon: Icons.mail_rounded,
                gradient: AppColors.errorGradient,
                onPressed: () => _openGmail(),
              ),
              _buildShareButton(
                isDark: isDark,
                label: pdfLocalization.openOutlook,
                icon: Icons.mail_outline_rounded,
                gradient: AppColors.infoGradient,
                onPressed: () => _openOutlook(),
              ),
            ],
          ),
          const SizedBox(height: 18),
          _buildSectionTitle(isDark, pdfLocalization.emailTemplates),
          const SizedBox(height: 8),
          ..._controller.templates.map(
            (template) => _buildTemplateCard(isDark, template),
          ),
        ],
      ),
      statusMessage: _controller.status.isEmpty
          ? 'Ready to compose an email share.'
          : _controller.status,
    );
  }

  Widget _buildBluetoothTab(bool isDark) {
    return FeatureExamplePage(
      title: pdfLocalization.bluetoothSharing,
      description: pdfLocalization.discoverNearbyDevicesSharePdfDesc,
      icon: Icons.bluetooth_rounded,
      code: '''final devices = await sharing.discoverBluetoothDevices();
await sharing.shareToBluetoothDevice(pdfBytes, device);''',
      contentTitle: 'Nearby sharing actions',
      content: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          FeatureActionGrid(
            children: <Widget>[
              _buildShareButton(
                isDark: isDark,
                label: pdfLocalization.nearbyShareAirDrop,
                icon: Icons.near_me_rounded,
                gradient: AppColors.cyanGradient,
                onPressed: () => _shareViaNearby(),
              ),
              _buildShareButton(
                isDark: isDark,
                label: pdfLocalization.discoverDevices,
                icon: Icons.bluetooth_searching_rounded,
                gradient: AppColors.purpleGradient,
                onPressed: () => _discoverDevices(),
              ),
            ],
          ),
          if (_controller.savedDevices.isNotEmpty) ...<Widget>[
            const SizedBox(height: 18),
            _buildSectionTitle(isDark, pdfLocalization.savedDevices),
            const SizedBox(height: 8),
            ..._controller.savedDevices.map(
              (device) => _buildDeviceCard(isDark, device),
            ),
          ],
        ],
      ),
      statusMessage: _controller.status.isEmpty
          ? 'Ready to discover nearby devices.'
          : _controller.status,
    );
  }

  Widget _buildAppsTab(bool isDark) {
    return FeatureExamplePage(
      title: pdfLocalization.appSharing,
      description:
          pdfLocalization.sendPdfDocumentsMessagingCloudDesc,
      icon: Icons.apps_rounded,
      code: '''await sharing.shareToApp(
  pdfBytes,
  app: GeniusSharableApp.whatsApp(),
);''',
      contentTitle: 'Application targets',
      content: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          _buildSectionTitle(isDark, pdfLocalization.messagingApps),
          const SizedBox(height: 8),
          Wrap(
            spacing: 10,
            runSpacing: 10,
            children: <Widget>[
              _buildAppCard(
                isDark,
                pdfLocalization.whatsApp,
                Icons.message_rounded,
                AppColors.successGradient,
                () => _shareToApp(GeniusSharableApp.whatsApp()),
              ),
              _buildAppCard(
                isDark,
                pdfLocalization.telegram,
                Icons.send_rounded,
                AppColors.infoGradient,
                () => _shareToApp(GeniusSharableApp.telegram()),
              ),
              _buildAppCard(
                isDark,
                pdfLocalization.signal,
                Icons.shield_rounded,
                AppColors.purpleGradient,
                () => _shareToApp(GeniusSharableApp.signal()),
              ),
            ],
          ),
          const SizedBox(height: 18),
          _buildSectionTitle(isDark, pdfLocalization.cloudStorage),
          const SizedBox(height: 8),
          Wrap(
            spacing: 10,
            runSpacing: 10,
            children: <Widget>[
              _buildAppCard(
                isDark,
                pdfLocalization.googleDrive,
                Icons.cloud_rounded,
                AppColors.warningGradient,
                () => _shareToApp(GeniusSharableApp.googleDrive()),
              ),
              _buildAppCard(
                isDark,
                pdfLocalization.dropbox,
                Icons.folder_rounded,
                AppColors.infoGradient,
                () => _shareToApp(GeniusSharableApp.dropbox()),
              ),
              _buildAppCard(
                isDark,
                pdfLocalization.oneDrive,
                Icons.cloud_queue_rounded,
                AppColors.primaryGradient,
                () => _shareToApp(GeniusSharableApp.oneDrive()),
              ),
            ],
          ),
          const SizedBox(height: 18),
          FeatureActionGrid(
            children: <Widget>[
              _buildShareButton(
                isDark: isDark,
                label: pdfLocalization.saveToDownloads,
                icon: Icons.download_rounded,
                gradient: AppColors.successGradient,
                onPressed: () => _saveToDownloads(),
              ),
              _buildShareButton(
                isDark: isDark,
                label: pdfLocalization.openInExternalApp,
                icon: Icons.open_in_new_rounded,
                gradient: AppColors.infoGradient,
                onPressed: () => _openInExternalApp(),
              ),
            ],
          ),
        ],
      ),
      statusMessage: _controller.status.isEmpty
          ? 'Select a target application.'
          : _controller.status,
    );
  }

  Widget _buildHistoryTab(bool isDark) {
    return FeatureExamplePage(
      title: pdfLocalization.shareHistory,
      description: pdfLocalization.recentPdfSharingActivityOutcomesDesc,
      icon: Icons.history_rounded,
      code: '''final history = sharing.history;
for (final item in history) {
  print('\${item.fileName}: \${item.status}');
}''',
      contentTitle: 'Recent activity',
      content: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          if (_controller.history.isEmpty)
             FeatureReadyState(
              icon: Icons.history_rounded,
              title: pdfLocalization.noSharingHistoryYet,
              description:
                  pdfLocalization.sharingActionCompletedEntriesWillDesc,
            )
          else ...<Widget>[
            Row(
              children: <Widget>[
                Expanded(child: Text('${_controller.history.length} shares')),
                TextButton.icon(
                  onPressed: _clearHistory,
                  icon: const Icon(Icons.delete_outline_rounded),
                  label:  Text(pdfLocalization.clearHistory),
                ),
              ],
            ),
            const SizedBox(height: 8),
            ..._controller.history.map(
              (item) => _buildHistoryCard(isDark, item),
            ),
          ],
        ],
      ),
      statusMessage: _controller.status.isEmpty
          ? 'History is up to date.'
          : _controller.status,
    );
  }
  Widget _buildShareButton({
    required bool isDark,
    required String label,
    required IconData icon,
    required List<Color> gradient,
    VoidCallback? onPressed,
  }) {
    return FeatureActionCard(
      title: label,
      icon: icon,
      onPressed: _controller.isLoading ? null : onPressed,
    );
  }

  Widget _buildSectionTitle(bool isDark, String title) {
    return Text(
      title,
      style: Theme.of(context).textTheme.titleSmall?.copyWith(
        fontWeight: FontWeight.w700,
        color: Theme.of(context).colorScheme.onSurface,
      ),
    );
  }

  Widget _buildAppCard(
    bool isDark,
    String name,
    IconData icon,
    List<Color> gradient,
    VoidCallback onPressed,
  ) {
    return SizedBox(
      width: 180,
      child: FeatureActionCard(
        title: name,
        icon: icon,
        onPressed: _controller.hasSample && !_controller.isLoading
            ? onPressed
            : null,
      ),
    );
  }

  Widget _buildContactCard(bool isDark, GeniusQuickShareContact contact) {
    final colors = Theme.of(context).colorScheme;
    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      child: ListTile(
        onTap: () => _quickShareToContact(contact),
        leading: CircleAvatar(
          backgroundColor: colors.primaryContainer,
          foregroundColor: colors.onPrimaryContainer,
          child: Text(
            contact.name.isEmpty ? '?' : contact.name[0].toUpperCase(),
          ),
        ),
        title: Text(contact.name),
        subtitle: Text(contact.target.type.displayName),
        trailing: IconButton(
          onPressed: () => _toggleFavorite(contact.id),
          icon: Icon(
            contact.isFavorite ? Icons.star_rounded : Icons.star_border_rounded,
          ),
          tooltip: contact.isFavorite ? 'Remove favorite' : 'Add favorite',
        ),
      ),
    );
  }

  Widget _buildTemplateCard(bool isDark, GeniusShareMessageTemplate template) {
    final colors = Theme.of(context).colorScheme;
    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      child: ListTile(
        onTap: () => _shareWithTemplate(template),
        leading: Icon(Icons.description_outlined, color: colors.primary),
        title: Text(template.name),
        subtitle: Text(template.subject),
        trailing: const Icon(Icons.chevron_right_rounded),
      ),
    );
  }

  Widget _buildDeviceCard(bool isDark, GeniusBluetoothDevice device) {
    final colors = Theme.of(context).colorScheme;
    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      child: ListTile(
        onTap: () => _sendToDevice(device),
        leading: Icon(_getDeviceIcon(device.type), color: colors.primary),
        title: Text(device.name),
        subtitle: Text(device.type.displayName),
        trailing: device.isFavorite ? const Icon(Icons.star_rounded) : null,
      ),
    );
  }

  Widget _buildHistoryCard(bool isDark, GeniusShareHistoryItem item) {
    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      child: ListTile(
        leading: Icon(
          _getStatusIcon(item.status),
          color: _getStatusColor(item.status),
        ),
        title: Text(item.fileName),
        subtitle: Text(
          '${item.target.type.displayName} • ${_formatDate(item.timestamp)}',
        ),
      ),
    );
  }
  IconData _getDeviceIcon(GeniusBluetoothDeviceType type) {
    switch (type) {
      case GeniusBluetoothDeviceType.computer:
        return Icons.computer_rounded;
      case GeniusBluetoothDeviceType.phone:
        return Icons.smartphone_rounded;
      case GeniusBluetoothDeviceType.tablet:
        return Icons.tablet_rounded;
      case GeniusBluetoothDeviceType.printer:
        return Icons.print_rounded;
      case GeniusBluetoothDeviceType.audio:
        return Icons.headphones_rounded;
      default:
        return Icons.bluetooth_rounded;
    }
  }

  IconData _getStatusIcon(GeniusShareStatus status) {
    switch (status) {
      case GeniusShareStatus.completed:
        return Icons.check_circle_rounded;
      case GeniusShareStatus.failed:
        return Icons.error_rounded;
      default:
        return Icons.pending_rounded;
    }
  }

  Color _getStatusColor(GeniusShareStatus status) {
    switch (status) {
      case GeniusShareStatus.completed:
        return AppColors.success;
      case GeniusShareStatus.failed:
        return AppColors.error;
      default:
        return AppColors.warning;
    }
  }

  String _formatDate(DateTime date) {
    final now = DateTime.now();
    final diff = now.difference(date);
    if (diff.inMinutes < 1) return 'Just now';
    if (diff.inHours < 1) return '${diff.inMinutes}m ago';
    if (diff.inDays < 1) return '${diff.inHours}h ago';
    return '${diff.inDays}d ago';
  }

  // Actions
  Future<void> _shareViaSystem() => _controller.shareViaSystem();

  Future<void> _shareViaEmail() => _controller.shareViaEmail();

  Future<void> _shareViaBluetooth() => _controller.shareViaBluetooth();

  Future<void> _saveToLocal() => _controller.saveToLocal();

  Future<void> _composeEmail() => _controller.composeEmail();

  Future<void> _openGmail() => _controller.openGmail();

  Future<void> _openOutlook() => _controller.openOutlook();

  Future<void> _shareViaNearby() => _controller.shareViaNearby();

  Future<void> _discoverDevices() => _controller.discoverDevices();

  Future<void> _sendToDevice(GeniusBluetoothDevice device) =>
      _controller.sendToDevice(device);

  Future<void> _shareToApp(GeniusSharableApp app) =>
      _controller.shareToApp(app);

  Future<void> _saveToDownloads() => _controller.saveToDownloads();

  Future<void> _openInExternalApp() => _controller.openInExternalApp();

  void _toggleFavorite(String contactId) =>
      _controller.toggleFavorite(contactId);

  Future<void> _quickShareToContact(GeniusQuickShareContact contact) =>
      _controller.quickShareToContact(contact);

  Future<void> _shareWithTemplate(GeniusShareMessageTemplate template) =>
      _controller.shareWithTemplate(template);

  Future<void> _clearHistory() => _controller.clearHistory();
}
