// GENERATED BY redesign_remaining_multi_example_screens.py
// Internal single-example host. Navigation never exposes a tabbed aggregate UI.

import 'package:flutter/material.dart';
import 'package:genius_pdf_example/shared/application/contracts/demo_file_gateway.dart';
import 'package:flutter/services.dart';
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;
import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';

import 'package:genius_pdf_example/features/template_engine/models/documents/template_builtin_invoice.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_builtin_letter.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_builtin_report.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_contract.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_export_json.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_invoice.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_json_letter.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_json_memo.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_purchase_order.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_quotation.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_receipt.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_report.dart';
import 'package:genius_pdf_example/features/template_engine/models/documents/template_timesheet.dart';

import 'package:genius_pdf_example/shared/presentation/widgets/feature_example_page.dart';

import 'package:genius_pdf_example/localizations/pdf_generator_localization.dart';
/// Demo screen for Template Engine features (v1.5.0).
class TemplateEngineSingleExampleHost extends StatefulWidget {
  const TemplateEngineSingleExampleHost({super.key, this.initialTab = 0});

  final int initialTab;

  @override
  State<TemplateEngineSingleExampleHost> createState() =>
      _TemplateEngineSingleExampleHostState();
}

class _TemplateEngineSingleExampleHostState
    extends State<TemplateEngineSingleExampleHost> {
  bool _isLoading = false;
  String _status = '';

  @override
  Widget build(BuildContext context) {
    final index = widget.initialTab.clamp(0, 2);

    return switch (index) {
        0 => _buildBuilderTab(),
        1 => _buildJsonTab(),
        2 => _buildRegistryTab(),
        _ => _buildBuilderTab(),
    };
  }

  Widget _buildBuilderTab() {
    return FeatureExamplePage(
      title: pdfLocalization.templateBuilder,
      description: pdfLocalization.reusablePdfTemplatesProgrammaticallyDesc,
      icon: Icons.build_rounded,
      code: '''final template = TemplateBuilder()
  .name('invoice')
  .build();

final bytes = await template.render(data);''',
      contentTitle: 'Builder actions',
      content: FeatureActionGrid(
        children: <Widget>[
          _buildActionButton(label: pdfLocalization.generateInvoiceTemplate, labelAr: 'إنشاء قالب فاتورة', icon: Icons.receipt_rounded, onPressed: _generateInvoiceTemplate),
          _buildActionButton(label: pdfLocalization.generateReportTemplate, labelAr: 'إنشاء قالب تقرير', icon: Icons.article_rounded, onPressed: _generateReportTemplate),
          _buildActionButton(label: pdfLocalization.generatePurchaseOrder, labelAr: 'إنشاء أمر شراء', icon: Icons.shopping_cart_rounded, onPressed: _generatePurchaseOrderTemplate),
          _buildActionButton(label: pdfLocalization.generateReceiptTemplate, labelAr: 'إنشاء قالب إيصال', icon: Icons.receipt_long_rounded, onPressed: _generateReceiptTemplate),
          _buildActionButton(label: pdfLocalization.generateQuotation, labelAr: 'إنشاء عرض سعر', icon: Icons.request_quote_rounded, onPressed: _generateQuotationTemplate),
          _buildActionButton(label: pdfLocalization.generateContract, labelAr: 'إنشاء عقد خدمة', icon: Icons.assignment_rounded, onPressed: _generateContractTemplate),
          _buildActionButton(label: pdfLocalization.generateTimesheet, labelAr: 'إنشاء سجل دوام', icon: Icons.schedule_rounded, onPressed: _generateTimesheetTemplate),
        ],
      ),
      statusMessage: _status.isEmpty ? 'Choose an action to execute the template builder.' : _status,
      statusTone: _isLoading ? FeatureExampleTone.info : FeatureExampleTone.neutral,
    );
  }
  Widget _buildJsonTab() {
    return FeatureExamplePage(
      title: pdfLocalization.jsonTemplates,
      description: pdfLocalization.importRenderExportPortableTemplateDesc,
      icon: Icons.code_rounded,
      code: '''final definition = TemplateDefinition.fromJson(json);
final bytes = await registry.renderDefinition(definition, data);
final exported = definition.toJson();''',
      contentTitle: 'JSON template actions',
      content: FeatureActionGrid(
        children: <Widget>[
          _buildActionButton(label: pdfLocalization.renderJsonLetter, labelAr: 'عرض خطاب JSON', icon: Icons.mail_outline_rounded, onPressed: _generateFromJson),
          _buildActionButton(label: pdfLocalization.renderJsonMemo, labelAr: 'عرض مذكرة JSON', icon: Icons.note_alt_rounded, onPressed: _generateFromJsonMemo),
          _buildActionButton(label: pdfLocalization.exportTemplateToJson, labelAr: 'تصدير القالب إلى JSON', icon: Icons.download_rounded, onPressed: _exportToJson),
        ],
      ),
      statusMessage: _status.isEmpty ? 'Choose a JSON template action.' : _status,
    );
  }
  Widget _buildRegistryTab() {
    return FeatureExamplePage(
      title: pdfLocalization.templateRegistry,
      description: pdfLocalization.registerDiscoverRenderTemplatesOneDesc,
      icon: Icons.inventory_2_rounded,
      code: '''final registry = GeniusTemplateRegistry.instance;
registry.register(invoiceTemplate);
final templates = registry.templates;
final bytes = await registry.render('invoice', data);''',
      contentTitle: 'Registry actions',
      content: FeatureActionGrid(
        children: <Widget>[
          _buildActionButton(label: pdfLocalization.registerBuiltInTemplates, labelAr: 'تسجيل القوالب المدمجة', icon: Icons.library_add_rounded, onPressed: _registerBuiltInTemplates),
          _buildActionButton(label: pdfLocalization.listAllTemplates, labelAr: 'عرض جميع القوالب', icon: Icons.list_rounded, onPressed: _listTemplates),
          _buildActionButton(label: pdfLocalization.renderBuiltInInvoice, labelAr: 'عرض الفاتورة المدمجة', icon: Icons.picture_as_pdf_rounded, onPressed: _renderBuiltInInvoice),
          _buildActionButton(label: pdfLocalization.renderBuiltInReport, labelAr: 'عرض التقرير المدمج', icon: Icons.assessment_rounded, onPressed: _renderBuiltInReport),
          _buildActionButton(label: pdfLocalization.renderBuiltInLetter, labelAr: 'عرض الخطاب المدمج', icon: Icons.mail_outline_rounded, onPressed: _renderBuiltInLetter),
        ],
      ),
      statusMessage: _status.isEmpty ? 'Choose a registry action.' : _status,
    );
  }

  Widget _buildActionButton({
    required String label,
    required String labelAr,
    required IconData icon,
    required VoidCallback onPressed,
  }) {
    return FeatureActionCard(
      title: label,
      subtitle: labelAr,
      icon: icon,
      onPressed: _isLoading ? null : onPressed,
    );
  }

  Future<void> _generateInvoiceTemplate() async {
    setState(() {
      _isLoading = true;
      _status = 'Building invoice template...';
    });

    try {
      // Build template
      final result = await buildTemplateInvoiceBytes(geniusPdfConfig);

      setState(() {
        _status = 'Invoice template generated successfully!\n'
            'Template ID: ${result.template.id}\n'
            'Variables: ${result.template.variables.length}\n'
            'Elements: ${result.template.content.length}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_invoice');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _generateReportTemplate() async {
    setState(() {
      _isLoading = true;
      _status = 'Building report template...';
    });

    try {
      final result = await buildTemplateReportBytes(geniusPdfConfig);

      setState(() {
        _status = 'Report template generated successfully!\n'
            'Template ID: ${result.template.id}\n'
            'Variables: ${result.template.variables.length}\n'
            'Elements: ${result.template.content.length}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_report');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _generatePurchaseOrderTemplate() async {
    setState(() {
      _isLoading = true;
      _status = 'Building purchase order template...';
    });

    try {
      final result = await buildTemplatePurchaseOrderBytes(geniusPdfConfig);

      setState(() {
        _status = 'Purchase order generated successfully!\n'
            'Template ID: ${result.template.id}\n'
            'Variables: ${result.template.variables.length}\n'
            'Elements: ${result.template.content.length}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_purchase_order');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
        _isLoading = false;
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _generateReceiptTemplate() async {
    setState(() {
      _isLoading = true;
      _status = 'Building receipt template...';
    });

    try {
      final result = await buildTemplateReceiptBytes(geniusPdfConfig);

      setState(() {
        _status = 'Receipt template generated successfully!\n'
            'Template ID: ${result.template.id}\n'
            'Variables: ${result.template.variables.length}\n'
            'Elements: ${result.template.content.length}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_receipt');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _generateQuotationTemplate() async {
    setState(() {
      _isLoading = true;
      _status = 'Building quotation template...';
    });

    try {
      final result = await buildTemplateQuotationBytes(geniusPdfConfig);

      setState(() {
        _status = 'Quotation template generated successfully!\n'
            'Template ID: ${result.template.id}\n'
            'Variables: ${result.template.variables.length}\n'
            'Elements: ${result.template.content.length}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_quotation');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _generateContractTemplate() async {
    setState(() {
      _isLoading = true;
      _status = 'Building contract template...';
    });

    try {
      final result = await buildTemplateContractBytes(geniusPdfConfig);

      setState(() {
        _status = 'Contract template generated successfully!\n'
            'Template ID: ${result.template.id}\n'
            'Variables: ${result.template.variables.length}\n'
            'Elements: ${result.template.content.length}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_contract');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _generateTimesheetTemplate() async {
    setState(() {
      _isLoading = true;
      _status = 'Building timesheet template...';
    });

    try {
      final result = await buildTemplateTimesheetBytes(geniusPdfConfig);

      setState(() {
        _status = 'Timesheet template generated successfully!\n'
            'Template ID: ${result.template.id}\n'
            'Variables: ${result.template.variables.length}\n'
            'Elements: ${result.template.content.length}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_timesheet');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _generateFromJson() async {
    setState(() {
      _isLoading = true;
      _status = 'Loading template from JSON...';
    });

    try {
      final result = await buildTemplateFromJsonLetterBytes(geniusPdfConfig);

      setState(() {
        _status = 'Template loaded from JSON successfully!\n'
            'Template: ${result.template.name}\n'
            'Version: ${result.template.version}\n'
            'Variables: ${result.template.variables.length}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_json_letter');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _generateFromJsonMemo() async {
    setState(() {
      _isLoading = true;
      _status = 'Loading memo template from JSON...';
    });

    try {
      final result = await buildTemplateFromJsonMemoBytes(geniusPdfConfig);

      setState(() {
        _status = 'Memo template loaded from JSON!\n'
            'Template: ${result.template.name}\n'
            'Version: ${result.template.version}\n'
            'Variables: ${result.template.variables.length}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_json_memo');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _exportToJson() async {
    setState(() {
      _isLoading = true;
      _status = 'Creating and exporting template...';
    });

    try {
      final json = buildExportTemplateJson();

      setState(() {
        _status = 'Template exported to JSON:\n\n$json';
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _registerBuiltInTemplates() async {
    setState(() {
      _isLoading = true;
      _status = 'Registering built-in templates...';
    });

    try {
      final registry = TemplateRegistry.instance;
      registry.clear();
      TemplateLibrary.registerBuiltInTemplates(registry);

      setState(() {
        _status = 'Built-in templates registered!\n'
            'Total templates: ${registry.count}\n'
            'Categories: ${registry.categories.join(", ")}\n'
            'Tags: ${registry.allTags.join(", ")}';
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _listTemplates() async {
    setState(() {
      _isLoading = true;
      _status = 'Listing templates...';
    });

    try {
      final registry = TemplateRegistry.instance;

      if (registry.count == 0) {
        TemplateLibrary.registerBuiltInTemplates(registry);
      }

      final templates = registry.templates;
      final buffer = StringBuffer('Registered Templates:\n\n');

      for (final template in templates) {
        buffer.writeln('• ${template.name} (${template.nameAr ?? ""})');
        buffer.writeln('  ID: ${template.id}');
        buffer.writeln('  Category: ${template.category ?? "none"}');
        buffer.writeln('  Variables: ${template.variables.length}');
        buffer.writeln('');
      }

      setState(() {
        _status = buffer.toString();
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _renderBuiltInInvoice() async {
    setState(() {
      _isLoading = true;
      _status = 'Rendering built-in invoice template...';
    });

    try {
      final result = await buildBuiltInInvoiceBytes(geniusPdfConfig);

      setState(() {
        _status = 'Built-in invoice rendered successfully!\n'
            'Template: ${result.template.name}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_builtin_invoice');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _renderBuiltInReport() async {
    setState(() {
      _isLoading = true;
      _status = 'Rendering built-in report template...';
    });

    try {
      final result = await buildBuiltInReportBytes(geniusPdfConfig);

      setState(() {
        _status = 'Built-in report rendered successfully!\n'
            'Template: ${result.template.name}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_builtin_report');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _renderBuiltInLetter() async {
    setState(() {
      _isLoading = true;
      _status = 'Rendering built-in letter template...';
    });

    try {
      final result = await buildBuiltInLetterBytes(geniusPdfConfig);

      setState(() {
        _status = 'Built-in letter rendered successfully!\n'
            'Template: ${result.template.name}';
      });
      await _saveAndOpenPdf(result.bytes, 'template_builtin_letter');
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  Future<void> _saveAndOpenPdf(Uint8List bytes, String fileName) async {
    await demoDocuments.saveAndOpen(
      bytes: bytes,
      fileName: fileName,
      location: DemoStorageLocation.temporary,
    );
  }
}
