// Generated by use_global_manager_toasts_in_showcase_tables_template_engine.py

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/features/showcase/models/documents/showcase_demo_documents.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _showcaseWorker(
  Map<String, Object?> message,
) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final bytes = await buildShowcaseDemoBytes(
    showcaseId: message['showcaseId']! as String,
    config: config,
  );
  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates one Showcase PDF on a worker isolate.
///
/// Queueing, persistence, progress lifecycle, and Toast feedback remain owned
/// by the app-wide GeniusPdfGenerationManager.
Future<Uint8List> generateShowcaseExampleInBackground({
  required String showcaseId,
  required bool isRtl,
}) async {
  final config = geniusPdfConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'showcaseId': showcaseId,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _showcaseWorker(message),
    debugName: 'showcase-$showcaseId',
  );
  return transferred.materialize().asUint8List();
}
