// Generated by use_global_manager_toasts_in_showcase_tables_template_engine.py

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/features/tables_grids/models/documents/s04_data_grid_vnext_verification_documents.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _tablesGridsWorker(
  Map<String, Object?> message,
) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final apiName = message['apiName']! as String;

  final Uint8List bytes = switch (apiName) {
    'buildS04SizingVerificationPdf' =>
      await buildS04SizingVerificationPdf(config),
    'buildS04LongContentVerificationPdf' =>
      await buildS04LongContentVerificationPdf(config),
    'buildS04PaginationVerificationPdf' =>
      await buildS04PaginationVerificationPdf(config),
    'buildS04GroupingVerificationPdf' =>
      await buildS04GroupingVerificationPdf(config),
    'buildS04SpansAndBuildersVerificationPdf' =>
      await buildS04SpansAndBuildersVerificationPdf(config),
    'buildS04ErpFormattingVerificationPdf' =>
      await buildS04ErpFormattingVerificationPdf(config),
    'buildS04DirectionalityVerificationPdf' =>
      await buildS04DirectionalityVerificationPdf(config),
    'buildS04EmptyStateVerificationPdf' =>
      await buildS04EmptyStateVerificationPdf(config),
    'buildS04LargeDataVerificationPdf' =>
      await buildS04LargeDataVerificationPdf(config),
    _ => throw ArgumentError.value(
        apiName,
        'apiName',
        'Unsupported tables/grids background example',
      ),
  };

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Generates a tables/grids verification PDF outside the UI isolate.
Future<Uint8List> generateTablesGridsExampleInBackground({
  required String apiName,
  required bool isRtl,
}) async {
  final config = geniusPdfConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'apiName': apiName,
  };

  final transferred = await Isolate.run<TransferableTypedData>(
    () => _tablesGridsWorker(message),
    debugName: 'tables-grids-$apiName',
  );
  return transferred.materialize().asUint8List();
}
