// Generated by migrate_modern_vouchers_printing_security_to_global_manager.py
// Background dispatcher for Printing S11 PDF examples.

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

import 'package:genius_pdf_example/features/printing/models/documents/s11_print_profiles_verification_documents.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _worker(Map<String, Object?> message) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  final apiName = message['apiName']! as String;

  final Uint8List bytes = switch (apiName) {
    'buildS11A4LandscapeVerificationPdf' => await buildS11A4LandscapeVerificationPdf(config),
    'buildS11A4PortraitVerificationPdf' => await buildS11A4PortraitVerificationPdf(config),
    'buildS11A5VerificationPdf' => await buildS11A5VerificationPdf(config),
    'buildS11CalibrationVerificationPdf' => await buildS11CalibrationVerificationPdf(config),
    'buildS11ContinuousVerificationPdf' => await buildS11ContinuousVerificationPdf(config),
    'buildS11LabelSheetVerificationPdf' => await buildS11LabelSheetVerificationPdf(config),
    'buildS11LegalVerificationPdf' => await buildS11LegalVerificationPdf(config),
    'buildS11LetterVerificationPdf' => await buildS11LetterVerificationPdf(config),
    'buildS11PrePrintedVerificationPdf' => await buildS11PrePrintedVerificationPdf(config),
    'buildS11SingleLabelVerificationPdf' => await buildS11SingleLabelVerificationPdf(config),
    'buildS11Thermal58VerificationPdf' => await buildS11Thermal58VerificationPdf(config),
    'buildS11Thermal80VerificationPdf' => await buildS11Thermal80VerificationPdf(config),
    _ => throw ArgumentError.value(
        apiName,
        'apiName',
        'Unsupported Printing S11 background example',
      ),
  };

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Runs one Printing S11 document generator outside the UI isolate.
Future<Uint8List> generatePrintingVerificationInBackground({
  required String apiName,
  required bool isRtl,
  required GeniusPdfConfig rootConfig,
}) async {
  final config = rootConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'apiName': apiName,
  };

  final result = await Isolate.run<TransferableTypedData>(
    () => _worker(message),
    debugName: 'printing-s11-$apiName',
  );
  return result.materialize().asUint8List();
}
