// GENERATED BY redesign_remaining_multi_example_screens.py
// Internal single-example host. Navigation never exposes a tabbed aggregate UI.

import 'package:flutter/material.dart';
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

import 'package:genius_pdf_example/app/theme/app_theme.dart';
import 'package:genius_pdf_example/shared/presentation/widgets/component_page.dart';
import 'package:genius_pdf_example/shared/presentation/widgets/custom_tab_bar.dart';

import 'package:genius_pdf_example/shared/presentation/widgets/feature_example_page.dart';
import 'package:genius_pdf_example/localizations/pdf_generator_localization.dart';
/// Demo screen for AI Features (v2.1.0).
///
/// This screen demonstrates the AI-powered features:
/// - **Content Analyzer**: Extract text, detect document types, find structured data
/// - **Smart Layout**: Font size, margin, and spacing suggestions
/// - **Text Services**: Summarization, language detection, title generation
class AiFeaturesSingleExampleHost extends StatefulWidget {
  const AiFeaturesSingleExampleHost({super.key, this.initialTab = 0});

  final int initialTab;

  @override
  State<AiFeaturesSingleExampleHost> createState() => _AiFeaturesSingleExampleHostState();
}

class _AiFeaturesSingleExampleHostState extends State<AiFeaturesSingleExampleHost>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;
  bool _isLoading = false;
  String _status = '';
  bool _isRTL = true;

  final List<CustomTabItem> _tabs = [
    CustomTabItem(
      id: 'content_analyzer',
      title: pdfLocalization.contentAnalyzer,
      icon: Icons.analytics_outlined,
      gradient: AppColors.primaryGradient,
    ),
    CustomTabItem(
      id: 'smart_layout',
      title: pdfLocalization.smartLayout,
      icon: Icons.auto_fix_high_outlined,
      gradient: AppColors.purpleGradient,
    ),
    CustomTabItem(
      id: 'text_services',
      title: pdfLocalization.textServices,
      icon: Icons.text_fields_outlined,
      gradient: AppColors.cyanGradient,
    ),
  ];

  @override
  void initState() {
    super.initState();
    _tabController = TabController(
      length: _tabs.length,
      vsync: this,
      initialIndex: widget.initialTab.clamp(0, _tabs.length - 1),
    );
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final index = widget.initialTab.clamp(0, 2);

    return switch (index) {
        0 => _buildContentAnalyzerTab(isDark),
        1 => _buildSmartLayoutTab(isDark),
        2 => _buildTextServicesTab(isDark),
        _ => _buildContentAnalyzerTab(isDark),
    };
  }

  Widget _buildContentAnalyzerTab(bool isDark) {
    return ComponentPage(
      title: pdfLocalization.contentAnalyzer,
      description:
          pdfLocalization.extractTextDetectDocumentTypesFindDesc,
      icon: Icons.analytics_outlined,
      gradient: AppColors.primaryGradient,
      isDark: isDark,
      isRTL: _isRTL,
      onRTLChanged: (v) => setState(() => _isRTL = v),
      isGenerating: _isLoading,
      onGenerate: null, // Custom actions provided in preview
      codeExample: '''
final analyzer = GeniusPdfContentAnalyzer();
final keywords = analyzer.extractKeywords(textList);
final type = analyzer.detectDocumentType(text);
''',
      preview: Column(
        children: [
          _buildContentAnalyzerActions(isDark),
          if (_status.isNotEmpty) ...[
            const SizedBox(height: 16),
            _buildResultsCard(isDark),
          ],
        ],
      ),
    );
  }

  Widget _buildSmartLayoutTab(bool isDark) {
    return ComponentPage(
      title: pdfLocalization.smartLayout,
      description:
          pdfLocalization.getIntelligentLayoutSuggestionsFontDesc,
      icon: Icons.auto_fix_high_outlined,
      gradient: AppColors.purpleGradient,
      isDark: isDark,
      isRTL: _isRTL,
      onRTLChanged: (v) => setState(() => _isRTL = v),
      isGenerating: _isLoading,
      onGenerate: null,
      codeExample: '''
// Analyze layout
final layout = GeniusSmartLayout();
final margins = layout.suggestMargins(pageSize);

// Color suggestions
final scheme = layout.suggestColorScheme(
  baseColor: AppColors.primary,
  isDark: true,
);
''',
      preview: Column(
        children: [
          _buildSmartLayoutActions(isDark),
          if (_status.isNotEmpty) ...[
            const SizedBox(height: 16),
            _buildResultsCard(isDark),
          ],
        ],
      ),
    );
  }

  Widget _buildTextServicesTab(bool isDark) {
    return ComponentPage(
      title: pdfLocalization.textServices,
      description:
          pdfLocalization.textSummarizationLanguageDetectionDesc,
      icon: Icons.text_fields_outlined,
      gradient: AppColors.cyanGradient,
      isDark: isDark,
      isRTL: _isRTL,
      onRTLChanged: (v) => setState(() => _isRTL = v),
      isGenerating: _isLoading,
      onGenerate: null,
      codeExample: '''
final services = GeniusSmartTextServices();
final summary = services.summarize(longText);
final language = services.detectLanguage(text);
final titles = services.generateTitles(content);
''',
      preview: Column(
        children: [
          _buildTextServicesActions(isDark),
          if (_status.isNotEmpty) ...[
            const SizedBox(height: 16),
            _buildResultsCard(isDark),
          ],
        ],
      ),
    );
  }

  Widget _buildContentAnalyzerActions(bool isDark) {
    return Column(
      children: [
        _buildActionButton(
          label: pdfLocalization.analyzeSampleInvoice,
          icon: Icons.receipt_long_outlined,
          gradient: AppColors.primaryGradient,
          onPressed: _analyzeInvoiceText,
          isDark: isDark,
        ),
        const SizedBox(height: 12),
        _buildActionButton(
          label: pdfLocalization.analyzeSampleReport,
          icon: Icons.assessment_outlined,
          gradient: AppColors.infoGradient,
          onPressed: _analyzeReportText,
          isDark: isDark,
        ),
        const SizedBox(height: 12),
        _buildActionButton(
          label: pdfLocalization.extractStructuredData,
          icon: Icons.data_object_outlined,
          gradient: AppColors.successGradient,
          onPressed: _extractStructuredData,
          isDark: isDark,
        ),
      ],
    );
  }

  Widget _buildSmartLayoutActions(bool isDark) {
    return Column(
      children: [
        _buildActionButton(
          label: pdfLocalization.analyzeFontSizes,
          icon: Icons.format_size_outlined,
          gradient: AppColors.purpleGradient,
          onPressed: _analyzeFontSizes,
          isDark: isDark,
        ),
        const SizedBox(height: 12),
        _buildActionButton(
          label: pdfLocalization.suggestMargins,
          icon: Icons.format_indent_increase_outlined,
          gradient: AppColors.cyanGradient,
          onPressed: _suggestMargins,
          isDark: isDark,
        ),
        const SizedBox(height: 12),
        _buildActionButton(
          label: pdfLocalization.suggestColorScheme,
          icon: Icons.palette_outlined,
          gradient: AppColors.pinkGradient,
          onPressed: _suggestColorScheme,
          isDark: isDark,
        ),
        const SizedBox(height: 12),
        _buildActionButton(
          label: pdfLocalization.fullLayoutOptimization,
          icon: Icons.auto_awesome_outlined,
          gradient: AppColors.orangeGradient,
          onPressed: _optimizeLayout,
          isDark: isDark,
        ),
      ],
    );
  }

  Widget _buildTextServicesActions(bool isDark) {
    return Column(
      children: [
        _buildActionButton(
          label: pdfLocalization.summarizeLongText,
          icon: Icons.summarize_outlined,
          gradient: AppColors.cyanGradient,
          onPressed: _summarizeText,
          isDark: isDark,
        ),
        const SizedBox(height: 12),
        _buildActionButton(
          label: pdfLocalization.detectLanguage,
          icon: Icons.translate_outlined,
          gradient: AppColors.tealGradient,
          onPressed: _detectLanguage,
          isDark: isDark,
        ),
        const SizedBox(height: 12),
        _buildActionButton(
          label: pdfLocalization.generateTitles,
          icon: Icons.title_outlined,
          gradient: AppColors.warningGradient,
          onPressed: _generateTitles,
          isDark: isDark,
        ),
        const SizedBox(height: 12),
        _buildActionButton(
          label: pdfLocalization.extractKeywords,
          icon: Icons.key_outlined,
          gradient: AppColors.errorGradient,
          onPressed: _extractKeywords,
          isDark: isDark,
        ),
      ],
    );
  }
  Widget _buildActionButton({
    required String label,
    required IconData icon,
    required List<Color> gradient,
    required VoidCallback onPressed,
    required bool isDark,
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: FeatureActionCard(
        title: label,
        icon: icon,
        onPressed: _isLoading ? null : onPressed,
      ),
    );
  }
  Widget _buildResultsCard(bool isDark) {
    return FeatureStatusPanel(
      message: _status,
      loading: _isLoading,
      tone: FeatureExampleTone.info,
    );
  }

  // ============ Actions ============

  void _analyzeInvoiceText() {
    setState(() {
      _isLoading = true;
      _status = 'Analyzing invoice text...';
    });

    try {
      const invoiceText = '''
        INVOICE #INV-2026-001
        Date: January 24, 2026

        Bill To:
        Ahmed Mohamed
        Email: ahmed@example.com
        Phone: +966 50 123 4567

        Items:
        Product A - SAR 500.00
        Product B - SAR 750.00
        Service C - SAR 250.00

        Subtotal: SAR 1,500.00
        VAT (15%): SAR 225.00
        Total: SAR 1,725.00

        Payment Terms: Net 30 days
        Bank: Saudi National Bank
      ''';

      final analyzer = GeniusPdfContentAnalyzer();
      final detectedLanguages = ['en'];
      final keywords = analyzer.extractKeywords(
          invoiceText.split(' ').where((w) => w.length > 3).toList());

      final buffer = StringBuffer('INVOICE TEXT ANALYSIS\n');
      buffer.writeln('=' * 40);
      buffer.writeln('\nDetected Languages: ${detectedLanguages.join(", ")}');
      buffer.writeln('Detected Type: Invoice');
      buffer.writeln('\nKeywords:');
      for (final keyword in keywords.take(5)) {
        buffer.writeln('  - $keyword');
      }

      setState(() {
        _status = buffer.toString();
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  void _analyzeReportText() {
    setState(() {
      _isLoading = true;
      _status = 'Analyzing report text...';
    });

    try {
      const reportText = '''
        Monthly Performance Report
        January 2026

        Executive Summary:
        This report provides a comprehensive overview of the company's performance metrics
        for January 2026. Revenue growth exceeded targets by 15%, while operational costs
        were reduced by 8% through automation initiatives.

        Key Findings:
        1. Total revenue reached SAR 2.5 million
        2. Customer satisfaction score: 92%
        3. New customer acquisition: 150 clients
        4. Employee retention rate: 95%

        Recommendations:
        Continue investment in customer service training and expand automation efforts
        to maintain operational efficiency gains.

        Contact: reports@company.com
      ''';

      final textServices = GeniusSmartTextServices();
      final summary = textServices.summarize(reportText, maxLength: 200);
      final language = textServices.detectLanguage(reportText);
      final keywords = textServices.extractKeywords(reportText, maxKeywords: 5);

      final buffer = StringBuffer('REPORT ANALYSIS\n');
      buffer.writeln('=' * 40);
      buffer.writeln(
          '\nLanguage: ${language.primaryLanguage} (${(language.confidence * 100).toStringAsFixed(0)}% confidence)');
      buffer.writeln('Is RTL: ${language.isRtl}');
      buffer.writeln(
          '\nSummary (${summary.compressionRatio * 100 ~/ 1}% compression):');
      buffer.writeln(summary.summary);
      buffer.writeln('\nKey Points:');
      for (final point in summary.keyPoints.take(3)) {
        buffer.writeln('  - $point');
      }
      buffer.writeln('\nKeywords: ${keywords.join(", ")}');

      setState(() {
        _status = buffer.toString();
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  void _extractStructuredData() {
    setState(() {
      _isLoading = true;
      _status = 'Extracting structured data...';
    });

    try {
      const sampleText = '''
        Invoice #INV-2026-001
        Order Reference: PO-2026-5678
        Date: 2026-01-24
        Due Date: February 23, 2026

        Contact Information:
        Email: sales@example.com
        Phone: +966 12 345 6789
        Mobile: 0501234567

        Amounts:
        Subtotal: SAR 1,500.00
        VAT (15%): USD 225.00
        Discount: -\$50.00
        Total: 1,675.00
      ''';

      // Extract dates
      final datePatterns = [
        RegExp(r'\d{4}-\d{1,2}-\d{1,2}'),
        RegExp(
            r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},?\s+\d{4}',
            caseSensitive: false),
      ];

      final dates = <String>[];
      for (final pattern in datePatterns) {
        dates.addAll(pattern.allMatches(sampleText).map((m) => m.group(0)!));
      }

      // Extract emails
      final emailPattern =
          RegExp(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b');
      final emails =
          emailPattern.allMatches(sampleText).map((m) => m.group(0)!).toList();

      // Extract phone numbers
      final phonePatterns = [
        RegExp(r'\+?\d{1,3}[-.\s]?\d{2,4}[-.\s]?\d{3}[-.\s]?\d{4}'),
        RegExp(r'\b0?5\d{8}\b'),
      ];

      final phones = <String>{};
      for (final pattern in phonePatterns) {
        phones.addAll(pattern.allMatches(sampleText).map((m) => m.group(0)!));
      }

      // Extract currencies/amounts
      final amountPatterns = [
        RegExp(r'(?:SAR|USD|EUR)\s?[\d,]+\.?\d*'),
        RegExp(r'\$?\s?[\d,]+\.?\d*'),
      ];

      final amounts = <String>{};
      for (final pattern in amountPatterns) {
        amounts.addAll(pattern.allMatches(sampleText).map((m) => m.group(0)!));
      }

      final buffer = StringBuffer('STRUCTURED DATA EXTRACTION\n');
      buffer.writeln('=' * 40);
      buffer.writeln('\nFound Dates:');
      for (final date in dates) {
        buffer.writeln('  - $date');
      }

      buffer.writeln('\nFound Emails:');
      for (final email in emails) {
        buffer.writeln('  - $email');
      }

      buffer.writeln('\nFound Phone Numbers:');
      for (final phone in phones) {
        buffer.writeln('  - $phone');
      }

      buffer.writeln('\nFound Amounts:');
      for (final amount in amounts) {
        buffer.writeln('  - $amount');
      }

      setState(() {
        _status = buffer.toString();
      });
    } catch (e) {
      setState(() {
        _status = 'Error: $e';
      });
    } finally {
      setState(() => _isLoading = false);
    }
  }

  void _analyzeFontSizes() {
    setState(() {
      _isLoading = true;
      _status = 'Calculating optimal font sizes...';
    });

    Future.delayed(const Duration(seconds: 1), () {
      if (!mounted) return;

      final buffer = StringBuffer('FONT SIZE ANALYSIS\n');
      buffer.writeln('=' * 40);
      buffer.writeln('\nDocument Type: Standard Report (A4)');
      buffer.writeln('\nRecommended Sizes:');
      buffer.writeln('  - Main Title: 24pt (Bold)');
      buffer.writeln('  - Section Headers: 18pt (Semi-Bold)');
      buffer.writeln('  - Body Text: 11pt (Regular)');
      buffer.writeln('  - Captions/Footnotes: 9pt (Light)');
      buffer.writeln('\nReadability Score: 92/100');

      setState(() {
        _status = buffer.toString();
        _isLoading = false;
      });
    });
  }

  void _suggestMargins() {
    setState(() {
      _isLoading = true;
      _status = 'Analyzing page structure...';
    });

    Future.delayed(const Duration(seconds: 1), () {
      if (!mounted) return;

      final buffer = StringBuffer('LAYOUT MARGIN SUGGESTIONS\n');
      buffer.writeln('=' * 40);
      buffer.writeln('\nBased on content density: High');
      buffer.writeln('\nRecommended Margins (A4):');
      buffer.writeln('  - Top: 2.54 cm');
      buffer.writeln('  - Bottom: 2.54 cm');
      buffer.writeln('  - Left: 1.9 cm');
      buffer.writeln('  - Right: 1.9 cm');
      buffer.writeln('\nGutter for Binding: 0.5 cm (Left)');

      setState(() {
        _status = buffer.toString();
        _isLoading = false;
      });
    });
  }

  void _suggestColorScheme() {
    setState(() {
      _isLoading = true;
      _status = 'Generating color palette...';
    });

    Future.delayed(const Duration(seconds: 1), () {
      if (!mounted) return;

      final buffer = StringBuffer('COLOR SCHEME SUGGESTIONS\n');
      buffer.writeln('=' * 40);
      buffer.writeln('\nBase Theme: Corporate Blue');
      buffer.writeln('\nPalette:');
      buffer.writeln('  - Primary: #1E88E5 (Blue)');
      buffer.writeln('  - Secondary: #FFC107 (Amber)');
      buffer.writeln('  - Accent: #43A047 (Green)');
      buffer.writeln('  - Background: #F5F5F5 (Light Gray)');
      buffer.writeln('  - Text: #212121 (Dark Gray)');
      buffer.writeln('\nContrast Ratio: 7.5:1 (AAA Pass)');

      setState(() {
        _status = buffer.toString();
        _isLoading = false;
      });
    });
  }

  void _optimizeLayout() {
    setState(() {
      _isLoading = true;
      _status = 'Running full layout optimization...';
    });

    Future.delayed(const Duration(seconds: 2), () {
      if (!mounted) return;

      final buffer = StringBuffer('FULL LAYOUT OPTIMIZATION\n');
      buffer.writeln('=' * 40);
      buffer.writeln('\nOptimization Complete');
      buffer.writeln('\nImprovements Found:');
      buffer.writeln('  - Reduced whitespace by 15%');
      buffer.writeln('  - Aligned 4 misaligned elements');
      buffer.writeln('  - Adjusted font hierarchy for better scanning');
      buffer.writeln('  - Optimized image placement');
      buffer.writeln('\nEstimated Page Count: Reduced from 5 to 4 pages');

      setState(() {
        _status = buffer.toString();
        _isLoading = false;
      });
    });
  }

  void _summarizeText() {
    setState(() {
      _isLoading = true;
      _status = 'Summarizing text...';
    });

    // Simulate AI processing
    Future.delayed(const Duration(seconds: 1), () {
      if (!mounted) return;
      _analyzeReportText(); // Re-use the logic for demo
    });
  }

  void _detectLanguage() {
    setState(() {
      _isLoading = true;
      _status = 'Detecting language...';
    });

    Future.delayed(const Duration(milliseconds: 800), () {
      if (!mounted) return;

      final buffer = StringBuffer('LANGUAGE DETECTION\n');
      buffer.writeln('=' * 40);
      buffer.writeln('\nInput Text: "مرحباً بكم في نظام جينيس سيستمز"');
      buffer.writeln('\nDetected: Arabic (ar)');
      buffer.writeln('Confidence: 99.8%');
      buffer.writeln('Script: Arabic');
      buffer.writeln('Direction: RTL');

      setState(() {
        _status = buffer.toString();
        _isLoading = false;
      });
    });
  }

  void _generateTitles() {
    setState(() {
      _isLoading = true;
      _status = 'Generating titles...';
    });

    Future.delayed(const Duration(seconds: 1), () {
      if (!mounted) return;

      final buffer = StringBuffer('SMART TITLE GENERATION\n');
      buffer.writeln('=' * 40);
      buffer.writeln('\nContext: Monthly sales data for Q1 2026');
      buffer.writeln('\nSuggested Titles:');
      buffer.writeln('  1. Q1 2026 Sales Performance Overview');
      buffer.writeln('  2. Monthly Revenue Analysis: January - March 2026');
      buffer.writeln('  3. Commercial Growth Report Q1 2026');
      buffer.writeln('  4. First Quarter Financial Summary');

      setState(() {
        _status = buffer.toString();
        _isLoading = false;
      });
    });
  }

  void _extractKeywords() {
    setState(() {
      _isLoading = true;
      _status = 'Extracting keywords...';
    });

    // Using invoice text logic for demo
    Future.delayed(const Duration(seconds: 1), () {
      if (!mounted) return;
      _analyzeInvoiceText();
    });
  }
}
