// Generated by migrate_modern_vouchers_printing_security_to_global_manager.py
// Background dispatcher for Modern Vouchers PDF examples.

import 'dart:isolate';
import 'dart:typed_data';

import 'package:flutter/material.dart' show TextDirection;
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/features/modern_vouchers/models/documents/modern_vouchers_demo_documents.dart';
import 'package:genius_pdf_example/shared/application/services/example_background_pdf_config.dart';

Future<TransferableTypedData> _worker(Map<String, Object?> message) async {
  final config = restoreExamplePdfConfig(
    message['config']! as Map<String, Object?>,
  );
  ExampleDependencies.configure(pdfConfig: config);
  final apiName = message['apiName']! as String;

  final Uint8List bytes = switch (apiName) {
    'generateB5PaymentVoucherPdf' => await generateB5PaymentVoucherPdf(config),
    'generateModernPurchaseReturnVoucherPdf' => await generateModernPurchaseReturnVoucherPdf(config),
    'generateModernPurchaseVoucherPdf' => await generateModernPurchaseVoucherPdf(config),
    'generateModernSalesReturnVoucherPdf' => await generateModernSalesReturnVoucherPdf(config),
    'generateModernSalesVoucherPdf' => await generateModernSalesVoucherPdf(config),
    _ => throw ArgumentError.value(
        apiName,
        'apiName',
        'Unsupported Modern Vouchers background example',
      ),
  };

  return TransferableTypedData.fromList(<Uint8List>[bytes]);
}

/// Runs one Modern Vouchers document generator outside the UI isolate.
Future<Uint8List> generateModernVoucherInBackground({
  required String apiName,
  required bool isRtl,
  required GeniusPdfConfig rootConfig,
}) async {
  final config = rootConfig.copyWith(
    textDirection: isRtl ? TextDirection.rtl : TextDirection.ltr,
  );
  final message = <String, Object?>{
    'config': captureExamplePdfConfig(config),
    'apiName': apiName,
  };

  final result = await Isolate.run<TransferableTypedData>(
    () => _worker(message),
    debugName: 'modern-voucher-$apiName',
  );
  return result.materialize().asUint8List();
}
