// GENERATED BY redesign_remaining_multi_example_screens.py
// Internal single-example host. Navigation never exposes a tabbed aggregate UI.

import 'package:flutter/material.dart';
import 'package:genius_pdf_example/app/dependencies/example_dependencies.dart';
import 'package:genius_pdf_example/features/export/presentation/controllers/export_demo_controller.dart';
import 'package:genius_link_pdf_generator/genius_link_pdf_generator.dart'
    hide EdgeInsets, Colors;

import 'package:genius_pdf_example/app/theme/app_theme.dart';
import 'package:genius_pdf_example/shared/presentation/widgets/component_page.dart';
import 'package:genius_pdf_example/shared/presentation/widgets/feature_example_page.dart';
// import 'package:genius_pdf_example/shared/presentation/widgets/custom_tab_bar.dart';

/// Demo screen for multi-format export features.
class ExportSingleExampleHost extends StatefulWidget {
  const ExportSingleExampleHost({
    super.key,
    this.initialTab = 0,
    this.controller,
  });

  final int initialTab;
  final ExportDemoController? controller;

  @override
  State<ExportSingleExampleHost> createState() => _ExportSingleExampleHostState();
}

class _ExportSingleExampleHostState extends State<ExportSingleExampleHost> {
  late final ExportDemoController _controller;
  late final bool _ownsController;
  @override
  void initState() {
    super.initState();
    _ownsController = widget.controller == null;
    _controller = widget.controller ?? ExportDemoController(
      config: geniusPdfConfig,
      documents: demoDocuments,
    );
    _controller.addListener(_onControllerChanged);
    _controller.initialize();
  }

  void _onControllerChanged() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
_controller.removeListener(_onControllerChanged);
    if (_ownsController) _controller.dispose();
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final index = widget.initialTab.clamp(0, 2);

    return switch (index) {
        0 => _buildImageExportTab(isDark),
        1 => _buildDocExportTab(isDark),
        2 => _buildBatchExportTab(isDark),
        _ => _buildImageExportTab(isDark),
    };
  }
  Widget _buildImageExportTab(bool isDark) {
    return ComponentPage(
      title: 'Image Export',
      description:
          'Export PDF pages as high-quality PNG or compressed JPEG images.',
      icon: Icons.image_rounded,
      gradient: AppColors.infoGradient,
      isDark: isDark,
      isRTL: _controller.isRtl,
      onRTLChanged: _controller.setRtl,
      isGenerating: _controller.isLoading,
      onGenerate: null,
      codeExample: '''
final config = GeniusExportConfiguration.image(
  format: GeniusExportFormat.png,
  quality: GeniusImageQuality.high,
);
await service.export(doc, config);
''',
      preview: Column(
        children: [
          Row(
            children: [
              Expanded(
                child: _ExportCard(
                  isDark: isDark,
                  icon: Icons.image_rounded,
                  label: 'PNG',
                  sublabel: 'High quality',
                  gradient: AppColors.infoGradient,
                  onPressed: _controller.isReady && !_controller.isLoading
                      ? () => _exportTo(GeniusExportFormat.png)
                      : null,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: _ExportCard(
                  isDark: isDark,
                  icon: Icons.photo_rounded,
                  label: 'JPEG',
                  sublabel: 'Compressed',
                  gradient: AppColors.orangeGradient,
                  onPressed: _controller.isReady && !_controller.isLoading
                      ? () => _exportTo(GeniusExportFormat.jpeg)
                      : null,
                ),
              ),
            ],
          ),
          const SizedBox(height: 16),
          _buildStatusAndResult(isDark),
        ],
      ),
    );
  }

  Widget _buildDocExportTab(bool isDark) {
    return ComponentPage(
      title: 'Document Export',
      description: 'Export to HTML, plain text, or PDF/A archival format.',
      icon: Icons.description_rounded,
      gradient: AppColors.purpleGradient,
      isDark: isDark,
      isRTL: _controller.isRtl,
      onRTLChanged: _controller.setRtl,
      isGenerating: _controller.isLoading,
      onGenerate: null,
      codeExample: '''
// HTML Export
final htmlConfig = GeniusExportConfiguration.html(
  embedImages: true,
  includeStyles: true,
);

// PDF/A Export
final pdfaConfig = GeniusExportConfiguration.pdfA(
  compress: true,
);
''',
      preview: Column(
        children: [
          Row(
            children: [
              Expanded(
                child: _ExportCard(
                  isDark: isDark,
                  icon: Icons.html_rounded,
                  label: 'HTML',
                  sublabel: 'Web format',
                  gradient: AppColors.purpleGradient,
                  onPressed: _controller.isReady && !_controller.isLoading
                      ? () => _exportTo(GeniusExportFormat.html)
                      : null,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: _ExportCard(
                  isDark: isDark,
                  icon: Icons.text_snippet_rounded,
                  label: 'Text',
                  sublabel: 'Plain text',
                  gradient: AppColors.tealGradient,
                  onPressed: _controller.isReady && !_controller.isLoading
                      ? () => _exportTo(GeniusExportFormat.text)
                      : null,
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          _ExportCard(
            isDark: isDark,
            icon: Icons.archive_rounded,
            label: 'PDF/A (Archival)',
            sublabel: 'Long-term preservation',
            gradient: AppColors.successGradient,
            onPressed: _controller.isReady && !_controller.isLoading
                ? () => _exportTo(GeniusExportFormat.pdfA)
                : null,
          ),
          const SizedBox(height: 16),
          _buildStatusAndResult(isDark),
        ],
      ),
    );
  }

  Widget _buildBatchExportTab(bool isDark) {
    return ComponentPage(
      title: 'Batch Export',
      description: 'Export to multiple formats simultaneously in background.',
      icon: Icons.dynamic_feed_rounded,
      gradient: AppColors.primaryGradient,
      isDark: isDark,
      isRTL: _controller.isRtl,
      onRTLChanged: _controller.setRtl,
      isGenerating: _controller.isLoading,
      onGenerate: null,
      codeExample: '''
final exporter = GeniusBatchExporter(maxConcurrent: 2);
final results = await exporter.exportToMultipleFormats(
  document,
  [
    GeniusExportFormat.png,
    GeniusExportFormat.html,
    GeniusExportFormat.text
  ],
);
''',
      preview: Column(
        children: [
          _ExportCard(
            isDark: isDark,
            icon: Icons.dynamic_feed_rounded,
            label: 'Export to All Formats',
            sublabel: 'PNG, HTML, Text',
            gradient: AppColors.primaryGradient,
            onPressed:
                _controller.isReady && !_controller.isLoading ? _batchExport : null,
          ),
          const SizedBox(height: 16),
          _buildStatusAndResult(isDark),
        ],
      ),
    );
  }

  Widget _buildStatusAndResult(bool isDark) {
    return Column(
      children: [
        _buildStatusCard(isDark),
        if (_controller.lastResult != null) ...[
          const SizedBox(height: 16),
          _buildResultCard(isDark),
        ],
      ],
    );
  }
  Widget _buildStatusCard(bool isDark) {
    return FeatureStatusPanel(
      message: _controller.status.isEmpty ? 'Ready for export.' : _controller.status,
      loading: _controller.isLoading,
      tone: _controller.isReady
          ? FeatureExampleTone.success
          : FeatureExampleTone.info,
    );
  }
  Widget _buildResultCard(bool isDark) {
    final result = _controller.lastResult;
    if (result is GeniusExportSuccess) {
      return Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          FeatureStatusPanel(
            message: 'Export completed successfully.',
            tone: FeatureExampleTone.success,
          ),
          const SizedBox(height: 10),
          _buildInfoRow(isDark, 'Format', result.format.displayName),
          _buildInfoRow(isDark, 'Pages', '${result.pageCount}'),
          _buildInfoRow(isDark, 'Size', result.fileSizeFormatted),
          if (_controller.lastFilePath != null)
            _buildInfoRow(isDark, 'Path', _controller.lastFilePath!),
          if (_controller.lastFilePath != null) ...<Widget>[
            const SizedBox(height: 10),
            Align(
              alignment: AlignmentDirectional.centerEnd,
              child: OutlinedButton.icon(
                onPressed: _openLastFile,
                icon: const Icon(Icons.open_in_new_rounded),
                label: const Text('Open exported file'),
              ),
            ),
          ],
        ],
      );
    }
    if (result is GeniusExportFailure) {
      return FeatureStatusPanel(
        message: result.message,
        tone: FeatureExampleTone.danger,
      );
    }
    return const SizedBox.shrink();
  }

  Widget _buildInfoRow(bool isDark, String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 60,
            child: Text(
              '$label:',
              style: TextStyle(
                fontWeight: FontWeight.w500,
                color: isDark ? AppColors.darkText : AppColors.lightText,
              ),
            ),
          ),
          Expanded(
            child: Text(
              value,
              style: TextStyle(
                color: isDark
                    ? AppColors.darkTextSecondary
                    : AppColors.lightTextSecondary,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Future<void> _exportTo(GeniusExportFormat format) =>
      _controller.exportTo(format);

  Future<void> _batchExport() => _controller.batchExport();

  Future<void> _openLastFile() async {
    try {
      await _controller.openLastFile();
    } catch (error) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Failed to open file: $error'),
          backgroundColor: AppColors.error,
        ),
      );
    }
  }
}

class _ExportCard extends StatelessWidget {
  final bool isDark;
  final IconData icon;
  final String label;
  final String sublabel;
  final List<Color> gradient;
  final VoidCallback? onPressed;

  const _ExportCard({
    required this.isDark,
    required this.icon,
    required this.label,
    required this.sublabel,
    required this.gradient,
    this.onPressed,
  });

  @override
  Widget build(BuildContext context) {
    return FeatureActionCard(
      title: label,
      subtitle: sublabel,
      icon: icon,
      onPressed: onPressed,
    );
  }
}
